### ISSUE TITLE
stack_output resolution fails when used in sceptre_user_data

### ISSUE THREAD

**Issue by joe1981al** [Sceptre/sceptre#1000]
## issue
Will get "Stack with id <id> does not exist" when a stack_output resolver is used in the sceptre_user_data section of config and points to another config file.  This only occurs when the stack being referenced is not actually running yet.

When using the same stack_output line in the parameter section it understands that the other stack is a dependency and does not through an error.

## expected behavior
I would expect the same behavior between parameters and sceptre_user_data sections of the template when using stack_output resolver.

**Comment by craighurley** [comment]
Hi @joe1981al , it always helps to include example code and the error you get; can you please add?

**Comment by joe1981al** [comment]
@craighurley  https://github.com/joe1981al/sceptre_error_example

**Comment by jfalkenstein** [comment]
I actually ran into this bug very recently. The issue results from how (unlike parameters), sceptre_user_data is accessed to pass in to actually render the templates for jinja and python based templates. 

I had to implement a custom hook that allows you to replace the sceptre_user_data on the stack before_validate and before_generate. It's a bit of a hacky workaround, but it works. It does seem like we might want a better option. 

I think a viable approach to this would be a toggle on the stack (or maybe a globally available variable?) that causes the StackOutput resolver to catch that error and instead return a default, like "<StackOutput('Vpc::VpcId')>", but ONLY when doing certain non-creation activities that require a template, like validation, generation, etc...

**Comment by sopeters** [comment]
I have this issue with the `validate` command even when the stack exists - getting
`stack for stack in self.stack.dependencies if stack.name == friendly_stack_name`

Will the PR fix this as well?

**Comment by jfalkenstein** [comment]
It's not clear what that error is that you're describing. Could you include more detail?

**Comment by jfalkenstein** [comment]
This issue has been generally resolved (as best as possible) with the use of placeholders now that #1185 has been merged.
