### ISSUE TITLE
Use stack output in an after_create hook

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1025]
### Use stack output in an after_create hook

I would like to be able to use the stack_output of the current stack and then pass that to an `after_create` hook. Is this possible? Reading the code suggests no and I can't find any examples to suggest that it is. If not possible, could this be a feature request?

**Comment by craighurley** [comment]
Related to #329

**Comment by zaro0508** [comment]
this is already labeled as a feature request in #329
