### ISSUE TITLE
Output of sceptre generate command is broken in 2.5.0

### ISSUE THREAD

**Issue by jlehtiniemi** [Sceptre/sceptre#1032]
### Subject of the issue
The `sceptre generate` command produces garbled output. Source templates are YAML, no Jinja templating is used.

### Your environment
The issue has been reproduced with following setups:

Sceptre version:
* 2.5.0

Python versions:
* 3.8.10
* 3.9.5

OS versions:
* macOS Catalina 10.15.7
* Ubuntu 20.04

Installed packages in local v-env:

```text
❯ pip freeze
appdirs==1.4.4
attrs==21.2.0
aws-sam-translator==1.35.0
boto3==1.17.68
botocore==1.20.68
certifi==2020.12.5
cfgv==3.2.0
cfn-lint==0.49.0
chardet==4.0.0
click==7.1.2
colorama==0.4.4
decorator==4.4.2
distlib==0.3.1
filelock==3.0.12
identify==2.2.4
idna==2.10
Jinja2==2.11.3
jmespath==0.10.0
jsonpatch==1.32
jsonpointer==2.1
jsonschema==3.2.0
junit-xml==1.9
MarkupSafe==1.1.1
networkx==2.5.1
nodeenv==1.6.0
packaging==16.8
pre-commit==2.12.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
PyYAML==5.4.1
requests==2.25.1
ruamel.yaml==0.15.100
s3transfer==0.4.2
sceptre==2.5.0
sceptre-stack-termination-protection-hook==1.1.0
six==1.16.0
toml==0.10.2
urllib3==1.26.4
virtualenv==20.4.6
```

### Steps to reproduce
Example command used to produce the issue

```bash
sceptre generate dev/eu-west-1/infra/iam-roles.yaml
```

### Expected behaviour
Expected output snippet with Sceptre v2.4.0:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: IAM Infra Roles
Parameters:
  ApplicationName:
    Description: Name of the application
    Type: String
  KmsEnvironmentKeyArns:
    Description: List of KMS key IDs with access to environment settings, normally ReadOnly access
```

### Actual behaviour
Output snippet with Sceptre v2.5.0:

```text
A    W    S    T    e    m    p    l    a    t    e    F    o    r    m    a    t    V    e    r    s    i    o    n    :         2    0    1    0    -    0    9    -    0    9    
    D    e    s    c    r    i    p    t    i    o    n    :         I    A    M         I    n    f    r    a         R    o    l    e    s    
    
    P    a    r    a    m    e    t    e    r    s    :    
              A    p    p    l    i    c    a    t    i    o    n    N    a    m    e    :    
                        D    e    s    c    r    i    p    t    i    o    n    :         N    a    m    e         o    f         t    h    e         a    p    p    l    i    c    a    t    i    o    n    
                        T    y    p    e    :         S    t    r    i    n    g    
              K    m    s    E    n    v    i    r    o    n    m    e    n    t    K    e    y    A    r    n    s    :    
                        D    e    s    c    r    i    p    t    i    o    n    :         L    i    s    t         o    f         K    M    S         k    e    y         I    D    s         w    i    t    h         a    c    c    e    s    s         t    o         e    n    v    i    r    o    n    m    e    n    t         s    e    t    t    i    n    g    s    ,         n    o    r    m    a    l    l    y         R    e    a    d    O    n    l    y         a    c    c    e    s    s    
                        T    y    p    e    :         L    i    s    t    <    S    t    r    i    n    g    >
```

**Comment by glisha** [comment]
I have the same problem on Amazonlinux. With or without Jinja templates.

# pip3 freeze
boto3==1.17.68
botocore==1.20.68
click==7.1.2
colorama==0.4.4
decorator==4.4.2
Jinja2==2.11.3
jmespath==0.10.0
MarkupSafe==1.1.1
networkx==2.5.1
packaging==16.8
pyparsing==2.4.7
python-dateutil==2.8.1
PyYAML==5.4.1
s3transfer==0.4.2
sceptre==2.5.0
six==1.16.0
urllib3==1.26.4

**Comment by glisha** [comment]
`sceptre --output yaml generate cfn.yaml` gives you the expected behavior.

**Comment by jlehtiniemi** [comment]
Can confirm that `sceptre --output yaml generate cfn.yaml` works for me too.

**Comment by craighurley** [comment]
The default output was changed from text to json here: https://github.com/Sceptre/sceptre/commit/65142f9b696b5ff98febff32c4e71396a2698225

... and then from json back to text in this PR: https://github.com/Sceptre/sceptre/pull/832

I think it's time to revisit the default. @zaro0508 and @lukeplausin, do you want to add your thoughts here?

**Comment by lukeplausin** [comment]
We should be able to use the `sceptre generate` command to troubleshoot templating issues. The old behaviour of transforming text to json caused problems as sceptre would crash if the template contained any syntax errors which meant that the template could not be transformed into json.
Personally I think that the `sceptre generate` command should just dump the compiled template as-is to stdout without any dependencies or trying to do anything too clever with it. We could add command line options to include dependencies or transform into other formats.

**Comment by jlehtiniemi** [comment]
Our use case here is that we use `sceptre generate` to generate the actual template that would be sent to CloudFormation offline, we then pipe the generated templates to `cfn-lint` in order to be able to lint the actual CloudFormation templates, and because `cfn-lint` of course cannot lint the templates that have Jinja templating in them. It would also be very helpful if the output of the `sceptre generate` would be fully machine-readable, at least with some optional command line parameter.

**Comment by zaro0508** [comment]
I have verified that the culprit is PR #918

**Comment by szechyjs** [comment]
This is definitely a regression caused by #918.

With v2.4.0 `sceptre generate config.yml` works as expected.

With v2.5.0 it outputs `    ` between every character of the expected output.

The advice above to use `--output yaml` does not work either as it reformats the template root to an array instead of an object.
