### ISSUE TITLE
Bug: dependencies fails initially but passes upon re-issuing the create command

### ISSUE THREAD

**Issue by JoeArmstrong** [Sceptre/sceptre#1049]
### Subject of the issue
When running a 'sceptre create dev/vt2' (where vt2 has several stacks defined) the earliest stack that needs to be deployed gets correctly deployed but then prior to deploying dependent stacks, the test to see if the first stack is deployed fails (but sceptre just finished deploying it).

Re-issuing the command immediately after the failure succeeds.

**Partial command output**

*deployment of vt2-mx-nlb-inbound1 proceeds normally to here*

> [2021-05-25 14:24:17] - dev/vt2/mx-nlb-inbound1 vt2-mx-nlb-inbound1 AWS::CloudFormation::Stack CREATE_COMPLETE 
> "An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with id vt2-mx-nlb-inbound1 does not exist"
> 

*re-issuing the command after the above failure*
> sceptre create dev/vt2
> Do you want to create 'dev/vt2' [y/N]: y
> [2021-05-25 14:26:26] - dev/vt2/mx-nlb-inbound1 - Creating Stack
> [2021-05-25 14:26:28] - dev/vt2/mx-nlb-inbound1 - Stack already exists
> [[ and the deployment goes on as it should from here ]]
> 

### Your environment
- Sceptre, version 2.5.0
- Python 3.9.1
- macOs Catalina (10.15.7)

### Steps to reproduce
-Create a set of stacks that use 'dependencies'
-sceptre create dev/vt2
--creation of first stack will succeed, but will fail with the first stack not being found (shown above)
-sceptre create dev/vt2
--creation will succeed

### Expected behaviour
sceptre should find the stack it just created 

### Actual behaviour
sceptre fails to find the stack it just created

### Directory structure and file contents

**Directory structure**

./config                                                                                                                               
./config/config.yaml
./config/dev
./config/dev/config.yaml
./config/dev/vt2
./config/dev/vt2/config.yaml
./config/dev/vt2/mx-nlb-inbound1.yaml
./config/dev/vt2/mx-nlb-inbound1-asg-green.yaml
./templates
./templates/generic_asg.yaml
./templates/mx-nlb.yaml

**contents of mx-nlb-inbound1-asg-green.yaml:**

template_path: generic_asg.yaml                                                                                                                
stack_name: vt2-mx-nlb-inbound1-asg-green

dependencies:
    - dev/vt2/mx-nlb-inbound1.yaml
    
**contents of mx-nlb-inbound1.yaml:**

template_path: mx-nlb.yaml                                                                                                                     
stack_name: vt2-mx-nlb-inbound1

**Comment by zaro0508** [comment]
I think you use the `create` command @ykhalyavin,  are you seeing anything like this in your executions?

**Comment by ykhalyavin** [comment]
We use launch for everything. I just tested sceptre 2.6.3 create command on a folder with multiple subfolders and lots of stack configurations in those subfolders with interdependencies. Worked fine. Maybe the issue is in a specific circumstance?

**Comment by zaro0508** [comment]
cannot reproduce.
