### ISSUE TITLE
Print context for errors when loading stacks

### ISSUE THREAD

**Issue by ianburrell** [Sceptre/sceptre#1055]
### Subject of the issue

Sceptre loads all stacks to check for dependencies. It can be hard to track down errors from loading the files because Sceptre does not print the filename that has the error. Even better if can print the line in file.

### Your environment
* Sceptre 2.5.0
* Python 3.8.9
* macOS

### Steps to reproduce

Stack file with variable without default:

Image: '{{ var.app_Image }}'

### Expected behaviour

Sceptre should print the file containing error.

config/qa/app.yaml:
"'dict object' has no attribute 'app_Image'"

### Actual behaviour

Sceptre only prints the error. For example:

"'dict object' has no attribute 'app_Image'"

**Comment by zaro0508** [comment]
related to #1048

**Comment by ericabrauer** [comment]
I'd like to be assigned to this if I could

**Comment by ericabrauer** [comment]
Thanks @zaro0508! Is there someone who I can go to if I have questions? I was wanting to create a test for this but I'm not sure if I'm following correctly. I think I'm close to understanding where the fix should be applied though.

**Comment by zaro0508** [comment]
@ericabrauer you can ask questions in our slack channel https://docs.sceptre-project.org/2.7.0/#communication

**Comment by ericabrauer** [comment]
Ah that makes sense, I'll reach out there and see if anyone can walk me through a general overview maybe. Thanks so much!

**Comment by jfalkenstein** [comment]
This issue was resolved recently with work on exception handling. Using the `--debug` flag solves this issue.
