### ISSUE TITLE
Add feature -U allowing sceptre change-sets to display as URLs

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1064]
I would like to add an option `-U, --url` that modifies the behaviour of the [`list change-sets`](https://sceptre.cloudreach.com/2.3.0/docs/cli.html#sceptre-list) command to optionally display change sets as URLs that take us to the change sets' pages in the AWS console. I am working on this feature in our fork of Sceptre with a view to merging it upstream if it is accepted.

**Comment by zxiiro** [comment]
This sounds like a reasonable improvement to me. Are the URLs very long? if not maybe even just make it default to print it.

**Comment by mrowlingfox** [comment]
At Foxtel we find this functionality very helpful. I would +1 recommend implementing this upstream

**Comment by craighurley** [comment]
I like it.  @alexharv074 can you provide a sample output from your fork, that includes the default output, and another one with the output after passing this arg?

**Comment by alexharv074** [comment]
@craighurley Here you go

## Before this change

<img width="1085" alt="Screen Shot 2021-09-09 at 2 10 37 am" src="https://user-images.githubusercontent.com/2305330/132549597-8bf6463e-23f6-452b-88ff-3c7fe4b67b59.png">

## After this change

Showing if I add `-U` to the command line after the `list change-sets` command, I receive back URLs to the AWS Console:

<img width="1087" alt="Screen Shot 2021-09-09 at 2 37 11 am" src="https://user-images.githubusercontent.com/2305330/132549674-49e477fd-a4a4-437c-b819-648eb1a0e869.png">

**Comment by alexharv074** [comment]
@zxiiro 

> This sounds like a reasonable improvement to me. Are the URLs very long? if not maybe even just make it default to print it.

I guess that would be a breaking change that would need to be considered in a major release?

**Comment by zxiiro** [comment]
> @zxiiro
> 
> > This sounds like a reasonable improvement to me. Are the URLs very long? if not maybe even just make it default to print it.
> 
> I guess that would be a breaking change that would need to be considered in a major release?

Oh I see looks like we're overwriting the JSON that's returned (I thought it was adding an additional entry). Okay in that case maybe leave the default as is with the switch.

**Comment by craighurley** [comment]
Looks good @alexharv074
