### ISSUE TITLE
Variable substitution in comments of config file

### ISSUE THREAD

**Issue by scottdonaldau** [Sceptre/sceptre#1069]
### Subject of the issue
If you have a comment in a yaml config file, that happens to contain the string "{{" and does not close it, Sceptre will fail. Sceptre should not attempt variable substitution within commented out blocks.

### Your environment
* version of sceptre 2.5.0
* version of python 3.9
* which OS/distro Amazon Linux

### Steps to reproduce
Have a comment with {{ in it within a sceptre config file.

### Expected behaviour
It should leave commented out parts alone.

### Actual behaviour
Attempts variable substitution within comments

**Comment by zaro0508** [comment]
I think this might be due to jinja processing which is expected.  would you be able to provide an example file to reproduce @scottdonaldau ?  Alternatively would you be able to try commenting with jinja comment syntax (`{# ... #}`)? https://jinja.palletsprojects.com/en/3.0.x/templates/#comments

**Comment by zaro0508** [comment]
no reply from report so closing this issue.
