### ISSUE TITLE
change to stack dependency processing starting with release 2.6.0?

### ISSUE THREAD

**Issue by himmelmrm** [Sceptre/sceptre#1078]
Is this a bug?

### environment
* sceptre 2.5.0 & 2.6.0
* Python 3.7.9
* Fedora release 34 (Thirty Four)

### Discussed in https://github.com/Sceptre/sceptre/discussions/1076

<div type='discussions-op-text'>

<sup>Originally posted by **himmelmrm** August  3, 2021</sup>
Has stack dependency processing changed starting with 2.6.0?  Previous to 2.6.0, deleting a stack would calculate and delete dependent stacks (referenced by !stack_output), -- likewise with create.  However, now stack dependency processing seems to only be done with create?

For example:

```
$ pipenv run sceptre --version
Sceptre, version 2.5.0
$ pipenv run sceptre delete lampdemo/prod/subnets.yaml
The following stacks, in the following order, will be deleted:
lampdemo/dns/dns
lampdemo/prod/routes
lampdemo/prod/load-balancers
lampdemo/prod/lamp-server-1
lampdemo/prod/volumes
lampdemo/prod/subnets

$ pipenv run sceptre --version
Sceptre, version 2.6.0
$ pipenv run sceptre delete lampdemo/prod/subnets.yaml
The following stacks, in the following order, will be deleted:
lampdemo/prod/subnets
```
</div>

**Comment by zaro0508** [comment]
Yes, I have verified that this is a regression introduced by PR #1043.  Would you be able to look at this issue @lucasvieirasilva ?

**Comment by lucasvieirasilva** [comment]
> Yes, I have verified that this is a regression introduced by PR #1043.  Would you be able to look at this issue @lucasvieirasilva ?

Hi @zaro0508, yes, I can have a look at this, @himmelmrm thanks for the feedback!

**Comment by zaro0508** [comment]
thanks @lucasvieirasilva, here is a test project I used to reproduce. https://plnkr.co/edit/37YJRGuBygutxha2

**Comment by zaro0508** [comment]
@lucasvieirasilva the sceptre community has decided that it would be best to revert PR #1043 unless you can come up with a fix fairly quickly, probably within a week.  if you would like to engage discussion around this topic then please join us on slack, instructions to join are here: https://sceptre.cloudreach.com/2.6.2/index.html?highlight=slack#communication

**Comment by lucasvieirasilva** [comment]
> @lucasvieirasilva the sceptre community has decided that it would be best to revert PR #1043 unless you can come up with a fix fairly quickly, probably within a week.  if you would like to engage discussion around this topic then please join us on slack, instructions to join are here: https://sceptre.cloudreach.com/2.6.2/index.html?highlight=slack#communication    

Understood, Will try to fix this issue in less than a week.

**Comment by lucasvieirasilva** [comment]
@zaro0508 PR https://github.com/Sceptre/sceptre/pull/1081 raised regarding this issue.
