### ISSUE TITLE
role_arn Session Timeout

### ISSUE THREAD

**Issue by davemorrow-telus** [Sceptre/sceptre#1080]
I guess this is somewhat of a feature request.

An additional option when specifying role_arn to allow the use of a custom session timeout would be really helpful. I have a sceptre project which takes 3 hours to deploy.  My Role in AWS has a session timeout of 4hrs (which works when manually assuming the role with other tools) ex. the AWS CLI allows --session-duration

AWS Linux 2
Python 3.7
sceptre 2.6.2

Run a sceptre project that takes > 1hr

Session token expires.

**Comment by zaro0508** [comment]
I'm not a security expert but it seems to me that your feature request may expose some type of security problem?  For example the role you assume for running sceptre would need to have permissions to extend a session?  The problem with that is whoever gave you access to that role probably does not want you to go beyond your session duration.  Would this feature not circumvent the session duration restriction?

**Comment by zaro0508** [comment]
closing this issue due to no reply from reporter
