### ISSUE TITLE
troposphere not installed with sceptre

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#1090]
Scepter supports the deployment of [troposphere templates](https://github.com/cloudtools/troposphere) however the troposphere library does not get installed on a sceptre install because the library dependency is not setup.  This means that troposphere must be installed separately from sceptre in order to use it.  The problem with that is that users may install a version of troposphere that may not work with sceptre.  To fix this issue I think we should add a versioned troposphere dependency to sceptre so that users will get a version that is tested and will most likey work with the installed version of scepter.

**Comment by tarkatronic** [comment]
I would highly recommend not forcing the install of an extra package when it is not necessary. A great alternative would be to add this as an optional/extra dependency. This way, users can easily install a compatible version, but only when needed. This can be achieved by adding the following to the `setup()` call in `setup.py`:

```python
extas_require={
    "troposphere": ["troposphere>=X,<Y"],
}
```

Then to install it, a user would install `sceptre[troposphere]`. For instance: `pip install sceptre[troposphere]`.

**Comment by tarkatronic** [comment]
An example of this can be found in the widely used `coverage` package, here: https://github.com/nedbat/coveragepy/blob/master/setup.py#L108-L111 and here: https://coverage.readthedocs.io/en/coverage-5.5/config.html?highlight=toml#configuration-reference

**Comment by jfalkenstein** [comment]
This might be problematic with the current issue Troposphere is facing with setuptools: https://github.com/cloudtools/troposphere/issues/1952. I ran into this issue this past weekend when I was trying to get my dev environment setup for Sceptre and tried to run `tox`.

**Comment by zxiiro** [comment]
I don't use Troposphere but my opinion when it comes to optional dependencies depends on the dependency. Personally I like a batteries included approach if the optional dependencies are small and neglible to the package if included. Like if it's the difference between a couple of MB then I think just including it makes for easier user experience.

On the other hand if the optional depencency is large or problematic to include like if it requires compiling extra stuff outside Python then I prefer @tarkatronic's approach to create a optional pip install path.

**Comment by tarkatronic** [comment]
Looking at it from a security perspective, I prefer to install the minimum amount of code required to get the job done. More code/dependencies means a larger attack surface, and more potential places for vulnerabilities to hide.

"a couple of MB" of code is a LOT of code.

**Comment by zxiiro** [comment]
> Looking at it from a security perspective, I prefer to install the minimum amount of code required to get the job done. More code/dependencies means a larger attack surface, and more potential places for vulnerabilities to hide.

I totally get that and share the same opinion when it comes to security.

> "a couple of MB" of code is a LOT of code.

Agreed. I didn't really mean literal code but more like if the final package size difference is only a few MB diifference I don't mind including isolated dependencies. Especially if the code is fairly contained with no other outside dependencies to consider.

Not familiar with Troposphere but a quick look at their GitHub repo tells me this project's fairly large. I would make this one optional too.
