### ISSUE TITLE
The documentation on Custom Hooks is wrong

### ISSUE THREAD

**Issue by jfalkenstein** [Sceptre/sceptre#1102]
### Subject of the issue
The example of a Custom Hook in our docs is incorrect. It says that Hooks get a ConnectionManager kwarg, but they don't.

**Comment by zaro0508** [comment]
would you be able to specify exactly which doc you are referring to?  I believe sceptre hooks do have access to the  connection_manager, using `self.stack.connection_manager`.

**Comment by jfalkenstein** [comment]
Hi @zaro0508 Take a look at the PR I put up for this: https://github.com/Sceptre/sceptre/pull/1103/files.

Here's the place in the docs: 
![image](https://user-images.githubusercontent.com/77296393/134035412-736c7e31-5aa6-4697-aaa4-aca73aeb8736.png)

According to the sample, it seems like the connection manager is directly passed in (rather than what is really the case, that it can be obtained off the stack that is passed in). This confused one of my coworkers when I put up a PR for a custom hook in one of our local repos that used the stack's connection manager. He thought I should just use the hook's connection manager because he saw this in the docs.

**Comment by jfalkenstein** [comment]
@zaro0508 Now that the PR for this (https://github.com/Sceptre/sceptre/pull/1103) was merged, does anything else need to happen for this issue? Should it be resolved? Or would we wait until those changes actually get deployed in a new Sceptre version?

**Comment by zaro0508** [comment]
currently, docs are only publish when a new sceptre version is released.

**Comment by zaro0508** [comment]
fixed, closing issue
