### ISSUE TITLE
Sceptre should manage sceptre-required resources

### ISSUE THREAD

**Issue by jfalkenstein** [Sceptre/sceptre#1114]
### Subject of the issue
One of the "weird" things about the way Sceptre works right now is how it works with some settings like...
* `template_bucket_name` (It will create an S3 buckets for your templates if it doesn't exist already)
* `iam_role`: The role used to execute sceptre actions on a stack group
* `role_arn`: The Cloudformation service role to be assigned to the stack upon creation
* `notification_arns`: Arns for SNS topics to notify about stack actions

All of these are AWS service resources that Sceptre can operate with, but Sceptre doesn't (smoothly) support using Sceptre to create those things. They are either automatically created as byproducts of the first use (template_bucket_name) or they just have to already exist.

Here's what I mean:
* Only notification_arns is a resolvable property, so you can't use `!stack_output` to establish dependencies to those configurations, so you can't you pipe the outputs of other stacks into those settings.
* `template_bucket_name` really expects to be set at the highest level config (though it isn't strictly necessary), so you can't have a `template_bucket_name` set if you want to create a cloudformation template to create your template bucket.
* You can't `unset` template_bucket_name on a stack where it's been set at the project-level by setting the value to `null` or `~`. I tried doing this to define the template bucket in a stack config, but that doesn't work. It just blows up.
* You could get a little creative about having one stack group for the "sceptre necessities" and one for everything else, but then you have to set those "top-level" configurations one level down and duplicate it in a bunch of places
* **Sceptre doesn't currently support setting stack dependencies at the StackGroup level; It errors out when you try.** You can only set dependencies on individual stacks.

In other words, the only way to have Sceptre manage the sceptre-used dependencies for these things feels pretty hacky. And it isn't foolproof. You need to hardcode duplicated values between stack configurations to make that work and set up explicit dependencies on _every...single...stack_. And I can't really figure out a way to manage the template bucket via Sceptre very well.

### What I think could make Sceptre a lot better on this front
Other infrastructure management tools (I'm thinking SAM CLI) have a command that can generate cloudformation stack that defines the required infrastructure to run SAM CLI, so it's like a secondary shared stack. I think this is pretty slick.

1. **I think Screptre needs to support `dependencies` at the StackGroup level**, not just individual stacks. This should work all the way to the highest level, at the project level. This would let you say that every stack in the project depends on x, y, and z, so no stack can be built without those stacks existing. Of course, the stack that IS that dependency would be excluded. We'd need some special logic to say "Every stack except for Stack X (and its dependencies) depends on Stack X" 
2. **I think all four of the configurations listed above should be resolvable properties**, so that you can configure them in another stack and send the outputs into it.
3. **There needs to be a way to break the circular reference** that would be caused by defining a project-level template_bucket_name, but then defining that template_bucket_name using a stack in the project. Kind of like a "Use this configuration for everything BUT the place where it is actually created". I suppose the easiest way would be just to support setting this value to `null` or `~` on that stack config. But maybe a new resolver like `!core_stack_output` or something. I don't know. We should talk about that. 
4. **I _really_ think it would be useful if Sceptre could auto-generate a basic "sceptre-support" stack config and template**. Ideally, this would include:
    * The Template bucket
    * An execution IAM role with the basic Sceptre requirements
5. **That autogeneration command would update the project requirements with project-level references** to `iam_role` and `template_bucket_name` from outputs from that stack.

**Comment by jfalkenstein** [comment]
This is in reader.py

![image](https://user-images.githubusercontent.com/77296393/134825657-29c1ab7a-869a-4944-8924-263e2e88cca1.png)

**Comment by jfalkenstein** [comment]
The dependencies issue has also been reported in #946

**Comment by jfalkenstein** [comment]
The resolvable role arn has been partially developed in #887

**Comment by jfalkenstein** [comment]
I also recognize that this is a significant feature request... One I would be happy to help build. But I want to start discussion on these ideas and get some sense of project direction first. @zaro0508 @ngfgrant

**Comment by jfalkenstein** [comment]
@zxiiro since you're now a core maintainer, I'm tagging you in this as well.

**Comment by zxiiro** [comment]
@jfalkenstein The template bucket one is one that's cause me much annoyance and I'd love to see a clean resolution for that. For awhile I had a separate bootstrap script to bootstrap my Sceptre infra but that just seems silly to me when I want Sceptre to be my goto infra management tool.

While I don't mind that sceptre generates a bucket automatically for me, there is no way to configure the bucket (say like you want encryption turned on or something). One thing I think would be neat is if Sceptre created something like that but then you create a configuration for that Sceptre created resource it could automatically import it into the CloudFormation stack rather than just fail because you created something outside of the stack.

I don't use StackGroups so I don't have an opinion on that currently.

**Comment by craighurley** [comment]
Regarding s3 bucket encryption, I raised #491, which was closed in favor of focusing on #730, but tbh I'm not sure how #730 resolved it :(

**Comment by jfalkenstein** [comment]
I fixed the bug with inheriting dependencies here: https://github.com/Sceptre/sceptre/pull/1116
