### ISSUE TITLE
Replace unsupported cloudformation stack name characters with dash

### ISSUE THREAD

**Issue by felipe1982** [Sceptre/sceptre#1147]
### Subject of the issue
When a sceptre stack config file name include characters forbidden by cloudformation stack names, sceptre fails to successfully create the stack.

### Your environment
* version of sceptre (sceptre --version) 2.6.3
* version of python (python --version) 3.6.12
* which OS/distro OpenSUSE

### Steps to reproduce
create a sceptre config called bad.characters.yaml and deploy a cloudformation template. The stack will fail because the `.` period characters is not allowed in cloudformation stack names.

### Expected behaviour
Sceptre will transform invalid characters into hyphen `-` which is an allowed cloudformation character.

### Actual behaviour
The stack fails to launch due to invalid character names.

**Comment by zaro0508** [comment]
The AWS cloufformation CLI to deploy CFN stacks  "does not transform invalid characters into hyphen" so why should sceptre do that?  I think the better solution to this problem is to just do some syntax validation on your sceptre configs.  You may want to take a look at this [pre-commit validator](https://github.com/Sceptre/sceptre/discussions/925) to help you do the syntax checking.

**Comment by felipe1982** [comment]
Sceptre is already forming the stack name from the path of the stack config file (config/client/prod/network.yaml becomes "client-prod-network" as the stack name). Sceptre is already forming & creating the name. This is the reason why sceptre should remove unsupported characters it finds in the names. Is it documented that file names cannot use characters that cloudformation does not support?

**Comment by jfalkenstein** [comment]
Why not just not use periods in your config names? I'm not so sure this is an issue with Sceptre and more just a matter of  needing to name your stack configs in ways that are compatible with sceptre.

**Comment by zaro0508** [comment]
No reply from reporter so closing.
