### ISSUE TITLE
The Documentation Links in README.md Display a 404 'Site not found' Error

### ISSUE THREAD

**Issue by DG-SHeather** [Sceptre/sceptre#1163]
### Subject of the issue
All of  the Sceptre documentation links in `README.md` and the [sceptre.cloudreach.com](https://sceptre.cloudreach.com) link in the GitHub 'About' box display a 404 'Site not found error.

Should these links should be updated to relevant pages within [docs.sceptre-project.org](https://docs.sceptre-project.org/)?

**Comment by zainulabidin302** [comment]
[](url)
<img width="1110" alt="Bildschirmfoto 2021-11-24 um 10 46 12" src="https://user-images.githubusercontent.com/7473349/143214824-a41da582-5c4b-457e-8586-890b003cf1fb.png">
<img width="1026" alt="Bildschirmfoto 2021-11-24 um 10 45 25" src="https://user-images.githubusercontent.com/7473349/143214832-be7d673d-f15e-4316-976c-5c3f087d1586.png">

**Comment by zainulabidin302** [comment]
I think links should be changed (I can do it if I get a go ahead). 

Because from the morning I was of the impression the docs were down when it was migrated.

**Comment by zainulabidin302** [comment]
Alright @jfalkenstein , I will do a pull request later tonight.

ciao

**Comment by zaro0508** [comment]
related to #1098

**Comment by DG-SHeather** [comment]
The link in the GitHub 'About' box is still https://sceptre.cloudreach.com/. Shouldn't this be changed to https://docs.sceptre-project.org/ also?

**Comment by jfalkenstein** [comment]
@zaro0508 , I don't think I have permissions to make that fix ^^

**Comment by zaro0508** [comment]
> The link in the GitHub 'About' box is still https://sceptre.cloudreach.com/. Shouldn't this be changed to https://docs.sceptre-project.org/ also?

@DG-SHeather @jfalkenstein I have updated about to link to https://docs.sceptre-project.org
