### ISSUE TITLE
Feature request: stack-name command

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1167]
### Feature request

Please implement a feature `stack-name` that returns the stack's stack name in CloudFormation. This is given by `self.external_name` in the `Stack` object. Where ambiguity would exist in the case of nested stacks, also return a mapping of stack names => command paths.

**Comment by jfalkenstein** [comment]
I can see the utility, but I'm not sure what you mean by "nested stacks". I think a useful output of this would be like:

```json
{
    "my/command/path.yaml": "external-stack-name"
}
```
