### ISSUE TITLE
Sceptre requires a very old version of packaging and it is problematic

### ISSUE THREAD

**Issue by jfalkenstein** [Sceptre/sceptre#1203]
Right now Sceptre requires `"packaging>=16.8,<17.0"`. Furthermore, sceptre resolvers installed by default (like the cmd and file resolvers) also require packaging at that old version. These all seem to resolve to v16.8, which was released on **Oct 29, 2016!**

A number of times, recently, this has come into direct contradiction with other libraries I want install in the same virtual environment. 

From what I can gather, sceptre appears to use this tool for gathering installed entry points for things like resolvers, hooks, and template handlers. **What I don't know** is what historical context there is for us having such a very old version specified on this package.

@craighurley, @zaro0508 do either of you have any context into this?

I'd like to upgrade this package to something much more recent, but (v21) but I'm not sure if there are known hurdles/obstacles to consider in that process.

**Comment by craighurley** [comment]
Sorry, I don't have info to add here.

**Comment by zaro0508** [comment]
sorry, I do not.  @ngfgrant would you be able to provide any information regarding this issue?
