### ISSUE TITLE
Missing Error Trapping for a Launch

### ISSUE THREAD

**Issue by avatarworf** [Sceptre/sceptre#1214]
https://github.com/Sceptre/sceptre/blob/33e9c98661c5f08f594e61b0e3bd92d9421fffdb/sceptre/config/reader.py#L375-L377

When a Yaml file is located in the Config directory which doesn't have excepted StackConfig values, example

```yaml
---
test
```

Then the `_recursive_read` raises a cryptic difficult to attribute error

```
    config.get(config_key), child_config.get(config_key)
AttributeError: 'str' object has no attribute 'get'
```

Proposal would be to wrap this call in a try, so as to highlight that the file with the issue is obvious

```python
            try:
                value = strategy(
                    config.get(config_key), child_config.get(config_key)
                )
            except Exception as err:
                raise ValueError(
                    "Error parsing {}/{}:\n{}".format(directory_path, filename, err)
                )
```

So that an output of the following is present in order to determine what file has the configuration issue.

```
ValueError: Error parsing custom/test.yaml:
'str' object has no attribute 'get'
```

**Comment by jfalkenstein** [comment]
Hi @avatarworf , I'm a little confused by your usecase here. Are you describing a situation where someone has created a StackConfig that isn't a StackConfig and which doesn't actually have any keys on it but is still a yaml file?

**Comment by avatarworf** [comment]
In sceptre v1, this file was just ignored.  It look a while to unearth where in our migration to sceptre v3 that the source problem was a rogue file as described.  Yes it was just a badly formed yaml file in the repo tree
