### ISSUE TITLE
Add Python 3.10 support

### ISSUE THREAD

**Issue by Morl99** [Sceptre/sceptre#1225]
### Subject of the issue
We would like to update to Python 3.10. Unfortunately, Sceptre does not yet seem compatible. If we try to run it, we get the following error message:

```
pkg_resources.DistributionNotFound: The 'importlib-metadata; python_version < "3.8"' distribution was not found and is required by click, jsonschema
```

This seems to be a bug in pkg_resources and a version upgrade is probably needed.

### Your environment
* version of sceptre (sceptre --version): 3.1.0
* version of python (python --version): 3.10.4
* which OS/distro: alpine

### Steps to reproduce
Just run any sceptre command after installing sceptre with python 3.10

**Comment by zaro0508** [comment]
@Morl99 PR #1227 attempted to add python 3.10 support however [tests are failing]( https://app.circleci.com/pipelines/github/Sceptre/sceptre/1308/workflows/03e0cd5a-2dbb-4442-ac4b-81d20d62b758/jobs/8546).  Would you be able to help debug the failures?

**Comment by Morl99** [comment]
It seems like you have solved it, that is awesome. Is there a (pre)-release that I could test?

**Comment by jfalkenstein** [comment]
Hi @Morl99, it's currently in Master, I believe. You could clone the repo and install from there. I don't believe we push pre-release versions to PyPI, but if you cloned and installed from there, you could test it out in py3.10.

**Comment by Morl99** [comment]
Are there any plans on crafting a new release? We decided, that testing this from source code would be quite complicated and outside of our comfort zone (sorry about that), so we are waiting for a final release. We would really appreciate, if a sceptre release that support python 3.10 would be available.

**Comment by jfalkenstein** [comment]
So right now, there's really [one final change](https://github.com/Sceptre/sceptre/pull/1229) that we're looking to get released in this release, I think. Assuming it gets merged within the next week, we'd be looking at a release probably end of next week or beginning of the following one.

**Comment by Morl99** [comment]
> So right now, there's really [one final change](https://github.com/Sceptre/sceptre/pull/1229) that we're looking to get released in this release, I think. Assuming it gets merged within the next week, we'd be looking at a release probably end of next week or beginning of the following one. 

That's a good one, looking forward to it!
