### ISSUE TITLE
Update `networkx` to mitigate CWE-502

### ISSUE THREAD

**Issue by rflett** [Sceptre/sceptre#1236]
### Subject of the issue
Sceptre depends on the `networkx` version `2.5.1` which [has a CWE rated 8.8](https://snyk.io/vuln/pip:networkx). This can be resolved by updating to at least version `2.6`.

[The changelog for `2.6`](https://networkx.org/documentation/stable/release/release_2.6.html#deprecations) doesn't appear to have any obvious deprecations that would affect sceptre.

### Your environment
* version of sceptre (sceptre --version)
`3.1.0`
* version of python (python --version)
N/A
* which OS/distro
N/A

### Steps to reproduce
N/A

### Expected behaviour
N/A

### Actual behaviour
N/A

**Comment by zaro0508** [comment]
@rflett would you be able to propose a PR for this?

**Comment by jfalkenstein** [comment]
This was resolved with #1243
