### ISSUE TITLE
Getting region from config.yaml

### ISSUE THREAD

**Issue by 1337G4mer** [Sceptre/sceptre#1237]
### Subject of the issue
How to programmatically get `region: us-east-1` which is in my `config/test/config.yaml` file using Python?

### Expected behaviour
I want to be able to do 
```python
    context = SceptreContext(project_path=str(Path.cwd()), command_path="test")
    plan = SceptrePlan(context)

# followed by something that allows me to get region out of context or plan

```

Is there a way to achieve this? Reading the docs or scouring the internet didn't help.

**Comment by 1337G4mer** [comment]
I did it using this 

```
    for resource in plan.describe_resources():
        region = resource.region
    client = boto3.client('ec2', region_name=region)
```

not sure if this is the best way though.

**Comment by zaro0508** [comment]
@1337G4mer take a look at some of the resolvers or hooks code.  You can get it from the stack object,  Example: https://github.com/Sceptre/sceptre-ssm-resolver/blob/master/resolver/ssm.py#L100
