### ISSUE TITLE
Better error handling with invalid templates

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#1253]
### Subject of the issue
The template handler does not provide a helpful message when sceptre cannot resolve a template from an http source.   It would be nice to improve the error handling for that.

### Your environment
* version of sceptre: 3.1
* version of python: 3.9
* which OS/distro: MAC OSX

### Steps to reproduce

1. Create a sceptre config and reference a non-existing template using the http template handler

contents of `dev/my-template.yaml`:
```
template:
  type: http
  url: https://my-bucket.s3.amazonaws.com/templates/my-template.yaml
stack_name: my-stack
```
2. run `sceptre launch dev`
get the following message..
 
```
"An error occurred (ValidationError) when calling the UpdateStack operation: Template format error: unsupported structure."
```

3. run `sceptre launch dev/mytemplate.yaml` will output the following message..
```
---
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>templates/my-template.yaml</Key><RequestId>YSEQKP3YV3RZ9FEJ</RequestId><HostId>Tc/l2Ne92PC1WZ3zoa4HhydMjuk3PRh+puZ0CAaC8YvnthVPYpBJiLBFQpbIFfSG+7+3b7LA5N4=</HostId></Error>
```

### Expected behaviour
More helpful message would be nice.

**Comment by jfalkenstein** [comment]
@zaro0508 What happens if you run this with `--debug`? A lot of times that shows a much more helpful stacktrace and maybe other info too.
