### ISSUE TITLE
Sceptre shouldn't need to make redundant !stack_output calls

### ISSUE THREAD

**Issue by jfalkenstein** [Sceptre/sceptre#1263]
### Subject of the issue
Right now, if you have the same `!stack_output` resolver argument spread across many stacks, sceptre will get the stack outputs for that stack to resolve the value for every single one. The leads to a longer deployment process with MANY more CloudFormation API calls than it needs.

I think Sceptre should implement some sort of stack_output resolver lazy-loaded cache where identical arguments should always resolve to the same value without future api calls needed. This should be fairly trivial to implement, though I think the question of just how to maintain a global state between stacks would be a relevant implementation concern.

**Comment by jfalkenstein** [comment]
@zaro0508 , @alexharv074 , @craighurley I'd be interested in your thoughts on this one.

**Comment by jfalkenstein** [comment]
That's indeed an interesting approach! I hadn't thought of that, but it's about as elegant as it comes...

**Comment by dboitnot** [comment]
I think two things need to be true for this to work:

1. The method arguments need to be hash-able. Looks like they're all strings so that shouldn't be an issue.
2. The process does not run long enough for the cached entries to be invalidated.

In my use cases this would always be true. But I rarely if ever launch more than one stack at a time. Are there circumstances where the user might expect the value from a resolver to mutate because of the run and the new value be available to subsequent updates in the same run?

**Comment by jfalkenstein** [comment]
lru_cache isn't based upon _time_; It's based on the number of distinct hits. I think the default cache size is something like 128 slots or something like that. Some people have some epic deployments with potentially >100 stacks. So we might need to tinker with the cache size (there's a parameter for that).

There are two potential issues I see, thought:
* In our integration tests, that cache would live for the duration. It's possible that we might need that cache cleared between each test. There's a behave hook we can use for that, so it's not impossible.
* stack_output creates a dependency between stacks, so this will guarantee that if stack b uses stack a's outputs, stack a will always be deployed first (and thus its outputs change) BEFORE stack b's resolver gets resolved. So the changing output values won't be an issue there. HOWEVER, stack_output_external does NOT establish those dependencies. It's POSSIBLE that the values from stack_output_external might change if stack b and c uses the outputs of stack a, and stacks are deployed in the order of b --> a --> c. This seems highly unlikely, though. I'm not sure that's a case we want to cover. We could also probably have a global sceptre cli flag to disable output caching that would set the cache-size to 0. If we did that, I think we could cover that very weird edge case that might inevitably affect someone.

**Comment by dboitnot** [comment]
From the docs (https://docs.python.org/3/library/functools.html) it looks like the annotation will add methods to the wrapped method that would allow us to inspect and flush the cache:

> To help measure the effectiveness of the cache and tune the maxsize parameter, the wrapped function is instrumented with a cache_info() function that returns a [named tuple](https://docs.python.org/3/glossary.html#term-named-tuple) showing hits, misses, maxsize and currsize.
>
> The decorator also provides a cache_clear() function for clearing or invalidating the cache.

We can also make the cache size unbound by setting it to `None`. This seems reasonable for a CLI tool which isn't run continuously but it might be more "future proof" to select a high number like 4,096 (or 40,960).

**Comment by jfalkenstein** [comment]
Yeah, I think if we set the cache size to None in the integration tests as well as with an optional CLI flag, that would solve the problem. Also, 4096 should be fine. The worst case scenario of too few cache slots is that we make some extra requests... but we're ALREADY making an extremely inefficient number of requests now. So I think 4096 would honestly be in the domain of "better than nothing".
