### ISSUE TITLE
iam_role and role_arn are confusing names that are easily confused.

### ISSUE THREAD

**Issue by jfalkenstein** [Sceptre/sceptre#1283]
### Subject of the issue
Right now, Sceptre has two very confusingly named StackConfigs that are easy to mistake for each other, despite operating very differently:

* `role_arn` is the ARN of the CloudFormation Service Role attached to a stack (permanently) and is assumed by _CloudFormation_ to perform all stack actions.
* `iam_role` is the ARN of the role _Sceptre_ assumes and uses to perform all stack actions.

**I believe we should deprecate these names and issue deprecation warnings when these configurations are used. Instead, we should transition to using much clearer names. I propose:
* `cloudformation_service_role`
* `sceptre_deployment_role`

Ideally, we'd deprecate the old configs (probably along with template_path), issue a warning, and then assign those values to the new fields. We could remove the deprecated fields on the next major version.

**Comment by zaro0508** [comment]
I am in favor of this idea.
