### ISSUE TITLE
Intermittent AttributeError when resolving dependencies using the sceptre.plan.plan module.

### ISSUE THREAD

**Issue by pjsmith404** [Sceptre/sceptre#1291]
### Subject of the issue

Hello,

I've got an intermittent AttributeError when resolving dependencies using the sceptre.plan.plan module. It only occurs when using a particular hierarchy of dependencies. The error does not occur when using equivalent Sceptre CLI commands. I'm not sure if there's something I'm overlooking in my usage of the API. My config appears to be consistent with the CLI. I didn't spot anything similar when looking through existing issues regarding dependencies.

Cheers,

Pat

The dependency hierarchy:
- Stack 1 depends on Stack 2 and Stack 3.
- Stack 2 depends on Stack 3.

Workarounds:
- Removing either Stack 1s dependency on Stack 2, or Stack 2s dependency on Stack 3 stops the issue occurring.
- Adding `ignore_dependencies` to the SceptreContext will prevent the error. This seems to be practical for what I need to do.

The trace:
```
Traceback (most recent call last):
  File "/home/pjls/repos/sceptre-bug/sceptre-describe.py", line 10, in <module>
    change_sets = plan.describe()
  File "/home/pjls/.local/lib/python3.9/site-packages/sceptre/plan/plan.py", line 208, in describe
    self.resolve(command=self.describe.__name__)
  File "/home/pjls/.local/lib/python3.9/site-packages/sceptre/plan/plan.py", line 114, in resolve
    self.launch_order = self._generate_launch_order(reverse)
  File "/home/pjls/.local/lib/python3.9/site-packages/sceptre/plan/plan.py", line 62, in _generate_launch_order
    graph = self.graph.filtered(self.command_stacks, reverse)
  File "/home/pjls/.local/lib/python3.9/site-packages/sceptre/config/graph.py", line 47, in filtered
    relevant |= nx.algorithms.dag.ancestors(graph, stack)
  File "/home/pjls/.local/lib/python3.9/site-packages/sceptre/stack.py", line 251, in __eq__
    self.dependencies == stack.dependencies and
  File "/home/pjls/.local/lib/python3.9/site-packages/sceptre/stack.py", line 242, in __eq__
    self.name == stack.name and
AttributeError: 'str' object has no attribute 'name'
```

### Your environment
* version of sceptre (sceptre --version): 3.2.0
* version of python (python --version): 3.9.2
* which OS/distro: Debian Bullseye

### Steps to reproduce
Using the sample repository here: https://github.com/pjsmith404/sceptre-bug

1. Create the stacks using `sceptre launch .`
2. Create a change set using `sceptre create experimental test-change-set`
3. Describe the change set using `sceptre describe change-set experimental test-change-set
4. Describe the change set using `python sceptre-describe.py`. Sometimes it will work, most times it will throw the AttributeError

### Expected behaviour
I would expect dependency resolution via the CLI or the API to return the same result.

### Actual behaviour
Dependency resolution via the API causes intermittent AttributeErrors

**Comment by jfalkenstein** [comment]
Interesting! I've not encountered that situation before, but I am seeing how that potentially would happen. It seems the issue has to do with the way we execute `__eq__` and when we convert the dependencies from strings to stacks. 

Right now, we convert the `dependencies` list from strings (e.g. `"my_stack.yaml"`) to full-fledged Stack objects in the `resolve_stacks` method on `reader.py`:

![image](https://user-images.githubusercontent.com/77296393/213223149-92c47b03-b136-4ef9-9f7e-2d557f738b81.png)

I'll need to look into your sample project (thanks for putting that together, btw). Is there a chance you're using the "ignore-dependencies" option?

**Comment by pjsmith404** [comment]
Howdy!

Regarding `ignore-dependencies`, if I run either of the CLI commands below it has no issues:
- `sceptre describe change-set experimental test-change-set`
- `sceptre --ignore-dependencies describe change-set experimental test-change-set`

If I add `ignore_dependencies=True` to the SceptreContext in python, it stops the error happening; which is a suitable workaround for how I'm currently using it.

Cheers,

Pat

**Comment by jfalkenstein** [comment]
Very interesting. Ok, so I'll need to dive in to further investigate, I guess. Or if you want to do some debugging and propose/create a fix, I'd be very happy to work with you to get that fix made and implemented. I'm not sure when I'll be able to work on this. It might be a couple weeks.

**Comment by pjsmith404** [comment]
Thanks, I'll have a crack at seeing what I can see :)

**Comment by jfalkenstein** [comment]
Hey, great detective work! I think I vaguely remember running into something like that by trying to use relative paths before! (for the record, with `--dir`, you don't need the period. If your directory with your configs is in your `$PWD/sceptre/`, you can just use `--dir sceptre` and it'll work just fine, since it will always assume your current working directory is the parent for your `--dir`.

I'd rather not check for "." leading the path, since I _think_ that might conflict with Windows paths? Maybe? In any case, I'd be far more in favor of resolving the project path, your second option. If you want to put up a PR, I can work with you get that moved toward release. Btw, if you're not on our slack channel, you definitely should join!
