### ISSUE TITLE
We have a bunch of hooks, resolvers, and other junk in the Sceptre Org nobody knows about

### ISSUE THREAD

**Issue by jfalkenstein** [Sceptre/sceptre#1298]
I was going through the [Sceptre org](https://github.com/Sceptre) today and realized that there are a bunch of hooks and resolvers there. It was recently mentioned on our slack channel that our docs should point to them. But I also realized that there are apparently junk repos that haven't really been touched in years that aren't useful.

After v4 is released, we should systematically go through the repos in the org and clean house:
* If it's a valuable Hook/Resolver/Template Handler, we should mention it and link to it in our docs as optional add-ons
* If it's outdated/unsupported/broken, we should either fix it up (if it would have value), close the repo, or at least put a big fat "UNSUPPORTED" label on the repo. We could use [PyPI Stats](https://pypistats.org/) to see if anyone is actually using some of these packages.

- [X] **sceptre.github.io:** Host Sceptre documentation with Github pages
- [X] **sceptre-circleci:** Docker image for Sceptre CircleCI builds.	\
      Decision: We actively use this for managing our CircleCI builds. No action necessary.
- [x] **sceptre-cli:** Sceptre CLI for v3	\
      Decision: This isn't available on PyPI. I don't think it's used. **I don't think we have much reason to keep this around.**
- [X] **sceptre-file-resolver:** \
      Decision: This is directly referenced by Sceptre as a dependency to be installed. We don't really need any further action with this. _I tend to think we should move this into Sceptre proper rather than installing it as a dependency, though._
- [ ] **sceptre-stack-termination-protection-hook:** A Sceptre hook to enable and disable stack termination protection	\
      Decision: This is actively being used. [It was downloaded 189 times in the last week](https://pypistats.org/packages/sceptre-stack-termination-protection-hook). **We should add a link to this in our docs.**
- [x] **sceptre-provider-test-fixture:** A demo provider for use as a test fixture	\
      Decision: **We should delete this.** It is for an outdated version of Sceptre and doesn't exist on PyPI. 
- [x] **sceptre-test-resolver-fixture:** A resolver to be used in testing	\
      Decision: **We should delete this.** This doesn't really seem to serve a purpose.
- [x] **sceptre-hook-sfx-custom-event:** \
      Decision: **We should delete this.** This doesn't really have a purpose. The hook does nothing.
- [ ] **sceptre-date-resolver:** A Sceptre resolver to retrieve the current datetime	\
      Decision: This seems very handy. **We should link to it in our docs.**
- [ ] **sceptre-kms-resolver:** A Sceptre resolver to retrieve and decrypt values from AWS KMS	\
      Decision: **This seems super handy**, but it's outdated. We should fix up the code and reference it in our docs. [It was only downloaded 24 times in the last month](https://pypistats.org/packages/sceptre-kms-resolver).
- [ ] **sceptre-ssm-resolver:** A Sceptre resolver to retrieve values from the AWS SSM	\
      Decision: This actively used. [1254 downloads in the last week. ](https://pypistats.org/packages/sceptre-ssm-resolver). It is a little outdated (doesn't have support for overriding iam_role). We reference this in our docs without actually saying that it needs to be explicitly installed separately. **We should update this library and then update our docs to point to this repo.**
- [x] **sceptre-provider-aws:** AWS Provider for Sceptre	\
      Decision: **We should delete this.** This repo is basically empty and provides nothing of use.
- [ ] **sceptre-cmd-hook:** Sceptre Command Hook	\
      Decision: [This was downloaded 4 times in the last month.](https://pypistats.org/packages/sceptre-cmd-hook). This is an old version of the `!cmd` hook that has been moved into Sceptre. It hasn't been updated since 2019. **I think we should delete this repo.** It doesn't really make sense to keep this around, though it appears like _somebody_ is using it... very rarely. I'm not sure what we should do about this, but it doesn't really make sense to continue with this around. Deleting the repo shouldn't remove the current version on PyPI.
- [ ] **sceptre-aws-stackoutput-resolver:** AWS StackOutput Resolver	\
      Decision: [This has been downloaded 45 times in the last week. ](sceptre-aws-stackoutput-resolver). It's clearly being used. But this resolver has been moved into Sceptre long ago and there's no reason to maintain it. **We should put a big bold banner on the readme that says we no longer maintain it.**
- [ ] **sceptre-aws-asg-scaling-processes-hook:** AWS Auto Scaling Group Scaling Processes Hook	\
      Decision: [This has been downloaded 3 times in the last month](https://pypistats.org/packages/sceptre-aws-asg-scaling-processes-hook). This exists as a part of Sceptre proper, though. Similar to with the CMD hook, I tend to think that we should just delete this repo. I don't think there's much use in us keeping this around, though it seems like _somebody_ out there is using it. Deleting the repo shouldn't remove the current version on PyPI.
- [x] **sceptre-file-contents-resolver:** File contents resolver for Sceptre	\
      Decision: [This has downloaded 4 times this past month](https://pypistats.org/packages/sceptre-file-contents-resolver). This is technically a part of Sceptre, though even our own docs indicate that it's deprecated. **I think we should officially deprecate the one in Sceptre using the deprecated decorator and remove this repo.** Somebody's using it, but I don't think we need the repo around any longer.
- [ ] **sceptre-environment-variable-resolver:** Environment variable resolver for Sceptre	\
      Decision: [This has been downloaded 338 times over the last month](https://pypistats.org/packages/sceptre-environment-variable-resolver). This is actually a part of Sceptre, but it appears a lot of people are installing it. **We should put a big bold banner on the readme that says we no longer maintain it.**
- [ ] **sceptre-aws-stackoutput-external-resolver:** AWS StackOuput External Resolver	\
      Decision: [This has been downloaded 5 times in the last month](https://pypistats.org/packages/sceptre-aws-stackoutput-external-resolver). It's been a part of Sceptre for quite a while. **I don't see a good reason to keep this repo around any more.**
- [X] **sceptre-hook-template:** A base structure to use for custom hooks. How to use: https://github.com/sceptre/project/wiki/sceptre-hook-template	\
      Decision: This is a template repo for creating new hooks. It's still good to use. **No action needed.**
- [X] **sceptre-resolver-template:** A base structure to use for custom resolvers. How to use: https://github.com/sceptre/project/wiki/sceptre-resolver-template	\
      Decision: This is a template repo for creating new resolvers. It's still good to use. **No action needed.**
- [X] **sceptre-template-handler-template:** A base structure to use for custom template handlers	\
      Decision: This is a template repo for creating new template handlers. It's still good to use. **No action needed.**
- [X] **tweetrel-test:** A repo for testing tweetrel	\
      Decision: It appears @ericabrauer set this up when she was working on automatic Tweets about releases. **We should delete this repo.**
- [ ] **sceptrelint:** A pre-commit linters for Sceptre stack configs	\
      Decision: I had no idea these existed. @zaro0508 apparently updated them as recently as July 2022, though. I can't find evidence of the repo in pypi, but I think Precommit installs directly from git repos, so I don't think that's an issue. This doesn't seem well-documented, but it seems like it could be potentially useful. **I think we should update these, document them, and link to this repo in our docs.**
- [X] **sceptre-aws:** Deploy and manage AWS account for Sceptre tests	\
      Decision: We use this repo to manage our integration tests environment. **No action needed.**
- [ ] **github-ci-action:** \
      Decision: This is a github action for sceptre. It is published to the [Github marketplace](https://github.com/marketplace/actions/sceptre-github-ci-action)
- [x] **sceptre-core:** Core Sceptre functionality for v3	\
      Decision: [This has been downloaded 6 times in the last month](https://pypistats.org/packages/sceptre-core). This is an old version of Sceptre. It appears as if Sceptre was refactored a long time ago from this version. **I don't really see a reason to keep this repo around. I think we should delete it.**

**Comment by jfalkenstein** [comment]
@zaro0508 , thoughs on this?

**Comment by zaro0508** [comment]
sounds like a good idea to me @jfalkenstein

**Comment by dboitnot** [comment]
I've updated the description with the list of repos in the org minus the obvious keepers. Based on "last updated" times, I suspect most of the ones at the top are also active. Feel free to drop anything that obviously doesn't need discussion.

**Comment by jfalkenstein** [comment]
@zaro0508, @dboitnot I've updated the description with my "decision". But really, it's just my thoughts on what I think we should do with each repo. I'd be interested in if you guys concur.

**Comment by zaro0508** [comment]
@jfalkenstein i agree with all of your assessments.

my suggestions..
* I'm just wondering whether we should go thru more of a deprecation process?  So instead of delete right away we archive the repos for a period of time then delete?  
* I think we should go the other direction with inclusion of hooks & resolvers into sceptre core.  I think should make them all plugins and reference them from python requirements like we currently do with the [sceptre-file-resolver](https://github.com/Sceptre/sceptre/blob/master/requirements/prod.txt#L13).  I like the consistency of moving resolvers to stand alone distributions and including specific versions of them in the requirements. 
* sceptre-cmd-hook should we deprecate in favor of rcmd resolver?

Here are some addition information about some of the repos..
* sceptre-core & sceptre-provider-aws were setup by @ngfgrant as a big refactor to provide support for [deploying to multiple clouds](https://github.com/Sceptre/sceptre/issues/385).  
* sceptre-hook-template & sceptre-resolver-template are probably outdated and should be updated to reflect better practices for creating hooks and resolvers.
* sceptrelint is used and is documented in it's README.md file.  It's also listed as a [supported pre-commit hook on the precommit website](https://pre-commit.com/hooks.html)

**Comment by jfalkenstein** [comment]
> I'm just wondering whether we should go thru more of a deprecation process? So instead of delete right away we archive the repos for a period of time then delete?

Yeah, for the ones that currently are downloaded by _somebody_ out there, I'd be fine with that. A lot of those empty/stubbed repos that aren't installed anywhere I don't see why we shouldn't just delete those, though. 

> I think we should go the other direction with inclusion of hooks & resolvers into sceptre core. I think should make them all plugins and reference them from python requirements like we currently do with the [sceptre-file-resolver](https://github.com/Sceptre/sceptre/blob/master/requirements/prod.txt#L13). I like the consistency of moving resolvers to stand alone distributions and including specific versions of them in the requirements over brining in the code base into sceptre core.

I think we need to make the distinction between "core" hooks and resolvers and those that are "extra".
Resolvers like `stack_output`, `stack_output_external`, and the others we have are pretty core to how Sceptre operates. I really don't want to see them split out from our codebase. I think a "batteries included" approach makes sense to give Sceptre users a satisfying experience. I don't like how Sceptre has these dependencies outside our codebase.

I _do_ think that some extra functionality does belong outside the core, though --> resolvers and template handlers like ssm, kms, SAM, CDK, etc...  These make sense outside of Sceptre.

 I also ran into an unfortunate chicken-and-egg situation recently with the rcmd resolver, where we couldn't upgrade Sceptre without upgrading the resolver, but we couldn't upgrade the resolver without upgrading Sceptre. It was a pain that required multiple deployments to get around. 

My recommendation would be:
* "Core" hooks, handlers, and resolvers that are described in our docs ought to be moved into our codebase. This makes maintaining them more coherent with changes elsewhere and we don't run into weird circular dependency issues. I'd consider all the hooks, handlers, and resolvers that we currently install with Sceptre to be in this category, except maybe the ASG hook (I don't know how many people actually use that...).
* Other supported and popular (or even _recommended_), "extra" hooks, handlers, and resolvers beyond our core functionality should be documented as extras that can be installed on our setup.py so that they can be installed like `pip install sceptre[ssm]`. I'd like to see the ssm resolver in here, Maybe "date" and "kms" too. 
* For more specific, less common use cases (like SAM and CDK), we ought to link to those in our docs as needing independent installation. 

> sceptre-cmd-hook should we deprecate in favor of rcmd resolver?
Those are two different things. `rcmd` is a _resolver_; `cmd` is a hook. 

Also... we should probably link to the pre-commit hooks in our docs, then. That seems useful and I had no idea they existed!

**Comment by dboitnot** [comment]
I agree with all of the above and as far as the dependency vs. core question I think I lean more toward inclusion than separate repos.

Would it be useful to formally define how we categorize extensions? Like, is a "core" extension one that's really popular or are there other criteria? I'd certainly agree that if we have a reason to mention an extension in our docs then it's worth including in the core. I'm also not sure what the utility of a separate repo is if it's a dependency unless there are other packages which also depend on it but shouldn't import the whole of Sceptre.

**Comment by zaro0508** [comment]
> "Core" hooks, handlers, and resolvers that are described in our docs ought to be moved into our codebase. This makes maintaining them more coherent with changes elsewhere and we don't run into weird circular dependency issues

I still disagree. I think moving plugin code into the core bloats it and makes the core more difficult to maintain.  It also requires us to decide which pieces of code should live inside vs outside.   I would just prefer to avoid that all together.  We just need to decide which plugins to install with sceptre core by including the plugin as a dependency in [setup.py](https://github.com/Sceptre/sceptre/blob/master/setup.py#L24)

**Comment by dboitnot** [comment]
> I still disagree. I think moving plugin code into the core bloats the code base and makes it more difficult to debug and maintain. It couples the plugin code to the core code which will restrict us from updating plugins independently of core.

I think this is a fair point. As a practical matter, do we find this problem is actually hampering plugin development? 

Philosophically I don't have any objections to including something labeled a "plugin" in the core repository as something "delivered." I think separate repositories can complicate development and deployment so I'd be looking to what problems separation can solve. If we're finding ourselves needing to release core plugin updates out of phase with the core release then separate repo's would be a solution.

I guess, as the "new guy" I'd ask, "Which problem(s) are we actually having and would they be helped by consolidation or separation?"

**Comment by dboitnot** [comment]
I agree we need to avoid circular dependency. So I'd argue that if Sceptre depends on it then it should be part of the "core" unless we redefine "core" to mean "the minimal set of libs required by all Sceptre things" then separate out all the user-facing package. So the dependencies would look like:

```mermaid
graph LR;
delivered[Delivered Plugin]
tp[Third-Party Plugin]
sceptre --> sceptre_core
sceptre --> delivered
delivered --> sceptre_core
tp --> sceptre_core
```

This seems like it'd be a pretty big effort so we'd want to be sure it solves a real problem.

**Comment by jfalkenstein** [comment]
I don't understand your distinction between "sceptre" and "sceptre_core".

**Comment by dboitnot** [comment]
The idea above (and I'm not advocating for it) is that we strip out the bare minimum core functions that plugins need to import. That becomes a separate library along with the "core" plugins. Then the Sceptre repository itself contains the user-facing parts of Sceptre.

I think this would address @zaro0508's concerns about modularity while avoiding circular dependencies. My feeling is that both solutions would work but if we're going to embark on breaking up into separate repos we should be addressing a problem which justifies the effort.

**Comment by zaro0508** [comment]
The following repos have been archived: sceptre-cli, sceptre-provider-test-fixture, sceptre-test-resolver-fixture, sceptre-hook-sfx-custom-event, sceptre-provider-aws, sceptre-aws, sceptre-core

**Comment by jfalkenstein** [comment]
@zaro0508 I think we need `sceptre-aws`.

**Comment by zaro0508** [comment]
> @zaro0508 I think we need `sceptre-aws`.

oops i didn't archive that one, the list has been updated

**Comment by zaro0508** [comment]
Archived `sceptre.github.io` because doc build and hosting have been moved to readthedocs.org

Archived `sceptre-circleci` The CI has been moved to github actions and the build has been refactored to use a base OS image from github.

Archived `tweetrel-test` because release tweet functionatlity to twitter/X has been removed

**Comment by zaro0508** [comment]
old repos have all been archives.  anything that's not archived is still needed.  i think we can just close this now.
