### ISSUE TITLE
List change-sets doesn't return full config file (missing suffix)

### ISSUE THREAD

**Issue by sopeters** [Sceptre/sceptre#1315]
### Subject of the issue
Noticed that `sceptre list change-sets <toplevel>` only returns the config file without the suffix - sceptre delete requires the full filename including suffix - we need to use this output to use it on `sceptre delete <config file> <changeset-name>, which requires the full file (including suffix).

The only way to get the full config file I found is using `sceptre list stacks` on the top level and use some grep to match StackName to full config file - or do a file system matching. Is there a way to include the suffix / full config filename (as an option for example) into the `sceptre list change-sets` output?

### Your environment
* Sceptre, version 3.2.0

### Steps to reproduce
* `sceptre list change-sets <toplevel>`

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by alex-harvey-z3q** [comment]
I think it's safe to say that this is confusing, and also unlikely that we can fix it.
