### ISSUE TITLE
Feature to save generate cloudformation templates files

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#1318]
### Subject of the issue
When debugging we typically use the `generate` command to output the generated cloudformation template files to standard out.    This is fine when generating one or a few templates however it's not as useful when generating a group of templates which can consist of a bunch of templates.  It would be nice to have an option to store all of the generated templates into a folder locally so that further inspection can be applied to each template.  The AWS CDK does this and outputs all templates to a `cdk.out` folder.  Each generated cloudformation template filename would be the name of the stack.

### Expected behaviour
```
sceptre generate --output template-output
```
generated cloudformations template files save in a `template-output` folder.  each filename is the stack name:

template-output
  |
  -- my-vpc.yaml
  -- my-ec2.yaml

**Comment by jfalkenstein** [comment]
That seems like a cool option.

**Comment by dboitnot** [comment]
I have an immediate use for this.
