### ISSUE TITLE
Why does black use Python 3.10?

### ISSUE THREAD

**Issue by iainelder** [Sceptre/sceptre#1370]
https://github.com/Sceptre/sceptre/blob/95d4a92b6e9fbb5a8f77a79e017016c0595f4bcb/.pre-commit-config.yaml#L38-L46

Tox runs tests on Python 3.11.

https://github.com/Sceptre/sceptre/blob/95d4a92b6e9fbb5a8f77a79e017016c0595f4bcb/tox.ini#L3

Should black's `language_version` be updated to match?

**Comment by zaro0508** [comment]
we probably updated tox and forgot to update the python language in pre-commit.  Maybe you could give provide a PR with that update @iainelder?

**Comment by iainelder** [comment]
Done! You can check it here. https://github.com/Sceptre/sceptre/pull/1371
