### ISSUE TITLE
announcements to twitter (X) is broken

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#1377]
### Subject of the issue
The release announcements done by the circleci [tweet-release](https://github.com/Sceptre/sceptre/blob/master/.circleci/config.yml#L191) job to X (or twitter) is broken again. 

https://app.circleci.com/pipelines/github/Sceptre/sceptre/1972/workflows/158d1c77-858c-414b-a2b8-2307d8e5a9b7/jobs/10855

```
{
  "errors": [
    {
      "message": "You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product",
      "code": 453
    }
  ]
}
```

Automated announcements to twitter have been a PITA to maintain.  We should either fix or remove this and the associated docs.

**Comment by jfalkenstein** [comment]
I sort of figured this would happen at some point with all the shenanigans related to Twitter/X in the last year. While it was cool that we did it (and one of @ericabrauer 's most notable contributions I'm aware of), I think we should tearfully, regretfully kill this off. It wasn't ever really that critical and if it's a burden, I think we should just cut it out.

**Comment by ericabrauer** [comment]
Agreed! I wondered how long it would be before this broke with all the changes in Twitter. I'm glad I at least got to help out! Thank you both for the opportunity  to work on this. 

If I ever get finished with my current side project, maybe I can try to replicate with FB Threads (more for fun and the principle of it rather than for practicality, idk how many ppl use that lol)

**Comment by ericabrauer** [comment]
@zaro0508 - do you need me to create the PR to remove it?

**Comment by zaro0508** [comment]
> @zaro0508 - do you need me to create the PR to remove it?

it's not an immediate need @ericabrauer.  The CI is just ignoring the failure we are not blocked from generating releases.  We would appreciate a PR if you have time though.
