### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by iainelder** [Sceptre/sceptre#1381]
Remove support for Python 3.7 from all the repos that contribute to build the main Sceptre application.

Python 3.7 reached the [end of its support lifecycle on 2023-06-27](https://devguide.python.org/versions/).

[On 2023-11-23 Homebrew requested support for Python 3.12](https://github.com/Homebrew/homebrew-core/pull/155493). Some of the PRs to add support for Python 3.12 at the same time drop support for Python 3.7.

* [x] [Main Sceptre repo](https://github.com/Sceptre/sceptre)
  * https://github.com/Sceptre/sceptre/pull/1382
  * https://github.com/Sceptre/sceptre/pull/1390
  * https://github.com/Sceptre/sceptre/pull/1395
* [x] [Docker image for CircleCI builds](https://github.com/Sceptre/sceptre-circleci)
  * https://github.com/Sceptre/sceptre-circleci/pull/19
  * 1395 above may make the sceptre-circleci repo obsolete
* [ ] [`!rcmd` shell command resolver](https://github.com/Sceptre/sceptre-resolver-cmd)
  * https://github.com/Sceptre/sceptre-resolver-cmd/pull/13
* [ ] [`!file` file content resolver](https://github.com/Sceptre/sceptre-file-resolver)
  * https://github.com/Sceptre/sceptre-file-resolver/pull/12

I track my own progress in [my dev notes for this task](https://github.com/iainelder/sceptre-dev-notes/blob/main/dev-notes/drop-support-for-python-3.7.md).

---

First planned on the [Slack channel](https://og-aws.slack.com/archives/C01JNN8RGBB/p1694624952882979).

**Comment by iainelder** [comment]
@zaro0508 I found a badge in the README that advertises the compatible Python feature versions.

```markdown
[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/sceptre?logo=pypi)](https://pypi.org/project/sceptre/)
```

Today it still shows 3.7.

![image](https://github.com/Sceptre/sceptre/assets/5024311/88e71d6c-fda9-4607-af06-9d2083cae0ae)

To update this badge, do we have to do anything apart from publish a new package to PyPI?

**Comment by zaro0508** [comment]
i don't think we need to worry about that @iainelder.  it's auto generated by shields.io  and it's called [dynamic badge](https://shields.io/badges/dynamic-json-badge)

**Comment by iainelder** [comment]
Today we merged https://github.com/Sceptre/sceptre/pull/1395.

Next I want to complete https://github.com/Sceptre/sceptre-file-resolver/pull/12.

**Comment by zaro0508** [comment]
This is done, python 3.7 has been dropped in sceptre repo and all resolvers hosted in the Sceptre org.  All repos have been moved to Github actions so we no longer need the circleci docker image
