### ISSUE TITLE
Setup build workflow without secrets

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#1401]
### Subject of the issue
Our current circleci workflow uses user credentials (secrets) when running integration tests (on AWS), deploying to pypi and dockerhub.   Modern CI system allow access to third party systems with OIDC which would allow setting up CI deployments without having to also setup secrets.  This is a more secure and flexible way to run integration tests and make deployments.  

Using secrets prevents us from allow others to trigger workflows that require secrets without also giving the user full access to those secrets therefore compromising security.  Currenly only Sceptre admins can trigger integration test runs.  Setting up OIDC might allow us to let non-admins trigger integration tests on our CI system without compromising security.

**Comment by iainelder** [comment]
See the CircleCI blog article [Using OpenID Connect identity tokens to authenticate jobs with cloud providers](https://circleci.com/blog/openid-connect-identity-tokens/) for example config using the [AWS CLI orb](https://circleci.com/developer/orbs/orb/circleci/aws-cli).

**Comment by zaro0508** [comment]
@iainelder I already know how to setup OIDC access to AWS with GH actions so instead of learning how to do it in circleci i've decided to switch to using GH actions.  We've also had multiple requests to move to GH actions in the past anyways so i think this is the right opportunity to dive in.
