### ISSUE TITLE
Provide a formatted_yaml template handler

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#1417]
### Subject of the issue
When generating templates from Jinja2, it is difficult and time-consuming to use Jinja2 line trimming to produce a neatly-formatted output template. This often leads to messy code seen in commands like `sceptre generate`.

It is proposed to add a template handler `formatted_yaml` that subclasses the `File` template handler and reformats white spacing and line breaks in a standard way.

**Comment by zaro0508** [comment]
this is done with the [sceptre-formatted-yaml-handler](https://github.com/Sceptre/sceptre-formatted-yaml-handler). thanks @alexharv074
