### ISSUE TITLE
sceptre validate does not validate whether all required stack parameters are present in the config

### ISSUE THREAD

**Issue by mvanholsteijn** [Sceptre/sceptre#1492]
### Subject of the issue

When you run `sceptre validate` it does not validate whether all required stack parameters are present in the config. It only validates the template. After a validate, a launch will cause an error if a required parameter is missing.

### Your environment
* 4.4.2
* 3.9.11
* MacOS/Linux

### Steps to reproduce
Tell us how to reproduce this issue. Please provide sceptre projct files if possible,
https://plnkr.co/edit/DHIEqhNDzMrIOAzq

- create a template with a parameter
- create a stack config, which does not provide a parameter value for it
- run sceptre validate

### Expected behaviour
- An error is raised that the config is missing a parameter

### Actual behaviour
- sceptre validates the template and says Oke...

**Comment by alexharv074** [comment]
Thanks for raising this issue. My initial feeling is that `sceptre validate` is a wrapper around Boto3's [`validate_template`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/validate_template.html) which in turn implements the [`ValidateTemplate`](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ValidateTemplate.html) API. I would, therefore, not expect Sceptre's `validate` command to do more than CloudFormation's `validate` command. This to me seems to be working as designed.

Have you considered implementing your own layer of automated testing around your templates and values file? That's what I would do.

**Comment by mvanholsteijn** [comment]
Of course I could write an additional script, but I request sceptre to validate stack configs, not only the CFN templates. It would be so much nicer to have a small check added to the validate call in sceptre: it would benefit all users of sceptre .

**Comment by zaro0508** [comment]
I agree with @alexharv074, the purpose of the `validate` command is specifically to validate CFN templates, not Sceptre configs.  The `generate` command might be a better candidate to do some validation however I'm not sure it fits there either.  You might want to consider validating sceptre configs with a linter, that's the main purpose of   https://github.com/Sceptre/sceptrelint
