### ISSUE TITLE
Update Sceptre on Conda Forge

### ISSUE THREAD

**Issue by ilyanoskov** [Sceptre/sceptre#1501]
Dear Maintainers,

Thank you very much for this great project.

Could you please publish the latest version for Conda too?

https://github.com/conda-forge/sceptre-feedstock

**Comment by alex-harvey-z3q** [comment]
@zaro0508 Do you know how to do this?

**Comment by zaro0508** [comment]
sorry, I don't use conda and have never published anything to conda-forge before.

**Comment by alex-harvey-z3q** [comment]
@ilyanoskov do you mind taking ownership of telling us what we have to do here since none of the maintainers actually know what Conda is or what we have to do here?

**Comment by alex-harvey-z3q** [comment]
@ilyanoskov As far as I can tell, the conda-forge project is no longer maintained (last commit by a human was 3 years ago). In any event, you need to chase the maintainers of that project, not this one. I'm going to close this but feel free to discuss if you disagree.
