### ISSUE TITLE
Add a nix flake, direnv, and justfile for development support

### ISSUE THREAD

**Issue by dboitnot** [Sceptre/sceptre#1521]
### Add a nix flake, direnv, and justfile for development support
Add a few optional features for developers:
- A nix flake to install developer tools such as poetry
- A justfile to collect dev's incantations
- A recipe in the justfile to enable direnv

**Comment by alex-harvey-z3q** [comment]
My view is that if @dboitnot needs this to be more impactful as a contributor and maintainer, I would have no personal objections however Dan hasn't responded to messages about it so for now, I am going to close this as @zaro0508 mentioned he is not in favour.
