### ISSUE TITLE
Error during aws sftp user creation via Jinja template using sceptre launch

### ISSUE THREAD

**Issue by vmuthu05** [Sceptre/sceptre#1528]
### Subject of the issue
Error during aws sftp user creation via Jinja template using sceptre launch
I am trying to pass in attributes such as sftp server id, public key and target path to Jinja resolving secret, however it is not resolving appropriately.. and throw error saying not correct format for these attributes

**Comment by alex-harvey-z3q** [comment]
Hi @vmuthu05  this seems like a request for support rather than a bug or issue in Sceptre. Consider joining the Sceptre slack channel? https://docs.sceptre-project.org/latest/#communication
