### ISSUE TITLE
Add Support for Stack Termination Protection

### ISSUE THREAD

**Issue by cboss24** [Sceptre/sceptre#228]
AWS recently released the ability to [protect stacks against termination](https://aws.amazon.com/about-aws/whats-new/2017/09/aws-cloudformation-provides-stack-termination-protection/). Currently this functionality is provided by the `protect` stack config, however this check is only being done client side by sceptre, leaving the stack open to manual deletion.

Should stack protection also be added to the `lock-stack` command? Currently that command is only protecting against updates.

**Comment by alexec** [comment]
I had this same use-case, and used this:
```
hooks:
  after_create:
    # enable termination protection so that we don't change the name-servers and therefore have to wait 2 days for DNS update
    - !cmd aws cloudformation update-termination-protection --enable-termination-protection --stack-name microservice-preprod-hosted-zone
```

**Comment by theseanything** [comment]
Yup so feel like this could be implemented apart of lock/unlock stack. Reluctant putting this into stack config - as pushes config to being more "stateful". e.g. what would the behaviour be for when you remove "protection" from config and its enabled on the stack...

**Comment by pmeghana1** [comment]
aws cloudformation update-termination-protection --enable-termination-protection --stack-name . Can we implement this feature using sceptre for entire stack on cloudformation.

**Comment by m1keil** [comment]
We don't use the lock feature, but having a terminate protecting config option is definitely useful.
The special case with removal of the terminate protection config can be handled by:
1. Nothing. Having a good error message during termination attempt can help.
2. Always trying to add/remove protection on every run of sceptre.

I would use the hook method but the only issue I have with it atm is that hooks don't have access to the stack name, so the name of the stack needs to be hardcoded in the hook.

**Comment by sustacek** [comment]
If it helps anyone, I've implemented a simple hook for this. The nice thing it does it for the current stack automatically - no need to reference the underlying CloudFormation stack, it will be computed by the hook itself:

```
# config/dev/db.yaml
hooks:
  after_create:
    - !set_stack_termination_protection 'enabled'
   
  before_delete:
    - !set_stack_termination_protection 'disabled'
```

```
# hooks/stacks.py
from sceptre.hooks import Hook
from sceptre.environment import Environment

class SetStackTerminationProtection(Hook):

    def __init__(self, *args, **kwargs):
        super(SetStackTerminationProtection, self).__init__(*args, **kwargs)

    def run(self):
        argument = self.argument
        
        environment = Environment(self.environment_config.sceptre_dir, self.environment_config.environment_path)
        stack = environment.stacks[self.stack_config.name]
        cf_stack_name = stack.external_name

        enable = (argument.lower() == 'enabled')
        enableLabel = 'enabled' if enable else 'disabled'

        self.logger.info(
            "Setting termination protection of stack '%s' to '%s'   (argument was '%s')",
            cf_stack_name, enableLabel, argument)

        self.connection_manager.call('cloudformation', 'update_termination_protection',
                                     kwargs={
                                         'StackName': cf_stack_name,
                                         'EnableTerminationProtection': enable
                                     })
```

**Comment by m1keil** [comment]
cheers, haven't realized the stack name is exposed under `self.stack_config.name` !

**Comment by sustacek** [comment]
Yeah, I'm just very freshly beginning with Spectre (love it so far) and I found that code snippet somewhere around forums / issues discussions.

**Comment by craighurley** [comment]
@jordie23 what version of sceptre did that work for you?  Keen to know in order to resolve a same use case as described here: https://github.com/cloudreach/sceptre/issues/410

**Comment by jordie23** [comment]
Sceptre 1.3.4

But I've just realised we define our stack name  "stack_name" in our config that's why it's working for us

https://sceptre.cloudreach.com/latest/docs/stack_config.html#stack_name

**Comment by ngfgrant** [comment]
@jordie23 - would you be willing to open a PR with your code as an addition to `contrib/`?

**Comment by zaro0508** [comment]
PR  https://github.com/cloudreach/sceptre/pull/498 is for sceptre V1, A port of that hook to sceptre V2 is here:  https://github.com/zaro0508/sceptre-stack-termination-protection-hook

**Comment by zaro0508** [comment]
@ngfgrant is there anything else to do in this issue?  Hooks provide ability to set termination protection on an entire stack and sceptre has the `set-policy` command to support protecting stack resources, https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html

**Comment by zaro0508** [comment]
the termination protection hook has been moved into the sceptre org: 
https://github.com/Sceptre/sceptre-stack-termination-protection-hook
