### ISSUE TITLE
Add support for Drift Detection

### ISSUE THREAD

**Issue by johnculkin** [Sceptre/sceptre#275]
This is a lower priority and more for planning purposes.

Some details here:
https://stelligent.com/2017/11/28/new-for-cloudformation-in-2018-drift-detection/

**Comment by ngfgrant** [comment]
Good suggestion. On hold until the feature is released by AWS.

**Comment by ryanpagel** [comment]
Can't wait for this feature in AWS CloudFormation and Sceptre.

**Comment by pc-mreeves** [comment]
Link is broken. Only reference I can find is here: https://aws.amazon.com/blogs/mt/aws-cloudformation-2017-in-review/

**Comment by jakul** [comment]
Now released! https://aws.amazon.com/blogs/aws/new-cloudformation-drift-detection/

**Comment by zaro0508** [comment]
duplicate of issue #1169 which contains a PR for drift detection feature.
