### ISSUE TITLE
How to reference the current StackName in the Config file

### ISSUE THREAD

**Issue by chrisduong** [Sceptre/sceptre#346]
Hi,

I modular my Nested Cloudformation stack with Sceptre, so in my Config file, I need to get the current StackName for my Parameter. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackname for all names.

Normally, within CFN, I can use `Ref: AWS::StackName`.

**Comment by et304383** [comment]
I too would love this ability.  It's a bit of a pain having to construct the stack name in an environment or stack config when this value could be exposed to the templating abilities of the config files.

**Comment by zaro0508** [comment]
duplicate of https://github.com/Sceptre/sceptre/discussions/1021
