### ISSUE TITLE
stack_output resolver fails when stack_name of that stack is set

### ISSUE THREAD

**Issue by lukeplausin** [Sceptre/sceptre#380]
I am having an issue where the `stack_output` resolver fails when resolving an output which belongs to another stack, which has the `stack_name` parameter set.

For example

```
stack_1_config.yaml
---
template_path: templates/template_1.yaml
stack_name: stack_1
parameters:
  ApplicationName: sceptre
  EnvironmentName: dev
```

```
stack_2_config.yaml
---
template_path: templates/template_2.yaml
stack_name: stack_2
parameters:
  ApplicationName: sceptre-monitoring
  ECSClusterName: !stack_output stack_1::ECSClusterName
```

I would expect the `stack_output` resolver to check whether the `stack_name` of my other stack was set in the yaml config, however it fails with an error like this:

```
[2018-05-29 07:42:24] - sceptre.environment - Stack dev/stack_2_config failed to launch
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sceptre/environment.py", line 252, in _manage_stack_build
    status = getattr(stack, command)()
  File "/usr/lib/python2.7/site-packages/sceptre/stack.py", line 281, in launch
    status = self.create()
  File "/usr/lib/python2.7/site-packages/sceptre/hooks/__init__.py", line 70, in decorated
    response = func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sceptre/stack.py", line 195, in create
    "Parameters": self._format_parameters(self.parameters),
  File "/usr/lib/python2.7/site-packages/sceptre/resolvers/__init__.py", line 72, in __get__
    return self.resolve_values(getattr(instance, self.name))
  File "/usr/lib/python2.7/site-packages/sceptre/resolvers/__init__.py", line 91, in resolve_values
    attr[key] = value.resolve()
  File "/usr/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 120, in resolve
    return self._get_output_value(stack_name, self.output_key)
  File "/usr/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 35, in _get_output_value
    outputs = self._get_stack_outputs(stack_name)
  File "/usr/lib/python2.7/site-packages/sceptre/resolvers/stack_output.py", line 68, in _get_stack_outputs
    raise StackDoesNotExistError(e.response["Error"]["Message"])
StackDoesNotExistError: Stack with id dev-stack-1-config does not exist
```

(stack names were changed)

**Comment by lukeplausin** [comment]
@nmyster I know about the `stack_output_external` resolver, but this means I need to hard code the stack name in the resolver and for each environment. I think the `stack_output` resolver should still be capable of resolving the `stack_name` parameter if it set.

**Comment by nmyster** [comment]
At the moment, `stack_output` doesn't support custom stack names. Take a look at using variables and variable files to help with the hardcoding issue you mention.

The problem with using `stack_output` with a custom name is that the way that a stack is named is based on the file path of that stack config. If you set a custom name, there is no current way to determine what stack that actually refers too. Feel free to submit a PR if this is something you think that can be achieved differently :)

**Comment by ngfgrant** [comment]
@lukeplausin - did you get a resolution to this at all?

**Comment by ngfgrant** [comment]
@lukeplausin it would be interesting to test if this issue still exists in v2. We’ve changed the way stacks are loaded so it might be that this issue has inadvertently been fixed. Do you have a test project we could use to see?

**Comment by xen0l** [comment]
I tested it and it still isn't working. Can we consider this to be a bug?

**Comment by ngfgrant** [comment]
I am assuming this was a 1.x sceptre project? If this is the case then I think the behaviour above is intended for v1. If it is not working then I will investigate more thoroughly. @xen0l can you confirm which version of sceptre you used to test and if possible share the project?

**Comment by dahu33** [comment]
In my sceptre v2 project, I haven't been able to use `stack_output` and `stack_output_external` with custom stack_names. I have tried:

`!stack_output path/to/my/file.yaml::output_name`
> An error occurred (ValidationError) when calling the DescribeStacks operation: 1 validation error detected: Value 'path/to-my-file' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*

`!stack_output_external path/to/my/file.yaml::output_name`
> An error occurred (ValidationError) when calling the DescribeStacks operation: 1 validation error detected: Value 'path/to/my/file.yaml' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*

`!stack_output_external stack_name_as_shown_in_cloudformation::output_name`
> Stack with id stack_name_as_shown_in_cloudformation does not exist

Have I missed something?

**Comment by ngfgrant** [comment]
What is your custom stack name @dahu33?

**Comment by dahu33** [comment]
@ngfgrant please find below an example with `!stack_output_external`:

config/prod/ap-southeast-1/stack1.yaml
```yaml
template_path: stack1-template.yaml
stack_name: stack-name1
```

config/prod/global/stack2.yaml
```yaml
template_path: stack2-template.yaml
stack_name: stack-name2
parameters:
  Param1: !stack_output_external stack-name1::Output1
```
Will error with: 
> Stack with id stack-name1 does not exist

**Comment by ngfgrant** [comment]
@dahu33 you will need to use the full path (`config` as root) in the `stack_output_external` path. E.g

```yaml
template_path: stack2-template.yaml
stack_name: stack-name2
parameters:
  Param1: !stack_output_external  prod-ap-southeast-1-stack1.yaml::Output1
```

see https://sceptre.cloudreach.com/2.1.5/docs/resolvers.html#stack-output-external

**Comment by sebastiankasprzak** [comment]
looks like same issue in sceptre 2 project @ngfgrant - is there a plan to correct/change this behaviour?

**Comment by ngfgrant** [comment]
Ok so the behaviour described is intended and was the same in v1 if using stack_name then you’ll need to use stack_output_external as well as dependencies key as per the docs: https://sceptre.cloudreach.com/latest/docs/stack_config.html#stack_name

Based on this I’m going to class this as a feature request. There might well have been a good reason why things were made this way but will need to investigate.

**Comment by zaro0508** [comment]
v1 no longer supported.  this works in v2
