### ISSUE TITLE
Sceptre Multi-Cloud Support

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#385]
# Proposal: Multi-Cloud Support

For a while now there has been a desire to add support for other clouds in
Sceptre (#68). The purpose of this proposal is to start a fresh discussion
about how we can best architect Sceptre to support multiple clouds, namely
Azure and GCP.

I'd like to see a final architecture that plays to Sceptre's strengths whilst
avoiding becoming another Terraform. We shouldn't shy away from helping to
solve vendor specific nuances with their templates, as we have with AWS's
CloudFormation.

## Suggested Benefits / Features

- Cloud Native Templates e.g. raw CloudFormation, ARM, GCP.

- Connection Handling & Helpers

- Shared/Central Configuration

- Cross-Cloud Parameter Passing

- Hooks / Resolvers

- A Unified CLI (if concepts between clouds allow)

We will need to balance features with the cost of maintaining and keep the
codebase up to date. Hopefully, the conversation here will be able to give
a good indicator of the core feature set we should include to further improve
the usefulness of Sceptre.

## Architecting for Multi-Cloud

My initial thoughts about the structure are to break out cloud-specific
wrappers into their own repositories, keeping the shared functionality of the
tool within "Sceptre Core". Having cloud-specific repositories such as:

- "sceptre-aws"

- "sceptre-azure"

- "sceptre-gcp"

- "sceptre-[insert-cloud-provider-here]"

Will allow those repositories to be kept up to date as new features for each
cloud are released, without having to do a full 'core' release. The sole
purpose of these components is to implement an appropriate SDK, such as boto3,
as closely as possible, making the functionality available to `sceptre-core`
and `sceptre-cli`. When included in a project these repositories provide the
functions available to 'core'.

Sceptre "core" would be responsible for:

- Managing Connections / Authentication

- Project Configuration

- Hooks / Resolvers

- Parameter Handling

It is also likely that the CLI should be split from the "core" repository. With
multi-cloud support, we need to assume that each project will use different
combinations of cloud providers. This will make it difficult for the CLI to
know ahead of time which commands are valid. It might be prudent to keep the
CLI as "dumb" as possible. We could consider a design whereby the CLI
`registers` with an instance of `sceptre-core`. Since `core` is likely to be
the place to hold the project configuration we can refactor the CLI to make
available commands that make sense given a specific configuration.

## Timescales 

We are working to get Version 2 completed and released. Assuming there are not 
major hiccups, this is something we hope to make live in a few weeks. 

Depending on the initial scope, I would hope to have substantial progress made 
into multi-cloud support by the end of 2018. There will probably be breaking 
changes in making multi-cloud a reality, so it will also incur a version bump

## Moving Forward

The above proposal is just to get things started. I would welcome any other
suggestions, questions, ideas about must-have features etc. If you have a vision 
of how multi-cloud support could be used in the real world, then get your thoughts 
written out below so we can consider them during development.

I would be especially keen to hear from people who have used ARM and GDM and
understand the common gripes with these tools. 

Let's make this happen!

**Comment by zaro0508** [comment]
Closing as sole focus has always been AWS. If people feel strongly and are committed to adding this feature, reopen.
