### ISSUE TITLE
Azure Spike

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#403]
# CONTEXT 

As part of our effort for #385 we want to develop a "spike" of "Azure support for Sceptre". 

The purpose of the spike is to experiment and figure out some of the challenges we might face when implementing Azure support "properly". With a working prototype we can avoid any "big design upfront" and make use of learnings for the full implementation. The spike shouldn't focus on code quality or tests etc - just get it working. 

The development of the spike is probably best done in a fork, rather than a branch. A secondary goal should be to implement Azure support with as few changes the existing code base as possible.

# DONE WHEN 

- Demonstrate a simple Azure stack being deployed using Sceptre and Azure Resource Manager.

- A draft is written with suggestions about how we can best implement Azure support in Sceptre. Specifically, we will want to note the commonalities and differences between Azure and AWS. Identify appropriate abstractions and highlight any nuances in ARM that Sceptre could help make smoother.

**Comment by craighurley** [comment]
Closing as sole focus has always been AWS.  If people feel strongly and are committed to adding this feature, reopen.
