### ISSUE TITLE
GCP Spike

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#404]
CONTEXT
As part of our effort for #385 we want to develop a "spike" of "GCP support for Sceptre".

The purpose of the spike is to experiment and figure out some of the challenges we might face when implementing GCP support "properly". With a working prototype, we can avoid any "big design upfront" and make use of learnings for the full implementation. The spike shouldn't focus on code quality or tests etc - just get it working.

The development of the spike is probably best done in a fork, rather than a branch. A secondary goal should be to implement GCP support with as few changes the existing code base as possible.

DONE WHEN
Demonstrate a simple GCP stack being deployed using Sceptre and Google Deployment Manager.

A draft is written with suggestions about how we can best implement GCP support in Sceptre. Specifically, we will want to note the commonalities and differences between GCP and AWS. Identify appropriate abstractions and highlight any nuances in GDM that Sceptre could help make smoother.

**Comment by ocsig** [comment]
I'm happy to review the early design and bring in GCP, Deployment Manager expertise, please reach me out.

**Comment by ngfgrant** [comment]
@ocsig Hey Adam - how are things? Would be great to get your input when I get a bit of time I will outline how I see the overall code structure for this and then we will need to think how well the current sceptre commands map on to Deployment Manager. Would be super to get your involvement.

**Comment by henrybell** [comment]
Nice @ocsig!

**Comment by davemorrow-telus** [comment]
Has the GCP spike died?

**Comment by craighurley** [comment]
Closing as sole focus has always been AWS.  If people feel strongly and are committed to adding this feature, reopen.
