### ISSUE TITLE
Deleted stacks are shown in 'PENDING' state

### ISSUE THREAD

**Issue by dsumsky** [Sceptre/sceptre#468]
Why deleted stacks are shown in 'PENDING' state? Is this a typo or is there any reasoning behind this?
https://github.com/cloudreach/sceptre/blob/fcbc2edf2ac3818ce14d3d45f3b001151d5fcdef/sceptre/environment.py#L163

**Comment by ngfgrant** [comment]
I am not entirely sure why this is the case - looks like it hasn't changed since the initial commit in v1. Probably a typo?

**Comment by zaro0508** [comment]
No longer applicable since sceptre V2 does not have sceptre/environment.py anymore
