### ISSUE TITLE
Cannot embed shell for debugging during development

### ISSUE THREAD

**Issue by mattvonrocketstein** [Sceptre/sceptre#475]
Sceptre seems to suffer from exactly the same issue as is [described here](https://github.com/google/python-fire/issues/19) namely that pdb has kind of reserved `cmd.py` for itself.  Can cmd.py be renamed?

**Comment by ngfgrant** [comment]
Just looking at this real quickly I think it would result in a breaking change to the API which would require a version bump. I will fix for v2 as it is a real pain.

**Comment by zaro0508** [comment]
i believe this is fixed in sceptre v2.
