### ISSUE TITLE
Support for custom Jinja filters

### ISSUE THREAD

**Issue by mattvonrocketstein** [Sceptre/sceptre#476]
My use-case involves adding new custom Jinja filters into projects using the v1 releases of sceptre, which I haven't found a supported way to accomplish.  I think this should work in way similar to hooks/resolvers, i.e. loading this project-specific functionality from "jinja_filters" folder underneath the sceptre root.  

EDIT: [pull here](https://github.com/cloudreach/sceptre/pull/477) for discussion

**Comment by 1oglop1** [comment]
+9001

**Comment by zaro0508** [comment]
this is old, sceptre v1 is no longer supported
