### ISSUE TITLE
Hook execution before create-change-set?

### ISSUE THREAD

**Issue by craighurley** [Sceptre/sceptre#489]
```sh
$ sceptre --version
Sceptre, version 1.4.
```

It appears that hooks do not get called when calling `create-change-set`, like this:

```sh
sceptre create-change-set dev/vpc vpca cs181023001
```

From looking at `stack.py`, it looks like that is a deliberate...

https://github.com/cloudreach/sceptre/blob/v1.4.2/sceptre/stack.py#L517

```py
    def create_change_set(self, change_set_name):
```

vs

https://github.com/cloudreach/sceptre/blob/v1.4.2/sceptre/stack.py#L183-L184

```py
    @add_stack_hooks
    def create(self):
```

I was planning on using the `cmd` hook to perform custom actions on a given template before creating the change set.

- Is there a workaround for my use case?
- Are there any plans to support hooks for additional commands such as as `create-change-set`?

Thanks.

**Comment by padilo** [comment]
related to: https://github.com/cloudreach/sceptre/pull/227

**Comment by ianburrell** [comment]
Hooks for create_change_set are needed when there are "update" hooks that are needed to apply updates. For example, uploading templates for nested stacks or files for bootstrap scripts.

The other option would be to run the "update" hooks for create_change_set.

**Comment by ianburrell** [comment]
We made local fork for v1 with create_change_set hook, and working on converting to v2.

**Comment by RobReus** [comment]
Any update on this? Running into an issue where I need a hook to be executed before creating a change set.

**Comment by ngfgrant** [comment]
I think this is possible in v2, although I’d need to check. We won’t be updating V1 to support.
