### ISSUE TITLE
use resolvers in config files

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#505]
Do sceptre config files support resolvers?  I would like to use a resolver to pass an existing stack output value to template_bucket_name.  something like this..

--- config.yaml file ---
project_code: my-project
profile: "default"
region: "us-east-1"
template_bucket_name: !stack_output_external bootstrap:: CloudformationBucket
template_key_prefix: "testing"

**Comment by nabeelamjad** [comment]
They do not, only [these properties](https://github.com/cloudreach/sceptre/blob/3981da00427a487d503e5b7c6c83c91da13fac78/sceptre/stack.py#L49) support resolvers.

**Comment by zaro0508** [comment]
Thanks you @nabeelamjad.   @ngfgrant Could we mark this as a feature request?

**Comment by ngfgrant** [comment]
@zaro0508 will put this down as needs discussion as we need to think if this would have an unintended implications elsewhere. I think it would certainly only be considered in the context of `v2` codebase.

**Comment by laur1s** [comment]
Hi, @ngfgrant would it be possible to implement this in v2 of sceptre?

**Comment by ngfgrant** [comment]
Hey @laur1s - honestly I am not sure exactly how this would work with the current setup. It might _"just work"_ but I doubt it. I am not a fan of the current implementation details of Resolvers (see #502) but the concept of resolvers themselves is good.

Happy to see a PR for this and discuss it...

**Comment by zaro0508** [comment]
an attempt to implement this is in PR #1153

**Comment by zaro0508** [comment]
closing as duplicate of issue #1114
