### ISSUE TITLE
Reading Stack config variables from custom resolvers

### ISSUE THREAD

**Issue by sopeters** [Sceptre/sceptre#532]
Using v2.0 - I'm trying to write a resolver that will need to read other config parameters from the same config file.

self.stack.parameters is a recursive error (due to the ResolvableProperty).

Can a resolver read specific values/parameters from the stack specific config file?

**Comment by nabeelamjad** [comment]
You shouldn't need to write a resolver for that purpose, in your stack file you can have something like:

```
parameters:
  region: {{ stack_group_config.region }}
```

Replace region with whatever you want to fetch from your config.

**Comment by sopeters** [comment]
I tried something like this but got error:
if not isinstance(key, collections.Hashable)

My config has
`
template_path: test.yaml
parameters:
    param1: !custom_resolver {{ stack_group_config.param2 }}
    param2: value2
`

I'm trying to write a resolver that calculates / determines an ALB priority from an existing ALB (which is the parameter I'd like to pass into the resolver).

**Comment by nabeelamjad** [comment]
Just to be clear, you have a stack (test.yaml) specifying `param1: {{ stack_group_config.param2 }}`, which is referencing your `config.yaml` which has `param2` specified in there?

Could you post your `config.yaml` as well (minimal failing example).

**Comment by sopeters** [comment]
stack_group_config isn't what I need.

I'm trying to forward an existing stack output from a different stack to a custom resolver.
Alternative trying to read another config parameter in the same stack.

* I have an ALB that is created in template A (and gets and output for the ARN there).
* In template B (for an application that uses above ALB) I want to use a custom resolver that calculates the ALB priority for the application. So I will need to feed into the custom resolver in template B either the output of template A or use a parameter from the same template B config that refers to the ALB ARN via !stack_output

Hope it's clearer

**Comment by sopeters** [comment]
Thanks - I wouldn't know how to do this otherwise if not using a !stack_output to feed into a custom resolver and/or have the custom resolver read the other config variables from the to-be-build stack.

**Comment by sopeters** [comment]
@nabeelamjad - Did you get a chance to look at this or need more information?

**Comment by nabeelamjad** [comment]
I've not had the time for this yet unfortunately, have been quite busy. I'll try to get it solved this weekend!

**Comment by sopeters** [comment]
Cool - I'm around, so let me know what I can help with

**Comment by nabeelamjad** [comment]
This seems a little bit more complicated due to the way properties are resolved right now, however when we change how that works in #502 then we can properly support this. I don't think that'll happen before January though.

**Comment by sopeters** [comment]
Thanks - appreciated. If you need any more information let me know.

**Comment by zaro0508** [comment]
closing issue due to old age and there does seem to be a workaround.
