### ISSUE TITLE
Stack update fails when config has dependency / stack_output reference with no change

### ISSUE THREAD

**Issue by sopeters** [Sceptre/sceptre#533]
If I do a change in a stack config xyz.yaml which has a dependency / reference to an output of stack abc.yaml (with !stack_output) and I run sceptre update env/xyz the result is that it tries to update the dependency stack "abc" (which hasn't changed) and giving me the below and exits

sceptre.plan.actions - env/abc - Updating Stack
An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed.

The actual stack that has changes (xyz) is never touched / updated

Used Version 2.0.0rc2

**Comment by nabeelamjad** [comment]
Does the behavior work correctly as you expect it with "launch" instead of "update"?

**Comment by sopeters** [comment]
Thanks - "launch" works vs "update" doesn't. Might be good to track as bug

**Comment by nabeelamjad** [comment]
We'll get this fixed in the next bug fix update, which will hopefully hit this week.

**Comment by inventionlabsSydney** [comment]
Any update on this? I am also experiencing this issue.

**Comment by ngfgrant** [comment]
@inventionlabsSydney do you still have this issue in 2.1.5?

**Comment by inventionlabsSydney** [comment]
I'm currently using 2.1.3 so this might be my issue haha.

**Comment by ngfgrant** [comment]
yeh I think we fixed in either 2.1.4 or 2.1.5, can't remember. If it is still giving you an issue please let me know.
