### ISSUE TITLE
SecretManager resolver in templates throws error

### ISSUE THREAD

**Issue by sopeters** [Sceptre/sceptre#544]
I'm trying to use Secrets Manager to hold DB passwords and part of my template is

MasterUserPassword: '{{resolve:secretsmanager:<name>:SecretString:password}}'

When launching the stack for an existing RDS I'm getting 

`An error occurred (ValidationError) when calling the UpdateStack operation: Parameters: [MasterUserPassword] must have values`

Uploading the template directly into CloudFormation works with no issues.

**Comment by ngfgrant** [comment]
Hey @sopeters 

Which version of Sceptre are you using and can you provide a bit more information about your stack and template? Can you also share the secrets manager custom resolver you are using?

**Comment by sopeters** [comment]
Hi @ngfgrant - using 2.0.0 release and it's a pretty simple YAML template. No custom resolver as AWS supports {{resolve:secretsmanager:<name>:SecretString:<string>}}:

https://aws.amazon.com/blogs/security/how-to-create-and-retrieve-secrets-managed-in-aws-secrets-manager-using-aws-cloudformation-template/

I have one template that creates a secret via:
`
DBSecret:
  Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretsPrefix
      Description: RDS Access Details
      SecretString: !Sub '{"username": "${MasterUsername}", "password": "${MasterUserPassword}"}'

  SecretsArn:
    Description: "ARN of Secrets entry"
    Value: !Ref DBSecret
`

The DB Template uses it via Parameter and !stack_output:

`
DB:
    Type: AWS::RDS::DBInstance
    Properties:
    ...
    MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref SecretsArn, ':SecretString:username}}']]
    MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref SecretsArn, ':SecretString:password}}']]
`

**Comment by iAnomaly** [comment]
@sopeters, your issue is quite a few months old at this point so maybe you have already resolved it on your own. If not however, the cause of this is that `{{ }}` notation used by CloudFormation dynamic references clashes with Jinja's templating notation/syntax. Please see the [Jinja documentation section on escaping](http://jinja.pocoo.org/docs/2.10/templates/#escaping).

**Comment by saranyasridharan** [comment]
@ngfgrant How did you solve your issue ? in my case, I am not getting error also not getting the value resolved.

**Comment by AdannaAkwats** [comment]
Escaping '{{' worked for me. 
Like this: 

> MasterUsername: !Join ['', ['{{'{{'}}', 'resolve:secretsmanager:', !Ref SecretsArn, ':SecretString:username', '{{'}}'}}']]

**Comment by saranyasridharan** [comment]
Did you try in userdata file in ec2 creation? @iAnomaly

**Comment by iAnomaly** [comment]
@saranyasridharan I'm not sure what you are trying to accomplish specifically. If you share an example we might be able to help.

If you are trying to use CloudFormation dynamic references in UserData specifically, it's not supported by CloudFormation. I have a custom Sceptre Resolver for that case here if you would like to read more: https://github.com/iAnomaly/sceptre-resolver-aws-secrets-manager

**Comment by saranyasridharan** [comment]
Thanks for the reply @iAnomaly . I will take a look.

**Comment by zaro0508** [comment]
Does your resolver do the same thing as the [sceptre-ssm-resolver](https://github.com/Sceptre/sceptre-ssm-resolver) @iAnomaly?

**Comment by iAnomaly** [comment]
Not unless that resolver has also added support for AWS Secrets Manager @zaro0508. Systems Manager's Parameter Store is an entirely separate service/feature of AWS.
