### ISSUE TITLE
launching/deleting stackgroup whose name is substring of other stackgroup will also launch/delete other stackgroup

### ISSUE THREAD

**Issue by jmwyson** [Sceptre/sceptre#546]
I have the following stack config structure

env/s1.yaml
```
template_path: mystack.template.yaml
parameters:
  Name: envs1
  Value: envs1
```

env1/s1.yaml
```
template_path: mystack.template.yaml
parameters:
  Name: env1s1
  Value: env1s1
```

When I run the command `sceptre launch env` both env/s1 and env1/s1 are launched even if they are unrelated. Similarly when I run `sceptre delete env` both env/s1 and env1/s1 are deleted even if they are unrelated.

I also tested the scenario renaming env to env2 and in this case env1 and env2 can be launched separately. Then I also tested renaming env1 to env-sec, in this scenario, both env and env-sec launched simultaneously when trying to launch env only.

How do I launch env without launching env1?

**Comment by ngfgrant** [comment]
Hey @jmwyson 

Thanks for raising this issue, I was able to reproduce it. The section of code that deals with deciding which stacks will eventually be executed is https://github.com/cloudreach/sceptre/blob/master/sceptre/config/reader.py#L206

```python
if abs_path.startswith(self.context.full_command_path()):
    command_stacks.add(stack)
```

I have tested a couple of potential solutions to this. Whilst using strict equality here will fix your issue it means we can't support execution on StackGroups that only contain other StackGroups. I.e. if you had an additional StackGroup in your setup that was above the other two called 'my-envs' you would be unable to do `sceptre launch my-envs`. So for the time being I think we will need to stick with the current `startswith()` check on line 206 in ConfigReader.

The quickest and best fix for this in your case is to use more distinct names for your StackGroups such that the `startswith()` will consider them separate enough, as you pointed our renaming env -> env2 would be enough.

I will leave this open, label as a bug, open a PR to note this limitation and we can think about how best to handle this specific case in the future.

**Comment by Mehul1313** [comment]
Has there been any update I see the similar issue.

For instance deleting sandbox resource deletes staging and prod resoruces too.

 sceptre --var-file=config/variables/sandbox-us-west-2.yaml --debug delete  sandbox/ecs-fargate-cluster.yaml
:
The following stacks, in the following order, will be deleted:
sandbox/load-balancers
staging/load-balancers
prod/load-balancers
sandbox/ecs-fargate-cluster
.
.

**Comment by adnanhb** [comment]
@Mehul1313 I am having a very similar issue. Any luck resolving it?

**Comment by Mehul1313** [comment]
@adnanhb , No I did not. I do not have a fix. I end up deleting stack (one stack at a time) manually.

**Comment by ngfgrant** [comment]
#731 will resolve this and I've just message the original PR author to see if they have time to resolve a conflict then will get this merged and released.
