### ISSUE TITLE
Add `sceptre debug` command

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#553]
# Proposal

Add a convenience CLI command and API method that would generate useful information for users to share when raising issues. 

Much of the time the same questions are asked when helping users to debug issues. This includes:

- project structure
- output of config files
- dependencies output 

Structure of the command/api would be something like

```shell 
sceptre debug OUTPUT_PATH
```

```python

context = SceptreContext(project_path, command_path)
plan = SceptrePlan(context)
plan.debug("path/to/save/report)
```

I propose that initially the debug report contains:

- A `tree` from "project_path" 
- A DiGraph representation of dependencies 
- Full print out of StackGraph (containing generated stacks)
- The output from `validate()` on each template.

We _could_ potentially add to this:

- some fuzzy searches against a bunch of v1->v2 checks. I.e. we could highlight where keywords from v1 still exist such as `environment`, `environment_path`, `environment_config`. 

- some fuzzy searching for potentially misspelt known config keys. 

We would need to be aware of making sure users don't inadvertently share secrets.

**Comment by 1oglop1** [comment]
I'm on this one.

how do you like folder tree better?
```
project-dir/ 
     file
     file

    config/ 
         config.yaml

        lab/ 
             config.yaml
             vpc.yaml
```

or without spaces

```
project-dir/ 
     file
     file
    config/ 
         config.yaml
        lab/ 
             config.yaml
             vpc.yaml
```

**Comment by ngfgrant** [comment]
Without spaces please.

**Comment by zaro0508** [comment]
This issue is old and it hasn't been a huge problem so closing.
