### ISSUE TITLE
Bring back support for simple custom resolvers read from the resolvers directory

### ISSUE THREAD

**Issue by et304383** [Sceptre/sceptre#554]
I don't want to build pip packages or write setup.py files.  I would like a simple way to use custom resolvers like was supported in version 1.

**Comment by ngfgrant** [comment]
Over the course of the project we’ve had a lot of requests to make hooks and resolvers easier to manage across projects. There was previously a lot of duplication between projects. 

The changes made address that and actually allow the community to reliably share hooks and resolvers with each other via pypi I’d they wish. 

Setting up a ‘setup.py’ is trivial but how about we add a helper to the ‘sceptre new ...’ command to assist with the building of setup.py and maybe a helper to discover and install all modules in hooks and resolvers directory to help mitigate that workload? 

In terms of reverting the change or adding in v1 behaviour, that won’t happen in v2, but I’d welcome suggestions on how to make life a bit easier with the new structure.

**Comment by et304383** [comment]
I don't see why the original behaviour couldn't have been preserved.  

If resolvers directory, read the files.

Yes, there is duplication (we have an acm resolver in every project) but deciding to just break the existing functionality seems like a poor design decision, IMO.

**Comment by zaro0508** [comment]
IMO we don't need multiple ways to support plugins.  It bloats the code and causes confusion.   I think V2 is a better approach.

**Comment by et304383** [comment]
Is this behaviour going to be restored in any way?  If not, then Sceptre, for us, will be forever stuck at version 1.x and/or we'll have to switch to another product.  :(

**Comment by ngfgrant** [comment]
Hey @et304383 don't know yet - there have been other more pressing things. Obviously, I want every one to feel that they can continue to use the tool. I am happy to review a PR for this if someone is willing to take a stab at it? It's still on my radar to look at but at this moment I can't make any promises that we can definitely bring it back; would need to see what was changed in more detail.

**Comment by ngfgrant** [comment]
I had this in mind when designing v3 sceptre-core. It might be possible to do this without too much additional pain.

**Comment by zaro0508** [comment]
V1 is no longer supported and it's unlikely this functionality will return in V2 and beyond.
