### ISSUE TITLE
Bring back support for iam_role

### ISSUE THREAD

**Issue by seddarj** [Sceptre/sceptre#571]
Hi,

I would really like to see `iam_role` support brought back.

It is mandatory for any project with multiple accounts and multiple users which cannot be forced to setup the exact same profiles on their machines for all the accounts they have to manage.

Thanks

**Comment by ngfgrant** [comment]
Ok I am happy to look into how this would fit within v2.

**Comment by seddarj** [comment]
Thanks @ngfgrant, much appreciated!

**Comment by tlkcr** [comment]
@ngfgrant Do you have any update on this?

**Comment by ngfgrant** [comment]
@tlkcr I don't have a timescale for this at the moment. Accepting pull requests for this though...

I've labelled as 'help wanted'.

**Comment by tlkcr** [comment]
I am more than happy to help but it would be good to understand why it has been removed from V2 initially.

**Comment by ngfgrant** [comment]
The original discussion (and subsequent change) happened around thihttps://github.com/cloudreach/sceptre/issues/257. 

I guess there is also an option to add a feature so that a user can add a custom map of profiles as Sean originally suggested.

**Comment by tlkcr** [comment]
This would introduce dependancy on a non-versionned file and sounds like a bad idea.

I see no good reason to implement a mapping neither as it would incur room for mistake between users. If a user cannot be sure he is using the same role (hence same policy) it is not predictable which permission will be available which could lead to mistake/misunderstanding.

I would recommend to recover the iam_role feature as it is in 1.5.

**Comment by ngfgrant** [comment]
@tlkcr Ok - like I said, happy to receive a PR for this. 

For anyone willing to pick this up. In terms of credential hierarchy see: https://github.com/cloudreach/sceptre/pull/395. The new hierarchy should be: 

1. Environment variable credentials take priority over profiles
2. Region specified in the Sceptre Stack configuration will take priority over the one specified in the profile
3. Profile
4. IAM Roles

Any implementation would need to ensure that roles worked cross account/region too.

**Comment by tlkcr** [comment]
Ok, clear.
Can you just elaborate a bit on :

> Any implementation would need to ensure that roles worked cross account/region too.

**Comment by ngfgrant** [comment]
Would just need to see that using roles you could still deploy to various accounts/regions as with profiles.

**Comment by tlkcr** [comment]
oh, you mean using a role to switch to another role somewhere else? Isn't it transparent from a role/profile perspective?

**Comment by zaro0508** [comment]
Sceptre docs declares that sceptre supports `role_arn` in template config: https://sceptre.cloudreach.com/latest/docs/stack_config.html#role_arn

Does this not provide the same functionality as `iam_role`?

**Comment by SmoothGlide** [comment]
> Sceptre docs declares that sceptre supports `role_arn` in stack config: https://sceptre.cloudreach.com/latest/docs/stack_config.html#role_arn
> 
> Does this not provide the same functionality as `iam_role`?

I have attempted to use the role_arn in the stack config and it simply does not seem to work.  
This is one reason I have not been able to move to v2 

For example when running a template validate on a large template, I use a template_bucket. The validation in v1.4.2 works just fine with iam_role defined in the config.yaml
With v2 - I try adding role_arn directly in the stack config and the template validation fails and it complains that it cannot access the template bucket.

**Comment by seddarj** [comment]
@zaro0508 @SmoothGlide As per the documentation,  `role_arn` refers to something completely different than `iam_role`:  `role_arn` is the ARN of the role CloudFormation (not Sceptre) should use to handle (create, update, delete) the stack resources.

@ngfgrant Could you give more details about the cross-account feature when it comes to profiles? How does a profile enable Sceptre to do cross account operations?

**Comment by SmoothGlide** [comment]
@seddarj As far as I can tell, the profile simply uses IAM keys
