### ISSUE TITLE
[For V3] `imp` module is deprecated in favour of `importlib`

### ISSUE THREAD

**Issue by 1oglop1** [Sceptre/sceptre#582]
`template.py` is using deprecated `imp` module

the imp module is deprecated in favour of importlib
https://github.com/cloudreach/sceptre/blob/master/sceptre/template.py#L10

possible fix: is to take similar approach like here: https://github.com/pyinvoke/invoke/issues/214

**Comment by ngfgrant** [comment]
Following the approach in pyinvoke/invoke#214 will be problematic as we still support 2.7. The `importlib.machinery` was only added in 3.4.  We can take this approach when we drop python2 support in a future Sceptre version (v3+).

**Comment by 1oglop1** [comment]
Sounds good, will you leave the issue open?
It might be good to mark it with some label then.

**Comment by ngfgrant** [comment]
I have a commit (317391af0f140b737298e3d7550b6cf14f4e7216) in https://github.com/Sceptre/sceptre-provider-aws that resolves this
