### ISSUE TITLE
Support for sceptre_user_data at the stack_group level

### ISSUE THREAD

**Issue by akio-outori** [Sceptre/sceptre#604]
Question / feature request:

Is there any support for sceptre_user_data at the stack group level?  What I'm trying to do is create a set of security group rules for a long series of subnets across multiple stacks.  Using jinja templates this works fine at the stack level, but leads to some code re-use.  It'd be great if these could be set at a project level instead.

**Comment by zaro0508** [comment]
All sceptre config files are loaded as jinja templates so i'm wondering whether you can solve this by simply using a combination of jinja include and import? here's a reference and some examples, https://ttl255.com/jinja2-tutorial-part-6-include-and-import/

**Comment by zaro0508** [comment]
no response from reporter so closing
