### ISSUE TITLE
Sceptre resolver to get the current date

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#608]
I would like to inject the current date to a cloudformation parameter in the stack config file.  I haven't found a way to do this with plain yaml.  A sceptre resolver would make this possible though.  Something like..

```
parameters:
    now: !date
```

I think this would help with issue #279. Basically it would allow empty updates with sceptre instead of having to run a lambda in AWS (the work around mentioned by @mithun -> https://forums.aws.amazon.com/thread.jspa?threadID=229748)

**Comment by ngfgrant** [comment]
Happy to receive a PR for this. As you said it has multiple applications.

**Comment by zaro0508** [comment]
@ngfgrant Not sure whether you meant as a core resolver or a plugin so i created a plugin.  here you go https://github.com/zaro0508/sceptre-date-resolver

**Comment by ngfgrant** [comment]
Thanks @zaro0508 I will add as part of Cloudreach repo along with the other resolver you've contributed. 

🙏 Thanks again

**Comment by zaro0508** [comment]
This resolver has been moved to https://github.com/Sceptre/sceptre-date-resolver with PR https://github.com/Sceptre/sceptre-date-resolver/pull/7
