### ISSUE TITLE
Updating many CF at once

### ISSUE THREAD

**Issue by FLavalliere** [Sceptre/sceptre#614]
```
[2019-01-28 14:18:42] - Request limit exceeded, pausing...
[2019-01-28 14:18:42] - Request limit exceeded, pausing...
```
Using a custom resolver that will do something like this 

        client = boto3.client('cloudformation')

Got error of :

local/lib/python3.5/site-packages/botocore/session.py", line 826, in create_client
    credentials = self.get_credentials()
local/lib/python3.5/site-packages/botocore/session.py", line 425, in get_credentials
    'credential_provider').load_credentials()
...
KeyError: 'credential_provider'

Ie : having over 20 stack to update... I would like to issue the update on all of them in parallel but right now the code breaks due to rate-limit.

**Comment by ngfgrant** [comment]
Hey @FLavalliere 

Can you describe the use-case for having a custom resolver that creates a boto3 client? If you are wanting to update a bunch of stacks you could do that by creating a `SceptreContext` with the appropriate `command_path`, create a `SceptrePlan` with the context such as:

```python
context = SceptreContext(path/to/project, path/to/stacks)
plan = SceptrePlan(context)
plan.update()
```

**Comment by FLavalliere** [comment]
We currently use the boto client to describe the cloudformation to validate some values that was created that might of changed. Ie: Something like describe the Current Autoscaling values of the stack we will be updating, and ensure we do not decrease the current ASG size.

We currently only use the bash command line, i assume we could create a python script to actually do what you are describing for the SceptreContext.

**Comment by ngfgrant** [comment]
Yep sounds like you could script this in python an utilise the methods in `plan`. Probably a mix of `generate()` and/or `describe_*()` and then `update()/launch()`

API docs: https://sceptre.cloudreach.com/latest/docs/api/sceptre.plan.html
