### ISSUE TITLE
Access the "user_variables" from Resolvers and Hooks - sceptre v2

### ISSUE THREAD

**Issue by medbensalem** [Sceptre/sceptre#618]
Hi,

It seems like there is a bug with scepter v2 where you can not access the `user_variables` from hooks and resolvers.
In v1 you could perform that by doing this for example:

> self.environment_config['user_variables']['OUR_VARIABLE_NAME']

But it doesn't seem to be an equivalent way in v2.

**Comment by ngfgrant** [comment]
This will be resolved by https://github.com/Sceptre/sceptre/pull/782 and it will be possible to access variables through the `context`.

**Comment by zaro0508** [comment]
closing this because it's really old and #782 is also closed
