### ISSUE TITLE
Allow for a default in stack_output resolver

### ISSUE THREAD

**Issue by pwrmiller** [Sceptre/sceptre#651]
Currently the stack_output resolver does not support a default, raising `DependencyStackMissingOutputError` if an output parameter is not found.

Consider modifying the stack_output resolver to add an additional parameter specifying a default if the output parameter is not found.

The other option we have would be to make sceptre parameters conditional by adding a jinja2 filter like Ansible's `omit`. (see: [Filters - Ansible Documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#omitting-parameters). Would optional stack config like this be desirable for parameters in sceptre?

**Comment by zaro0508** [comment]
This does seems like a useful feature.    The other option, which i've been using, is to add the parameter to your CF template and set a default value there.

**Comment by zaro0508** [comment]
This issue is old and there does seem to be a workaround therefore closing.
