### ISSUE TITLE
Add ability to create a new stack with change sets

### ISSUE THREAD

**Issue by kirkhansen** [Sceptre/sceptre#663]
I would like to be able to use change sets on new stacks as well as existing stacks.

AWS/boto supports creating a new stack with change sets using the `ChangeSetType` keyword [see here for details](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.create_change_set).  To the untrained eye, it appears that updating the cli `create` and `update` to pass an argument of `change_set_type` to the `create_change_set` function, and updating that function to accept the new argument may get me the functionality I'm after. I'm up for a PR if this makes sense to implement.

Outputs may be a bit tricky to deal with, but I haven't gotten that far down the path yet.

It looks like there was an attempt to address this with #198 , but that appears to have been closed, and inactive for awhile (thus the new issue).

**Comment by m1keil** [comment]
That's a good catch. I just started using change-sets myself and haven't realized that my workflow will break anytime I add a new environment to my configs in CI/CD.

Here's the error:
```
$ sceptre create -y dummy test
/Users/msverdlik/.virtualenvs/sceptre/lib/python3.7/site-packages/yaml/constructor.py:126: 
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack [test-dummy] does not exist
```

**Comment by ngfgrant** [comment]
Yep I think we should support this. Also partly related to #520

**Comment by rgillen** [comment]
I have implemented a change locally to get basic change sets working when creating a new stack. I would like to inquire if you would accept a limited scope pull request for this... if so I think it would be good to clarify the exact scope of the changes before submitting a pull request.

**plan/actions.py(create_change_set)**
- Add 2nd argument `change_set_type` to def
- Add parameter `change_set_type` to  `create_change_set_kwargs` as `ChangeSetName`

**cli/create.py(create_command)**
- Add argument `change_set_type=CREATE` to `plan.create_change_set` call

**cli/update.py(update_command)**
- Add argument `change_set_type=UPDATE` to `plan.create_change_set` call

**Corresponding Tests & Documentation to be added as appropriate**

**Comment by kirkhansen** [comment]
@ngfgrant any thoughts on @sacvalleytech's comment?

**Comment by hilllaboratories** [comment]
Is there any chance of moving this along? At the moment we can't create changesets for new stacks, which breaks any ability to use changesets for a group when new stacks are involved, which means we can't preview our changes, which is dangerous for production deploys.

**Comment by roneystein** [comment]
This could be added at least for treating cases were there are no dependent stacks. Would solve my use case at least as I don't use sceptre for beyond single stacks creation/updates. A CLI option could be used to alter the default behavior.

**Comment by alex-harvey-z3q** [comment]
This was fixed in https://github.com/Sceptre/sceptre/pull/1469

**Comment by alex-harvey-z3q** [comment]
Duplicated by #915
