### ISSUE TITLE
template output location

### ISSUE THREAD

**Issue by networkpadawan** [Sceptre/sceptre#689]
hi
is there a way to call the output stack json file before it´s uploaded to s3? 
I would like to use something like a hook before_create and make validations on the template (cfn-lint, cfn-nag, ...)

**Comment by craighurley** [comment]
You can run `scepter generate` to print the template(s).  With that in mind, you could bake a script to lint/nag on commit/pull request or even on file change (e.g. using something like python [watchdog](https://github.com/gorakhargosh/watchdog)).

**Comment by networkpadawan** [comment]
Sceptre generate could work thks:)
That part is what I’m doing with jenkins, it triggers on push to repo. Lint works for the bare template but would like something after the resolvers/outputs of variables are added to the templates but before creating the stack.

**Comment by ngfgrant** [comment]
like @craighurley suggests `hooks` and `generate` probably your friends here within a script or utilise the API directly in another script.

**Comment by networkpadawan** [comment]
hi, just tested this, but as far as i can go, the generate template literally only generates the template, it does not injects the values of the parameters. is there no way to catch the json file before its uploaded to s3 for deployment?

**Comment by networkpadawan** [comment]
also, to be on the same page i mean cloudformation template not "sceptre" template:) thank you!
