### ISSUE TITLE
Improve launch command documentation

### ISSUE THREAD

**Issue by Marakai** [Sceptre/sceptre#714]
For automated workflows I would like to be able to create/update stacks without having to check every time via some shell ugliness whether a sceptre stack already exists.

It would be great to have an "upsert" (as it's sometimes called for databases), or "crupdate":

"if stack does not exist: create; else update"

**Comment by henrist** [comment]
Have you tried the `launch` command? It should do exactly that. As you can see from the code it will do either create or update as fit:

https://github.com/cloudreach/sceptre/blob/42b24c6d41144eb15a3ed48f7effab1d3861055e/sceptre/plan/actions.py#L161

**Comment by Marakai** [comment]
Oops, seems I was mentally stuck in the CFN create-stack vs update-stack approach, I didn't even look. And wondering "when would I bother with the launch command?"

I shall endeavour to RTFM more, though as you'd commented elsewhere, the  docs could use a bit of expansion and organising. ;)

**Comment by henrist** [comment]
I agree that the docs should be more clear about this. I had similar issues as you.

**Comment by ngfgrant** [comment]
Would be delighted to review a PR that helps improve the docs in this area if you’d like to have a shot?
