### ISSUE TITLE
Idea: Add ability for custom template filetypes

### ISSUE THREAD

**Issue by cyphus** [Sceptre/sceptre#715]
Sceptre comes with out-of-the-box support for json, yaml, Jinja2, and Troposphere based templates.

I'd like to register the `.jsonnet` extension for rendering [Jsonnet](https://jsonnet.org) templates before upload.

But rather than make a PR to add Jsonnet rendering and indirectly force the sceptre developers to support this filetype indefinitely, why not make template rendering customizable like hooks and resolvers? That way, the Jsonnet renderer can be developed and maintained independently.

Template rendering is already nicely contained in the [Template#body](https://github.com/cloudreach/sceptre/blob/master/sceptre/template.py#L67-L95) method. I could make a PR to call out to custom renderers based on the template extension, and refactor the existing filetype rendering logic to their own classes so they can exist as builtin renderers.

@ngfgrant Do you think custom template renderer support is inline with Sceptre's unopinionated philosophy? How likely would you approve a PR that adds, tests, and documents this functionality?

For me, adding support for custom renderers means I can add support for Jsonnet rendering to my project without having to fork Sceptre, and I very much want to avoid forking if I can.

**Comment by zaro0508** [comment]
The idea of a custom template handlers is proposed in PR 864

**Comment by zaro0508** [comment]
We now have template handlers via PR https://github.com/Sceptre/sceptre/pull/1088 which will allow anyone to create their own custom template resolvers.
