### ISSUE TITLE
Idea: stack_ouput would omit current local path/to/file

### ISSUE THREAD

**Issue by arnaudgay-cr** [Sceptre/sceptre#720]
In Sceptre V2 (2.1.3) !stack_ouput is defined like :
`!stack_output path/to/infrastructure.yaml::VpcId`
If you project structure looks : 
```
├───config
│   └───myapp
│       └───subtree1
│       │    ├───template-1.yaml
│       │    └───template-2.yaml
│       └───subtree2
│       │    ├───template-a.yaml
│       │    └───template-b.yaml
│       └───subtree3
│        ......

```
Refering template-1 from template-2 must be :
> ```yaml
> myvar:
>   - !stack_output myapp/subtree1/template-1.yaml::value
> ```

It should be nice to omit the complete path for file located in the same folder.
For instance here : 
> ```yaml
> myvar:
>   - !stack_output template-1.yaml::value
> ```
Assuming that when no path is given, the "local" path is taken.

It is specially usefull when the subtree path is deep or if the folder might move to another location.

This should be done in `stack_output.py` setup method by adding:
> ```python
> def setup(self):
>     """
>     Adds dependency to a Stack.
>     """
>     dep_stack_name, self.output_key = self.argument.split("::")
>     if not os.path.dirname(dep_stack_name):
>         dep_stack_name = os.path.join (
>             os.path.dirname(self.stack.name),
>             os.path.basename(dep_stack_name)
>         )
>     self.dependency_stack_name = normalise_path(dep_stack_name)
>     self.stack.dependencies.append(self.dependency_stack_name)
> ```

**Comment by ngfgrant** [comment]
Hey @arnaudgay-cr 

Iirc This was the way it worked in v1. In v2 we changed the way dependencies were handled and it required things like `stack_output` to be a bit more explicit. 

Just off the top of my head I am not sure this is quite as easy as it seems, hence we needed the change. When we had the discussion during the development of v2 I recall that there was a sense that although more convenient not to specify the path, actually being slightly more explicit had some merit for improving clarity.

Have you been able to test the suggestion above? In particular I wonder what would happen if the project structure was like:

```
├───config
│   └───myapp
│       └───subtree1
│       │    ├───template-1.yaml
│       │    └───template-2.yaml
│       └───subtree2
│       │    ├───template-1.yaml
│       │    └───template-2.yaml
│       └───subtree3
```

**Comment by arnaudgay-cr** [comment]
Hi Niall,

Yes it works (just re tested now) in that case.

subtree1/template-2 can refere to  subtree1/template-1 with `!stack_output template-1.yaml::value` or `!stack_output myapp/subtree1/template-1.yaml::value`

subtree1/template-2 can refere to  **subtree2**/template-1 with `!stack_output myapp/subtree2/template-1.yaml::value`

If there is no path given to the **stack_output**, it takes the path of the current template (here template-2) => assuming that template-1 and template-2 are in the same folder. 

Below that, it was working like that in V1 and fully agreed that explicite declaration is better than implicite.
But in case of a big project migration from V1, that could be a nice help.
And it should be less pain in case you have to modify the structure. Adding a subtree level or rename a folder, or copy one feature from one project to another. 

```
├───config
│   └───myapp
│       └───subtree1
│       │    └───newsubtreefolder
│       │           └───template-1.yaml
│       │           └───template-2.yaml
│       └───subtree2
│       │    ├───template-1.yaml
│       │    └───template-2.yaml
│       └───subtree3
```

**Comment by ngfgrant** [comment]
Yeh ok - happy to look at a PR for this. Would need some test coverage as well.

**Comment by cornerman** [comment]
How about introducing a special starting character for relative paths like `!stack_output ./template-2.yaml`? This would make the relative path explicit and handle possible ambiguities if there was a `template-2.yaml` with the same name in the root directory.  Because then, it would not be decidable which template was meant.

**Comment by ngfgrant** [comment]
I am going to close this for now because there was a previous decision to make the path explicit to remove ambiguity.

**Comment by dlahn** [comment]
Something like this would be very helpful for us to clean up our templates.
