### ISSUE TITLE
Website migration

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#736]
Today we will be migrating the docs site to the new documentation site https://sceptre.github.io. 

There might be some disruption as the dns changes happen.

**Comment by aamirmushtaq** [comment]
I wish you guys a smooth transition. Meanwhile referring to the docs from within the repo incase anyone needs them : 
https://github.com/cloudreach/sceptre/tree/master/docs/_source/docs

**Comment by zaro0508** [comment]
sceptre.github.io is redirecting to sceptre.cloudreach.com and that site seems to be down right now. Would you be able to look into this @ngfgrant ?

**Comment by ngfgrant** [comment]
Yeh sorry about this folks will get it up ASAP.

**Comment by brent-johnson** [comment]
😌 I am about to start using this tool for a new project.  I thought there was something seriously wrong with it.  I'm glad that isn't the case.

**Comment by ngfgrant** [comment]
Ok folks I reverted some changes so https://sceptre.github.io/ should work for now and will look at why our custom domain name is not resolving properly this weekend. Apologies for the interruption!

**Comment by zaro0508** [comment]
@ngfgrant the website still seems like it's down?

**Comment by ngfgrant** [comment]
All resolved now - site is available at sceptre.cloudreach.com. If you are unable to reach the site you may need to wait until DNS resolves or clear your cache and try again.
