### ISSUE TITLE
Enable/Disable a whole stack-group

### ISSUE THREAD

**Issue by cornerman** [Sceptre/sceptre#750]
Within my stack-group I have a lot of monitoring stuff that I do not really want to deploy to my development stages. I could of course build separate stack-groups, but currently I am parameterizing the stack-group with a variable whether it is production or development. Now, I have to hand in this variable into all cloudformation stack and put a condition on all of my resources in there.

Would it be possible to disable a whole stack-group in the `config.yaml`dynamically, for example:
```yaml
region: some-region-x
enabled: {{ var.MonitoringEnabled }}
```

**Comment by mike-rsi** [comment]
I think this functionality would be useful in stack configs as well.

**Comment by zaro0508** [comment]
this has been implemented in v3.2.0 with PR #1229.  The [ignore stack config](https://docs.sceptre-project.org/3.2.0/docs/stack_config.html#ignore) will allow you to disable a whole stack
