### ISSUE TITLE
Create example sceptre projects for documentation

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#754]
# CONTEXT

When we move to our new home at github.com/sceptre we should have an "examples" repo with suggested structures etc. Useful for new comers and could even utilise in real world scenarios.

**Comment by gpinganaud** [comment]
It would be VERY usefull, please do examples. I'm looking for some api-gateway.yml (and many others).

**Comment by ngfgrant** [comment]
I now have a skeleton repo up. I guess it will populate over time. https://github.com/Sceptre/examples
