### ISSUE TITLE
Sceptre launch fails if stack is in UPDATE_IN_PROGRESS

### ISSUE THREAD

**Issue by laur1s** [Sceptre/sceptre#759]
We use Sceptre in GItlab-CI environment. Everytime code is merged stack launch command is executed:

`sceptre  --var "imageversion=${IMAGE_TAG}" launch  PROD/ecs-service -y)` 

However, If multiple commits are merged to master sceptre fails because `Stack action is already in progress state and cannot be updated`. Is this a bug or intended behavior? Is there a way to make sceptre wait until previous update is applied and then run the update again?

**Comment by ngfgrant** [comment]
Yeh that is a cloudformation thing unfortunately. I will leave this open incase we can think of a good way to handle this but it feels like it might be opening a can of worms.

**Comment by zaro0508** [comment]
cloudformation is not meant for parallel deploymenets.  you can put stacks into a stuck or bad state by using the aws cloudformation CLI.  Therefore this is a cloudformation issue and not something sceptre can fix.
