### ISSUE TITLE
AWS credentials confusion (only default profile is working) 

### ISSUE THREAD

**Issue by SohamChakraborty** [Sceptre/sceptre#766]
Hello,

I noticed that if there are multiple profiles in `~/.aws/credentials` file then sceptre commands fail with boto connection errors. After removing all the entries and keeping only one entry called `default` profile, I was able to run sceptre commands. 

Is this the normal or expected behaviour? Can we have multiple profiles in `~/.aws/credentials` file? Otherwise I have to change the credentials file every now and then during running sceptre.

**Comment by ngfgrant** [comment]
Hey @SohamChakraborty 

Sceptre will use and AWS creds set in your environment before using any profiles set in your stacks. Here is the relevant code (if you are interested) https://github.com/cloudreach/sceptre/blob/master/sceptre/connection_manager.py#L120.

I would think that there was maybe a mix up in what was available in your environment compared to what creds you think you might have been using - hence the boto connection error.

I've got multiple profiles for various AWS accounts and run no problem.

**Comment by SohamChakraborty** [comment]
I see. So I ran it like this and now it worked: 

`$ AWS_PROFILE=soham-test sceptre --debug create dev/vpc.yaml`. 

Thanks @ngfgrant

**Comment by ngfgrant** [comment]
Sure would review a PR that added some information about how sceptre connects to aws to the docs. Not sure this necessarily belongs in the README though.
