### ISSUE TITLE
Update integration tests to use vcrpy

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#770]
# CONTEXT

Our Integration tests are pretty slow - taking around 15 minutes to complete each full run. This is a pain for development and also during deployments. 

We also have another issue as in order to allow integration tests to run from contributors external to Cloudreach we would need to allow access to our sceptre test AWS account which is used during our circleci builds.

We could utilise a library like [vcr.py](https://github.com/kevin1024/vcrpy) to store the results of CloudFormation API requests and for the majority of test to be run against these during branch development. As stated in the vcr project this would give us:

- The ability to work offline
- Completely deterministic tests
- Increased test execution speed

but importantly it would also allow external contributors PRs to run the integration tests which would make life easier for the maintainers. Currently, we have to create a branch and merge the external PR into it in order to trigger the build in circleci - or of course clone it and run locally. 

# DONE WHEN

Firstly, we should evaluate whether we can indeed utilise VCR.py and if so then implement it by decorating the existing integration tests.

**Comment by 1oglop1** [comment]
What about https://github.com/localstack/localstack - would that help?

**Comment by alex-harvey-z3q** [comment]
While integration tests are still slow, it probably doesn't make sense to have this old issue still open.

**Comment by zaro0508** [comment]
This issue is related to #1432
