### ISSUE TITLE
Accessing stack_config in Hooks

### ISSUE THREAD

**Issue by YusufAzam** [Sceptre/sceptre#773]
Currently if I create a custom hook and use stack_group config I get the following error. 
object has no attribute 'stack_config'. I have noticed however that if you install setup.py for your custom hook before the use of stack_config, you can then add it to your code after the installation and do a sceptre launch. Works fine that way
 
However if stack_config is in your hook code and then setup.py is installed you will get the error.
This is problematic as I launch my code though a CICD pipeline. Is there a solution for this?

**Comment by ngfgrant** [comment]
I think this is probably because sceptre will need to be installed first (it is an install dependency for CustomResolvers).

In your case you are trying to call something from the main sceptre codebase without having sceptre installed. 

Add a step in your cicd pipeline to install sceptre into your env before installing your hook

**Comment by YusufAzam** [comment]
@ngfgrant Not the case, since I am installed sceptre before hand. Same thing will happen locally if I try and launch via the CLI using sceptre commands.

**Comment by ngfgrant** [comment]
are you pip installing your custom hook in your pipeline?

**Comment by YusufAzam** [comment]
@ngfgrant 
yes I am.  using the setup.py file for my custom hook. It seems like their a some compiled dependencies that stack_config needs that it gets by installing setup.py , before its use case.

**Comment by ngfgrant** [comment]
@YusufAzam are you executing `pip install ...` or `python setup.py install` and can you please share the `setup.py` of your CustomHook?

**Comment by YusufAzam** [comment]
@ngfgrant 
from __future__ import print_function
import os
import sys
from setuptools import setup, find_packages

setup(
    name='example',
    py_modules=['s3_creation_hook'],
    entry_points={
        'sceptre.hooks': [
            's3_creation_hook = s3_creation_hook:CreateFileHook',
        ],
    }
)
