### ISSUE TITLE
Add `sceptre logs` command

### ISSUE THREAD

**Issue by ngfgrant** [Sceptre/sceptre#781]
# CONTEXT

It maybe useful to get the logs from a CloudFormation stack. We _should_ be able to get these without too much drama. 

Depending on how the logs are returned by AWS we could parse them into a consumable standard format. 

Would welcome feedback on the idea and this needs a bit of discussion.

**Comment by dboitnot** [comment]
I could see some use in this. Here are some thoughts:

- By default it shows the last `n` logs from the stack
- A `tail -f` style option to poll logs continuously
- Monitor multiple stacks simultaneously

**Comment by alex-harvey-z3q** [comment]
I can't see us doing this unless someone wants to reopen and send in a PR.
