### ISSUE TITLE
Execution of a stack group slows down when migrating from sceptre v1 to v2

### ISSUE THREAD

**Issue by heinrichbernd** [Sceptre/sceptre#789]
When migrating from sceptre 1 to sceptre 2 the order of executing stacks changes.
Suppose the following stack dependencies:

```
sgroup
- s1
- s2
  - s21
    - s211
  - s22

```  
In sceptre 2 a breadth first strategy is used which results in the following order:

1. s1, s2
2. s21, s22
3. s211

In sceptre 1 the execution of s211 starts immediately after s21 is finished and it doesn't wait until s22 is finished like in sceptre 2.
So the execution strategy in sceptre 1 allows an overall faster execution of a stack group like sceptre 2.

I suggest to switch to the more condensed execution strategy as in sceptre 1.

**Comment by ngfgrant** [comment]
Version 1 did not handle dependencies strictly and we as users were able to get away with a quite a bit until there was a problem and it became pretty difficult to debug. 

V2 batches up and executes stacks with the correct and safe level of concurrency to ensure dependent stacks are always executed first.

Every batch (set) contains stacks that are not dependent on each other and creates a thread for each to execute on. The 2nd batch will have dependencies on the first batch. So the stacks in a batch are not related and execute concurrently and each of the batches execute serially.

So it’s not so much breadth first as it is just executing stacks in the most correct order. The ordering comes from the DAG(StackGraph) creates in ScetrePlan. 

Hope that makes some sense? Ultimately, we’re not going to go back to the old execution model.

It might be worth looking at your project and seeing if the dependencies between stacks is really always nexeaaary.
