### ISSUE TITLE
stack_output throws "Template format error: YAML not well-formed"

### ISSUE THREAD

**Issue by fuxjezz** [Sceptre/sceptre#794]
Hi,

Just getting started with sceptre so I might just be attempting something the wrong way.

I've got 2 stacks and I want to reference one of the outputs of the first one.

Got this defined in my yaml template:

<pre>
sceptre_user_data:
  SubnetId: !stack_output vpc/vpc-multiple-az.yaml::PrivateSubnetA
</pre>

but running the "sceptre create" command throws an error :

<pre>
sceptre create ec2/single-ec2-instance-simple.yaml

stuff snipped

"An error occurred (ValidationError) when calling the CreateStack operation: Template format error: YAML not well-formed. (line 19, column 13)"
</pre>

The line exactly corresponds to my !stack_output attempt.

The resource from the "first" stack is listed correctly when running:

<pre>
sceptre list resources vpc/vpc-multiple-az.yaml

stuff snipped 

{
      "LogicalResourceId": "PrivateSubnetA",                                                
      "PhysicalResourceId": "subnet-XXXXXX"                                      
},

</pre>

I'm using sceptre 2.1.5 . Could somebody point out what I'm doing wrong?

Any help appreciated!

Kind regards,

Ruben

**Comment by ngfgrant** [comment]
Hey @fuxjezz welcome!

Can you show me the output of `vpc/vpc-multiple-az.yaml` it looks like it is probably a formatting error. maybe worth running the output through a online yaml formatter to see what is up unless you have a linter in your environment?

**Comment by fuxjezz** [comment]
Hi,

The file is in 

https://github.com/fuxjezz/some_stuff/blob/master/vpc-multiple-az.yaml
(i've added the second one to the same repository as well)

Found it somewhere online and it does build using sceptre.

I did not try pasting the contents of the file that correctly builds into an online parser yet, tnx for that suggestion.

It throws a similar exception (constructor cannot be determined) as the second one (which does _not_ get built by sceptre):

<pre>
ERROR:

could not determine a constructor for the tag '!Not'
  in "<unicode string>", line 66, column 17:
      BuildPublicB: !Not [ !Equals [ !Ref NumberOfAZ ... 
</pre>

Since the online parsers are not fitted with the Cloudformation or Sceptre constructors i'm not terribly surprised by the "errors" :(

Kind regards,

Ruben

**Comment by ngfgrant** [comment]
https://github.com/fuxjezz/some_stuff/blob/master/single-ec2-instance-simple.yaml#L19 - you can't use sceptre_user_data resolver in your templates

**Comment by fuxjezz** [comment]
Ah ok. That explains.

TnX
