### ISSUE TITLE
Documentation for upgrade from V1 to V2

### ISSUE THREAD

**Issue by bl-mklein** [Sceptre/sceptre#797]
Hello!

Is there still any documentation describing the upgrade process from Sceptre V1 to V2?

The README refers to a wiki page with the process, but the link is broken and redirects back to the repo page.

Thanks in advance!

**Comment by ngfgrant** [comment]
Apologies - I've now fixed the link that got broken during the move across to the new org. Here is the wiki https://github.com/sceptre/project/wiki/Migration-Guide:-V1-to-V2

**Comment by bl-mklein** [comment]
Thanks for the quick reply @ngfgrant !
Have a nice day!
