### ISSUE TITLE
Recommended method of handling linting

### ISSUE THREAD

**Issue by priorax** [Sceptre/sceptre#800]
Asking here mostly because I'm unsure where else to put this (sorry if it's the wrong place).

I'm looking at building sceptre into my CI/CD pipeline and was wanting to integrate it with tools like cfn-nag (to check for any obvious governance issues) and cfn-lint (to check for basic syntax issues) as a test step prior to running anything since I've had issues caught by these tools that were not caught by the validation API.

My current working environment has the following stack groups (for the sake of example)
  - dev
  - staging
  - prod
  - shared
Shared is things that dev/staging share (such as monitoring Lambda's)

I tried just running `sceptre generate dev` and it put each of my 10 templates in one stdout so I can't easily just do `sceptre generate dev > /tmp/dev.template && cfn-lint /tmp/dev.template` . Since there is some jinja in use, I cannot easily just run each of the files in the templates folder through the linter and I do need to test the compiled jinja

The best method I can find is by running `sceptre list resources ${env}` for each of the stack groups, parsing the output into a single file and then de-duping shared resources and then looping through these files to generate the finalized template for each resource and then finally running that through the linter, just was wondering if there was anyone doing similar already and if there was any feedback you could offer

**Comment by zaro0508** [comment]
We have something like this setup in our CI/CD pipeline.  We are using travis-ci[1] as the CI engine, and pre-commit[2] as our linter framework to do all the linting.  you can checkout our .pre-commit-config.yaml[3] to see the linters we've setup for our project.   The linter runs on every commit (before a PR) and then runs again by our CI when a PR occurs.  As for testing we also setup taskcat to run cloudformation integration tests in our main repo where we have shared templates.

[1] https://travis-ci.org/
[2] https://pre-commit.com/
[3] https://github.com/Sage-Bionetworks/sandbox-provisioner/blob/master/.pre-commit-config.yaml
