### ISSUE TITLE
Custom resolver failing on Sceptre V2

### ISSUE THREAD

**Issue by bl-mklein** [Sceptre/sceptre#805]
Hello!

First of all, thanks for all the effort on this project. Has been helping our team massively 🥇 

We're in a process of migrating from Sceptre V1 to V2 and everything works, except a custom resolver we have.

I'm following the process described in the [migration guide](https://github.com/sceptre/project/wiki/Migration-Guide:-V1-to-V2#custom-hooks-and-resolvers), so my current setup is the following:

_resolvers/kms_decrypt.py:_
```python
from sceptre.resolvers import Resolver
import base64

class KMSDecrypt(Resolver):
    def __init__(self, *args, **kwargs):
        super(KMSDecrypt, self).__init__(*args, **kwargs)

    def resolve(self):
        # [Our internal logic here]
        return self.argument
```

_resolvers/setup.py:_
```python
from setuptools import setup

setup(
    name='kms-decrypt',
    version="1.0.0",
    py_modules=['kms_decrypt'],
    entry_points={
        'sceptre.resolvers': [
            'kms = kms_decrypt:KMSDecrypt',
        ],
    }
)
```

The module is successfully installed using `pip3 install resolvers/`.

However, when using the resolver in a template:

```yaml
clientSecret: !kms AAAAABBBBBBCCCCCDDDDEEEE
```

We always get the same error:
```bash
"'dict object' has no attribute 'instance_class'"
```

- Sceptre, version 2.1.5
- pip 19.1.1
- Python 3.6.8

My knowledge in Python isn't extensive, but I did extensive research about Pip packaging and seems to be correct.

Am I missing something?

Thanks in advance for any support!

**Comment by ngfgrant** [comment]
Hey @bl-mklein 

Could you try use the resolver template (you'll need to edit `setup.py`) to see if the problem persists. 

Also could you share a snippet of a stack that uses the resolver and a `tree` of your project structure or at least the resolver folder?

**Comment by bl-mklein** [comment]
Thanks @ngfgrant !

I just re-created the module using resolver template (https://github.com/bl-mklein/kms-decrypt) but when installing the module and using on my templates, I got the same error.

Maybe worth mention that I'm running Sceptre on Docker (v2.1.5):

```bash
docker run -it --rm \
   -v "$PWD":/project:rw \
   -v ~/.aws:/root/.aws:ro \
   --entrypoint /bin/bash \
   cloudreach/sceptre:2.1.5
```

Thanks!

**Comment by bl-mklein** [comment]
Here's an example of a template using this data (read data omitted):

```yaml
template_path: rds-postgres.yaml
parameters:
  DBName: mydb
  DBSubnetGroup: vpc-foobar
  VPCSecurityGroups: sg-xxxxxxxx
  User: foobar
  StorageType: standard
  AllocatedStorage: '5'
  Password: !kms MYKMSENCRYPTEDKEY==
```

**Comment by 1oglop1** [comment]
@bl-mklein It could potentially be a name of the class, IRRC there is a simple code which turns `PascalCase` into `dash-case`. So when your input is `KMSDecrypt` it gets messed up into `kmsdecrypt` or similar. so you should rename the class to `KmsDecrypt`.

**Comment by bl-mklein** [comment]
Thanks @1oglop1 

Considering the most updated example, using resolver template ([here](https://github.com/bl-mklein/kms-decrypt)), I followed your suggestion and renamed the class from `KMS` to `Kms` + necessary adjustments on `setup.py`, but the problem persists :/

**Comment by ngfgrant** [comment]
@bl-mklein Can you `pip list please?` also any changes you make in your resolver require another `pip install`

**Comment by bl-mklein** [comment]
Hello!

Here's the Pip list:
```
Package         Version
--------------- --------
boto3           1.9.179
botocore        1.12.179
Click           7.0
colorama        0.3.9
decorator       4.4.0
docutils        0.14
Jinja2          2.10.1
jmespath        0.9.4
kms-decrypt     1.0.0
MarkupSafe      1.1.1
networkx        2.1
packaging       16.8
pip             19.1.1
pyparsing       2.4.0
python-dateutil 2.8.0
PyYAML          5.1.1
s3transfer      0.2.1
sceptre         2.1.5
setuptools      41.0.1
six             1.12.0
urllib3         1.25.3
wheel           0.33.3
```

And yes, after changing the class name or `setup.py` configuration I always run `pip3 install resolvers/kms-decrypt/`

**Comment by ngfgrant** [comment]
Ok it might be something in your code - could you share the resolver?

**Comment by bl-mklein** [comment]
I'm using the resolver template you suggested before.
You can find it [here](https://github.com/bl-mklein/kms-decrypt).
But the resolver has no logic, just default one.
So I suppose it's something on the `setup.py`

**Comment by ngfgrant** [comment]
It is probably not going to be the template (we've got all the core resolvers working based off the template in our org). 

Going back to the original error it was `"'dict object' has no attribute 'instance_class'"`. Is there anywhere else you are using the attribute `instance_class`? if so then it is not accessible as you are trying to access it.

If you uninstall the custom resolver and try and run it does the same error persist?

**Comment by bl-mklein** [comment]
@ngfgrant you found the problem.

I just found this template:

```yaml
template_path: restore-rds-from-snapshot.yaml
parameters:
  InstanceClass: {{ var.instance_class }}
  DbIdentifier: {{ var.db_identifier }}
  DbSnapshot: {{ var.db_snapshot }}
  SubnetGroup: {{ var.subnet_group }}
  ParameterGroup: {{ var.parameter_group }}
  SecurityGroups: {{ var.security_groups }}
```

Deleting this template the errors stops, so the problem is actually in the template, not the resolver.
I'm so sorry for this :/

I'll check the migration docs and see how adjust these `var` for the V2 format.

Thanks a lot for your attention and support! 🙇
