### ISSUE TITLE
Support Instance Profiles credentials

### ISSUE THREAD

**Issue by rdpa** [Sceptre/sceptre#822]
As it stands, Sceptre implements it's own version of the AWS credentials chain, which only allows specifying either a profile or credentials [1]. Our CI pipeline relies on using Instance Profiles, which is preventing us from using Sceptre.

Boto3 provides a method to traverse the default credential chain [2]. Sceptre should use this. If `profile` and/or `region` are set in the config files then sceptre can override the config to retain compatibility.

1: https://github.com/Sceptre/sceptre/blob/master/sceptre/connection_manager.py#L111-L169
2: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html

**Comment by jeffmacdonald** [comment]
I can think of where this could be bad, if I was testing on my own machine, forgot to explicitly set a profile name and ran sceptre. It could cause me to build / delete infrastructure on an unintended AWS Account.

However, i do find the error handling of "not having a profile set" to be a bit annoying. Must be a middle ground somewhere.
