### ISSUE TITLE
Strings starting with 0 are identified as Octal in Sceptre User data

### ISSUE THREAD

**Issue by laur1s** [Sceptre/sceptre#823]
Hi,

It seems that Sceptre somehow interprets  variables starting with 0 as octal and converts them to decimal. This is a an Issue because we have user names that start with 0. Here is the example 
Sceptre Config file:
```
sceptre_user_data:
  env:
    user: {{ var.user }}
```
`sceptre --var "user=03303560" launch TEST/s3    `  
When I execute this the value in the deployed cloudformation template becomes 886640.

Is it possible to do something about this?
Thanks!

**Comment by 1oglop1** [comment]
Hi, this is probably due to how YAML works.

(more info: https://stackoverflow.com/questions/54820256/how-to-read-load-yaml-parameters-with-leading-zeros-as-a-string)

I'd suggest to treat these numbers as strings 'user="03303560"' unless you really need it to be an integer starting with zero.
