### ISSUE TITLE
No stacks detected from the given path [] Valid stack paths are []

### ISSUE THREAD

**Issue by githubnoobieme** [Sceptre/sceptre#824]
Hello guys,

Iam pretty new to sceptre, I have some starting troubles. When I try to launch my stacks from my CI pipeline on gitlab, I get following Error message.

```
$ sceptre launch -y dev
"**No stacks detected from the given path 'dev'. Valid stack paths are: ['dev/public-private-vpc.yml', 'dev/private-subnet-private-loadbalancer.yml']"
ERROR: Job failed: exit code 1**
```
I also tried to name the as valid declared paths, same error.

I followed all the Guidelines and my structure looks like this 
```
.
└── config
      ├── config.yaml
      └── dev
            └── public-private-vpc.yml                
            └── private-subnet-private-loadbalancer.yml
└── templates
            └── public-private-vpc.yml                
            └── private-subnet-private-loadbalancer.yml
```

Is there a Problem in the version or did I missconfigure something?

**Comment by ngfgrant** [comment]
Hey @githubnoobieme welcome - thanks for trying sceptre and happy to help.

As a starter can you rename your files to use the `.yaml` extension rather than `yml`? It might be as easy as that....

**Comment by githubnoobieme** [comment]
Oh wow thanks for the superfast answer 👍 

Well that helped a bit :) but now I got a bunch of new errors, not sure but are this dependency errors? Did I missed something to install?

`$ sceptre --version
Sceptre, version 2.2.1
$ sceptre launch -y dev
Traceback (most recent call last):
  File "/usr/local/bin/sceptre", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sceptre/cli/helpers.py", line 36, in decorated
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sceptre/cli/launch.py", line 35, in launch_command
    plan = SceptrePlan(context)
  File "/usr/local/lib/python3.6/dist-packages/sceptre/plan/plan.py", line 34, in __init__
    all_stacks, command_stacks = config_reader.construct_stacks()
  File "/usr/local/lib/python3.6/dist-packages/sceptre/config/reader.py", line 227, in construct_stacks
    for dep in stack.dependencies
  File "/usr/local/lib/python3.6/dist-packages/sceptre/config/reader.py", line 227, in <listcomp>
    for dep in stack.dependencies
KeyError: 'public-private-vpc'
ERROR: Job failed: exit code 1`

**Comment by ngfgrant** [comment]
So in this case it is throwing a `KeyError` which is a Python error for when a key in a dict does exist and is called.

What you are really experiencing is some not very useful error messages from sceptre. We should have probably caught this and reported something nicer. 

Is it possible to see the contents of `public-private-vpc.yaml`?

**Comment by githubnoobieme** [comment]
yes sure its just refering to my cloudformation template

`template_path: public-private-vpc.yml
parameters:
  PublicOne: 10.9.0.0/24
`

**Comment by ngfgrant** [comment]
Ok thanks can I see the output of private-subnet-private-loadbalancer.yaml and config.yaml?

**Comment by githubnoobieme** [comment]
Thats the output of private-subnet-private-loadbalancer.yaml 
```

template_path: private-subnet-private-loadbalancer.yml
parameters:
  StackName: dev-fargate
dependencies:
  - public-private-vpc
```

and this is the output of config.yaml

```
project_code: dev-fargate
region: eu-central-1
```

**Comment by ngfgrant** [comment]
In 

private-subnet-private-loadbalancer.yaml:

Specify the dependency with the stack group:

...
dependencies:
    - dev/public-private-vpc

**Comment by githubnoobieme** [comment]
Yeah that helped, now its deploying
```

$ sceptre launch -y dev
[2019-09-16 11:42:35] - dev/public-private-fargate - Launching Stack
[2019-09-16 11:42:35] - dev/public-private-fargate - Stack is in the PENDING state
[2019-09-16 11:42:35] - dev/public-private-fargate - Creating Stack
```

Thank you very much!!!

BTW is there a better documentation as on https://sceptre.cloudreach.com/2.2.1/ ? Because it looks like there is a some commands that are not existing anymore for example "launch-env" now "launch"?

**Comment by ngfgrant** [comment]
@githubnoobieme version 1 documentation can be found at https://github.com/Sceptre/sceptre/tree/v1/docs/docs. You are using v2 though, so these docs are at https://sceptre.cloudreach.com/2.2.1

`launch-env` and similar were v1 commands.

Hope that helps, going to resolve this issue, anything else just let us know!

**Comment by anshul0915** [comment]
How you change config for multi environment project and need to deploy with ci cd
