### ISSUE TITLE
Feature request: ability to produce raw generated file from .j2 templates

### ISSUE THREAD

**Issue by 1oglop1** [Sceptre/sceptre#838]
### Current situation

At the moment `sceptre generate` or `sceptre validate` is trying to process templates and generate desired output `json/yaml`.
Steps:

1. Take `template.yaml.j2`
2. Render internally (https://github.com/Sceptre/sceptre/blob/master/sceptre/template.py#L118)
3. Parse rendered template into desired format json/yaml
4. Produce result

This makes debugging difficult if there are loops and other macros used inside template and rendered result is not valid json/yaml.

example:

`template.yaml.j2`
```
{% for num in range(5) %} 
Key: Value{{ loop.index0 }} 
{% endfor %}

OtherKey: [ !Ref {% for num in range(5) %} Value{{ loop.index0 }}, {% endfor %} ]]
```

Is supposed to produce:
```
Key: Value0 
Key: Value1 
Key: Value2 
Key: Value3 
Key: Value4

OtherKey: [ !Ref  Value0,  Value1,  Value2,  Value3,  Value4,  ]]
```
However due to `yaml` syntax error in `OtherKey` `]]` Sceptre outputs only
```
"An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: YAML not well-formed. (line 7, column 65)"
```

But real error is on line `(line 5, column 82)` it would be helpful if `generate/validate` command could produce intermediate step and keep rendered templates.

### Suggestion:

Add switch to `generate/validate` or other template commands which would preserve rendered files.
E.g. `sceptre generate --raw-render stack.yaml ` would result into
```
Key: Value0 
Key: Value1 
Key: Value2 
Key: Value3 
Key: Value4

OtherKey: [ !Ref  Value0,  Value1,  Value2,  Value3,  Value4,  ]]
```
Which can be easily piped into a `file.yaml` and debugged.

Or switch `--keep-raw-renders` would produce multiple raw rendered files next to it's stacks.

Given input
```
group/stack1.yaml
group/stack2.yaml
templates/template.yaml
```

`sceptre generate --keep-raw-renders group` would result in

```
group/stack1.yaml
group/stack1.raw.yaml <--- this contains rendered values from stack config and template
group/stack2.yaml
group/stack2.raw.yaml

templates/template.yaml
```

**Comment by craighurley** [comment]
Related PR: https://github.com/Sceptre/sceptre/pull/832

**Comment by 1oglop1** [comment]
@craighurley Shall I close this one?

PS did anyone introduce `__main__.py` in PR already, like I did here?
https://github.com/Sceptre/sceptre/blob/add-debugger/sceptre/__main__.py

**Comment by zaro0508** [comment]
i think we can probably close this issue, correct @ngfgrant ?
