### ISSUE TITLE
Support for lambda with node 10 

### ISSUE THREAD

**Issue by s50600822** [Sceptre/sceptre#859]
<img width="1666" alt="Screen Shot 2019-10-18 at 12 23 56 am" src="https://user-images.githubusercontent.com/5586453/67013174-6e29a480-f13e-11e9-9e5f-239a9716fcbb.png">
This happens when I used 
```
      Runtime: nodejs10.x
...
      Code:
        ZipFile: |
...
```
Also is there a built in way to include code from a js file instead ?

**Comment by zaro0508** [comment]
I believe the error indicates that cloudformation does not support nodejs10.x yet.  When AWS supports a new lambda runtime they need to also make it available in cloudformation.  I think the support is just lagging.

**Comment by ngfgrant** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=908801
