### ISSUE TITLE
"stack" attribute of Resolver class never gets set

### ISSUE THREAD

**Issue by robertsigler** [Sceptre/sceptre#865]
I have a custom resolver which I wrote and used with Sceptre 1.X. The resolver relies on being able to retrieve information about the stack that the resolver appears in the config for. Therefore, I used the `stack_config` attribute which was available on the base Resolver class.

Then I started migrating to Sceptre 2.X. I found that, instead of `stack_config`, the Resolver class has a `stack` attribute (https://github.com/Sceptre/sceptre/blob/6cef58b0d729437ad6de8e9abdb619e24fd1191f/sceptre/resolvers/__init__.py#L32) but it doesn't appear to get initialized with any value--it appears to always be `None`.

I traced through the commit history and it looks like it used to get initialized with a value until this commit (https://github.com/Sceptre/sceptre/commit/b954bd952745f0360eee8d25b2c24fdb2228b28e) which broke that behavior.

It looks like partial functions and a final pass used to be required to initialize resolvers with a reference to their stack object (https://github.com/Sceptre/sceptre/blob/9f97d1e26a7c46bf105109c3478f38db843e3dab/sceptre/config_reader.py#L286), but that was removed to simplify config reading. Was this (resolvers no longer have access to a reference to the stack they are defined in) an intended consequence of this change or an unintended bug?

The issue can be reproduced with this project--the `stack_output` resolvers found in this project will have their `self.stack` attribute set to `None`.
[repro.zip](https://github.com/Sceptre/sceptre/files/3852318/repro.zip)

**Comment by zaro0508** [comment]
Is this the same as #760 ?

**Comment by robertsigler** [comment]
Not exactly, although I think they are related.

What I am specifically reporting is a regression where, in the past, you used to be able to see all kinds of information about the stack that your resolver is declared in, even if you don't pass any arguments into your resolver.

What that issue seems to be is a feature request where you could access stack config _inside_ your stack config, which could be used to pass information into your resolver via arguments. I see how they're related but I'd have to change all of my resolvers and the stack configs that use them in order to leverage #760 .

**Comment by zaro0508** [comment]
Well, sceptre V2 is not backwards compatible with V1.  That's why there's a migration guide, https://github.com/sceptre/project/wiki/Migration-Guide:-V1-to-V2   Issue #760 is probably the thing you want to bridge that gap.

**Comment by robertsigler** [comment]
I think I have a better handle on this issue now.

The problem was not that the "stack" attribute never gets set--the problem is that it used to get set in the constructor, but now it gets set as part of the __set__ method (https://github.com/Sceptre/sceptre/blob/master/sceptre/resolvers/__init__.py#L99). Users like myself who referred to the 'stack' argument within the constructor ran into issues. We can fix these issues by moving all logic that depends on having access to the 'stack' object into the `resolve` method.

Thanks for your patience. Closing this issue now.
