### ISSUE TITLE
Uploading files to S3 (without zipping them)

### ISSUE THREAD

**Issue by Dennissie1981** [Sceptre/sceptre#866]
Hey, 

How can I upload files to S3? 
Don't want to zip them like the s3-packager does...
I need to upload templates to s3 so I can reference them from my Service Catalog Products

I tried this in the config: 
```hooks:
  # This step uploads the gitlab-runner template to s3
  before_create: &create_hooks
    - !cmd 'BUCKET=$(aws cloudformation list-exports --no-paginate | jq -r ".Exports[] | select(.Name | contains(\"MyBucketName\")) | .Value")'
    - !cmd 'aws s3 sync catalog-templates s3://$BUCKET/catalog-templates'
  before_update: *create_hooks
```
It gives this error: 
`subprocess.CalledProcessError: Command 'BUCKET=$(aws cloudformation list-exports --no-paginate | jq -r ".Exports[] | select(.Name | contains(\"MyBucketName\")) | .Value")' returned non-zero exit status 255.`

Also tried this: 

```hooks:
  # This step uploads the gitlab-runner template to s3
  before_create: &create_hooks
    - !cmd 'aws s3 sync catalog-templates s3://{{!stack_output guardrails/config-recorder.yaml::oConfigBucketName}}/catalog-templates'
  before_update: *create_hooks
```

and some variants, which don't work either. 

I can't set the bucketname hardcoded as it's created as part of the stack group. It includes the account number, so it can't be set beforehand as some config parameter.

Any idea? Thanks!

**Comment by zaro0508** [comment]
set the `template_bucket_name` and sceptre will automatically upload your CFN templates to that bucket before deploying them. 
 https://sceptre.cloudreach.com/2.2.1/docs/stack_group_config.html#template_bucket_name

**Comment by brentbain** [comment]
@zaro0508 - how about nested cloudformation stacks? I've run into this recently where I need to find a way to upload a nested stack, with sceptre calling/deploying the parent stack.

**Comment by zaro0508** [comment]
you probably need a libraries repo that contains a library of templates with CI setup to upload those to an S3 bucket as dependencies of your main cloudformation template.  you can upload them with a scrip like one we use, https://github.com/Sage-Bionetworks/aws-infra/blob/master/deploy-templates.sh
