### ISSUE TITLE
protect: true

### ISSUE THREAD

**Issue by SpyderDave** [Sceptre/sceptre#872]
I am attempting to use sceptre to deploy a stack and then set stack protection on it.

In the past, with older versions of sceptre, I could use an after_create hook to set stack termination on a stack after it's been initially deployed.

V 2.2.1 of sceptre appears to support adding "protect: true" to a StackConfig however I am a little unclear how this is to be used.  If I add this to a stack config, sceptre fails to even initially create the stack.

**Comment by ngfgrant** [comment]
Hey @SmoothGlide are you able to provide the error that occurs when trying to use protect: true when creating a stack?

**Comment by zaro0508** [comment]
closing due to lack of response from reporter
