### ISSUE TITLE
When is the new release planned?

### ISSUE THREAD

**Issue by 1oglop1** [Sceptre/sceptre#875]
Hi,
When is the next release planned, it was already quite some time since the last one?

 + there is a missing information about usage of iam_role 
which is now implemented here: https://github.com/Sceptre/sceptre/blob/master/sceptre/resolvers/stack_output.py#L173

Is stack_output_external parameter as optional? (I received some error, but I lost the stacktrace, and it somehow started to work as expected)
https://github.com/Sceptre/sceptre/blob/master/docs/_source/docs/resolvers.rst#stack_output_external

**Comment by ngfgrant** [comment]
Hey @1oglop1 

I guess we can release at anytime and like you said there is probably enough in the master branch to justify a tag and release. Will do that today.

We re-added support for IAM role https://github.com/Sceptre/sceptre/commit/e8f92d2f777572de2555fad38132fb2dd6f0980c

Re the other point not sure... guess would need to see the stacktrace

**Comment by 1oglop1** [comment]
Thanks for the release!

@ngfgrant For some reason it fixed itself. It looks more like an anomaly and coincidence of multiple factors.
