### ISSUE TITLE
How to pass the stackname of some stack as input parameter to another?

### ISSUE THREAD

**Issue by schlichtanders** [Sceptre/sceptre#884]
Hi all,

with `!stack_output` I can refer to outputs of a stack, however how can I refer to the full stackname itself?

Let's say we have defined some stack in `MyStackGroup/some_stack_sceptre_config.yaml` which we want to refer to in another stack `MyStackGroup/another_stack_sceptre_config.yaml` like follows
```yaml
parameters:
   StackNameOfSomeStack: !stack_name MyStackGroup/some_stack_sceptre_config.yaml
```

I couldn't find a way todo it nicely with sceptre. My current workaround is to create a dummy output parameter ``StackName`` which returns the stackname, and then use `!stack_output MyStackGroup/some_stack_sceptre_config.yaml::StackName`

is there a better way to do it?

**Comment by craighurley** [comment]
I use the latter.  In many cases for me, the same cfn template is used by multiple stack configs so their stack names will be different.  In the template I have the following output:

```
Outputs:
  StackName:
    Value: !Sub '${AWS::StackName}'
```

... and if I want to reference it, I do exactly like you have proposed with `!stack_output`.
