### ISSUE TITLE
role_arn with External ID 

### ISSUE THREAD

**Issue by SpyderDave** [Sceptre/sceptre#892]
I have a need to use a role for cross account usage which includes the requirement to pass an ExternalId as documented https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

**Comment by ngfgrant** [comment]
Hey @SpyderDave can you elaborate a bit on what the ask is and the problem you are facing?

**Comment by craighurley** [comment]
Setting an external ID for a role used by a third party helps reduce the risk of the _The Confused Deputy Problem_.

There may be cases where people want to use sceptre with a role configured with an external ID to deploy CloudFormation.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-servicerole.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

**Comment by SpyderDave** [comment]
What @craighurley said :)

**Comment by nabeelamjad** [comment]
Hi @SpyderDave  / @craighurley 

Under #799 I did not add support for passing an external ID primarily as it wasn't possible in V1 either. (this is also mentioned in the PR back then). This functionality would need to be built in, you may still be able to use an AWS config (the config then contains the external_id) but I don't remember exactly how on the top of my head, you could have a look at #395 to see how this might be done.

**Comment by zaro0508** [comment]
@SpyderDave setting up `external_id` in the AWS config file is documented here: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by SpyderDave** [comment]
The AWS CLI is one way to do it, but if it's sceptre which is assuming the role, CLI credentials do not come into play so an external_id cannot be used.
