### ISSUE TITLE
Drop support for Python 2.x

### ISSUE THREAD

**Issue by mbeacom** [Sceptre/sceptre#893]
Python 2.x is now end of life and will no longer receive updates.

I propose we drop support in subsequent releases by introducing a deprecation notice, followed by deprecation.

Some additional references in favor of this change:

- [Python Clock - Lapsed](https://pythonclock.org/)
- [Python 3 Statement](https://python3statement.org/)
- [Pandas drops Python 2 support - July 2019](https://pandas.pydata.org/#v0-25-0-final-july-18-2019)
- [NumPy drops Python 2 support - Proposed January 2019](https://numpy.org/neps/nep-0014-dropping-python2.7-proposal.html)
- [Pytest drops Python 2 support](https://pytest.readthedocs.io/en/latest/py27-py34-deprecation.html)
- [PEP-373 - 2.7 Lifecycle](https://www.python.org/dev/peps/pep-0373/)

**Comment by ngfgrant** [comment]
That is the plan. Python 2 will not be supported in our next major release (v3).
