### ISSUE TITLE
Implement package management and accommodate PEP-517/518

### ISSUE THREAD

**Issue by mbeacom** [Sceptre/sceptre#894]
# Package Management / Modernization

## Context

Currently, sceptre is using the setup.py, setup.cfg, and dev/prod requirements.txt files to handle sceptre packaging, dependencies, and publishing.

[PEP-517](https://www.python.org/dev/peps/pep-0517/)
[PEP-518](https://www.python.org/dev/peps/pep-0518/)
[PEP 517 and 518 in Plain English](https://medium.com/@grassfedcode/pep-517-and-518-in-plain-english-47208ca8b7a6)

## Possible Fix

Migrate to use [Poetry](https://github.com/python-poetry/poetry), removing setup.py and MANIFEST.in in favor of the new pyproject.toml standard.

**Comment by ngfgrant** [comment]
I’m not against this but I don’t see it as an immediate priority. Ideally, we’d just use whatever is provided by core python with an additional dependency.

**Comment by zaro0508** [comment]
i believe @tarkatronic is doing this work in PR #1035
