### ISSUE TITLE
[Resolved] Stack_tags String value converted to boolean

### ISSUE THREAD

**Issue by churtado-edrans** [Sceptre/sceptre#903]
Hi all,
I am globally implementing the use of some tasks, and I have found that when generating this tag.

```
stack_tags:
   mytag: {{ config.value }}

config.yaml
 value=no
```

In stack deployed in AWS appear.

`mytag: False`

some way to literally interpret the value as boolean but as a string?

**Comment by hreeder** [comment]
If I remember correctly, this is down to how the YAML parser works.

Try wrapping it in quotes like so:
```yaml
stack_tags:
  mytag: "{{ config.value }}"
```

and see if that helps.

**Comment by churtado-edrans** [comment]
I tried with quotes and i've the same result.

`mytag: False`

**Comment by churtado-edrans** [comment]
we've found the solution. 
For this it's necessary pass the following parameter to get value as string.

```
stack_tags:
   mytag: {{ config.value }}

config.yaml
 value = **"!!str NO"**
```
