### ISSUE TITLE
config files included with {% include %} does not format correctly

### ISSUE THREAD

**Issue by heikkima** [Sceptre/sceptre#905]
Scpetre version: `Sceptre, version 2.3.0`
Issue: `{{ stack_group_config }}` does not format correctly when included with `{% include %}`

Demo: 
```
.
├── config
│   ├── config.yaml
│   └── dev
│       ├── config-templates
│       │   └── tags.yml
│       ├── config.yaml
│       └── s3.yaml
└── templates
    └── cf-s3.yaml.j2
```

We have shared config files in `config-templates/` directory and we use these config files with `{% include %}` in stack's main config -file.

In this demo our stack's main config -files path is `./config/dev/s3.yaml`
```
# ./config/dev/s3.yaml

template_path: cf-s3.yaml.j2

parameters:
  BucketName: {{ stack_group_config.s3_bucket_name }}-{{ stack_group_config.environment }}

{% include 'config-templates/tags.yml' %}
```
```
# ./config/dev/config-templates/tags.yml

sceptre_user_data:
  {% if stack_group_config.variables[stack_group_config.environment].tags is defined %}
  tagKeyPairs:
    {{ stack_group_config.variables[stack_group_config.environment].tags }}
  {% endif %}
```
The included `tags.yml`-file reads values from our `./config/config.yaml` and passes the data to the template under `sceptre_user_data` variable key `tagKeyPairs`.
```
# ./config/config.yaml

project_code: 'sceptre-demo'
region: 'eu-west-1'

s3_bucket_name: sceptre-demo-bucket-name

variables:
  dev:
    tags:
      FOO: 'barDev'
      BAZ: 'bazDev'
      BAR: 'fooDev'
```
Running command `sceptre status dev` will throw the following error:
```
expected alphabetic or numeric character, but found '#'
  in "<unicode string>", line 9, column 7:
        {&#39;FOO&#39;: &#39;barDev&#39;,  ... 
          ^
```

But if we move the content from `./config/dev/config-templates/tags.yml` to our stack's main config file `./config/dev/s3.yaml`, like this:
```
# ./config/dev/s3.yaml

template_path: cf-s3.yaml.j2

parameters:
  BucketName: {{ stack_group_config.s3_bucket_name }}-{{ stack_group_config.environment }}

sceptre_user_data:
  {% if stack_group_config.variables[stack_group_config.environment].tags is defined %}
  tagKeyPairs:
    {{ stack_group_config.variables[stack_group_config.environment].tags }}
  {% endif %}
```
Running command `sceptre status dev` again will not throw an error.

This setup was also tested with `Sceptre, version 2.2.1` and it worked fine with `{% include %}`

**Comment by ngfgrant** [comment]
Just as a quick elimination thing - can you change `tags.yml` to `tags.yaml` and try again? There was a Jinja vulnerability which we patched between sceptre 2.2.1 and 2.3.0 so that might be something we need to look at as well.

**Comment by heikkima** [comment]
Changing `tags.yml` to `tags.yaml` result in different error:
```
"Required attribute 'template_path' not found in configuration of 'dev/config-templates/tags'."
```

**Comment by ngfgrant** [comment]
Ok that second error makes sense - I see that you are making use of the fact we don't use `.yml` extension and importing that. This is very likely to be a Jinja thing.

**Comment by ngfgrant** [comment]
Here is the only change that happening to our handling of Jinja between 2.2.1 and 2.3.0 https://github.com/Sceptre/sceptre/commit/6d4124bdc9d4d5277c3f5cdc5eb7d6db9696b667 - does this look like something that would have affected your setup?

**Comment by heikkima** [comment]
I believe `select_autoescape()` function is the reason why this doesn't work in 2.3.0.
I tried overriding autoescape with `{% autoescape false %}` and it fixed our problem ([link](https://jinja.palletsprojects.com/en/2.11.x/templates/#autoescape-overrides) to jinja2 documentation)

```
# ./config/dev/config-templates/tags.yml

sceptre_user_data:
  {% if stack_group_config.variables[stack_group_config.environment].tags is defined %}
  tagKeyPairs:
    {% autoescape false %}
    {{ stack_group_config.variables[stack_group_config.environment].tags }}
    {% endautoescape %}
  {% endif %}
```

**Comment by ngfgrant** [comment]
@heikkima Thanks for follow up with this. If you had time would you be willing to add a note into our documentation for this?
