### ISSUE TITLE
Duplicate parameter in stack config should produce either warning or error

### ISSUE THREAD

**Issue by oturpe** [Sceptre/sceptre#909]
Sceptre version: 2.3.0

If stack config contains the same parameter key more than once, Sceptre passes the last read value to the template, silently ignoring the others. This is not good, since such configuration is most probably an error (perhaps from misbehaving source control operation?). User should be given a clear indication that something may be off here.

## To reproduce:
Project folder hierarcy:
```
/
    config/
        config.yaml
        app/
            stack.yaml
    templates/
        stack.yaml
```

config/config.yaml:
```
region: eu-west-1
project_code: duplicateparams
required_version: '~=2.3.0'
template_key_prefix: templates
```

config/app/stack.yaml:
```
template_path: stack.yaml
stack_name: StackWithDuplicateParameter
parameters:
  Param: foo
  Param: bar
```

templates/stack.yaml:
```
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack with parameter

Parameters:
  Param:
    Type: String

Resources:
  TestResource:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "testresource-${Param}"
      RetentionInDays: 1
```

running `sceptre launch app` results in the following session that creates resource named `testresource-bar` and does not have any indication of discarding the competing `Param: foo`:
```
$ sceptre launch app
Do you want to launch 'app' [y/N]: y
[2020-06-18 17:08:06] - app/stack - Launching Stack
[2020-06-18 17:08:06] - app/stack - Stack is in the PENDING state
[2020-06-18 17:08:06] - app/stack - Creating Stack
[2020-06-18 17:08:07] - app/stack StackWithDuplicateParameter AWS::CloudFormation::Stack CREATE_IN_PROGRESS User Initiated
[2020-06-18 17:08:11] - app/stack TestResource AWS::Logs::LogGroup CREATE_IN_PROGRESS
[2020-06-18 17:08:11] - app/stack TestResource AWS::Logs::LogGroup CREATE_IN_PROGRESS Resource creation Initiated
[2020-06-18 17:08:16] - app/stack TestResource AWS::Logs::LogGroup CREATE_COMPLETE
[2020-06-18 17:08:16] - app/stack StackWithDuplicateParameter AWS::CloudFormation::Stack CREATE_COMPLETE
```

**Comment by ngfgrant** [comment]
Hey @oturpe 

Thanks for raising this issue. Sounds like we should make this more clear in the documentation. Would you be willing to submit a PR for this?

**Comment by oturpe** [comment]
Hey!

Ok, I can add a warning about this to the docs.

I still think this should produce a runtime warning or, even better, fail some kind of static analysis before anything is executed. But, we have stopped using Sceptre since I raised this issue, so my stake here is minimal. I'll send in a pull request about documentation update and consider this issue finished from my point of view.

**Comment by oturpe** [comment]
Here you go: https://github.com/Sceptre/sceptre/pull/940
