### ISSUE TITLE
Create changeset for new stack

### ISSUE THREAD

**Issue by dtlhlbs** [Sceptre/sceptre#915]
We'd like to create a changeset in our CI/CD pipeline before we execute it, so we can review changes and execute the change set manually. CloudFormation gives us the opportunity to `deploy` without executing via `--no-execute-changeset`, or to create a changeset with either CREATE or UPDATE `--change-set-type`. I don't think Sceptre has this ability? When we create a changeset for a stack that doesn't exist we get:

`"An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack [stack-name-goes-here] does not exist"`

And `launch` doesn't have an equivalent to  `--no-execute-changeset`.

**Comment by kirkhansen** [comment]
See issue #663. We were waiting on some scope clarification before proceeding.

**Comment by zaro0508** [comment]
it looks like the sceptre update command has a `--change-set` option, [the sceptre doc](Create a change set before updating.) says.. "Create a change set before updating".  Does this not work?
