### ISSUE TITLE
Add feature allowing merging of dictionaries

### ISSUE THREAD

**Issue by alexharv074** [Sceptre/sceptre#919]
As far as I can tell, there is no feature in Sceptre that would allow a dictionary to defined in a common YAML var file and then merge that with more specific dictionaries in other var files. Is this a feature that Sceptre might implement or accept a PR for?

**Comment by alexharv074** [comment]
If someone could explain to me how this code works here:
https://github.com/Sceptre/sceptre/blob/master/sceptre/cli/__init__.py#L69-L71

I would like to implement this to optionally merge the dictionaries specified in `var_file`.

**Comment by alexharv074** [comment]
I have a PR open but the build is broken apparently as a result of something unrelated to my change.

**Comment by zaro0508** [comment]
related to #604
