### ISSUE TITLE
Query : Can we set customize stack name while running sceptre create

### ISSUE THREAD

**Issue by nilbante** [Sceptre/sceptre#920]
When we run `sceptre create  test/new-vpc.yaml`. Its created stack name with **<proejctdir>test/vpc**
Is there any way we can customize that?

Another query, When we run **sceptre new project** <project_name>. Its asked for project name and region. Is there any way we can run this command without prompt for project name and region. I checked help but there is no such option.

We are using **sceptre** to run our automation. 

Thank you ..

**Comment by craighurley** [comment]
Yes.  Use `stack_name` in your stack config.  See the docs for more info: https://sceptre.cloudreach.com/2.3.0/docs/stack_config.html#stack_name

**Comment by nilbante** [comment]
Perfect.  That's what I want.
Thank you @craighurley.
Can we run **sceptre new project**  without asking prompt?
