### ISSUE TITLE
Any ETA for new release ? 

### ISSUE THREAD

**Issue by pipozzz** [Sceptre/sceptre#926]
Hello,

do you have some ETA for new release date?

Thansk

**Comment by ngfgrant** [comment]
Minor/patch or major?

**Comment by pipozzz** [comment]
Any of them, I'm especially interested in fix for execution of change-sets.

**Comment by pipozzz** [comment]
Any update?

**Comment by ngfgrant** [comment]
For v3 nothing set in stone yet. Still need to unpick all the aws specific stuff into its own provider. Minor or patch release can happen any time - I guess we are due one!

**Comment by pipozzz** [comment]
I would appreciated some minor/patch release with fix of executing empty change sets.
Thanks in advance.

**Comment by craighurley** [comment]
I'm also keen to see the greedy pattern matching from #731 in a formal release.

**Comment by zaro0508** [comment]
Just as a data point i've been using master in many of my repos and haven't noticed any problems.  However we don't use the change sets feature at all.

**Comment by ngfgrant** [comment]
I was getting round to this but then the build issue happened with networkx 2.4. With that reverted I think we can just push some tags and get master released.

**Comment by ngfgrant** [comment]
v2.4.0 now released apologies for the delay in this one. Will make sure to get a more continual release cycle going.
