### ISSUE TITLE
Support CloudFormation exports

### ISSUE THREAD

**Issue by nikolay** [Sceptre/sceptre#93]

**Comment by rdkr** [comment]
Sceptre supports resolving stack outputs from other stacks to use as parameters for Sceptre stacks, if that's what you mean?

http://sceptre.cloudreach.com/docs/stack_config.html#stack-output

**Comment by theseanything** [comment]
Nikolay could you clarify what you mean in the description? I assume you mean add the ability to determine stack order on outputs being exported and imported in dependent stacks?

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html

**Comment by nikolay** [comment]
Yup. The new feature.

**Comment by ngfgrant** [comment]
Sceptre will add support for dependency resolution using stack exports.

**Comment by ngfgrant** [comment]
With sceptre 2.0 strict handling of dependencies I am not sure this is required?

**Comment by bgdnlp** [comment]
It's been a while and I don't know how 2.0 handles it, but my point (if it helps) was to let AWS know about the dependency tree in order to benefit from whatever they do with it. Don't know if that happens now. Or if you consider that useful.

**Comment by craighurley** [comment]
Closing due to age and lack of updates.  If this is still a concern, please create a new issue.
