### ISSUE TITLE
Circle CI build fails on networkx==2.4 dependency

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#931]
PR #916 updated networkx to v2.4 however on a recent build I see the following message: "ERROR: Could not find a version that satisfies the requirement networkx==2.4".  I'm not sure why it's failing since that version is available https://github.com/networkx/networkx/releases/tag/networkx-2.4 and the `pip install  -r requirements/prod.txt` works fine for me on my local machine.

build from PR #879 : 
https://app.circleci.com/pipelines/github/Sceptre/sceptre/252/workflows/cfabdceb-6223-46c5-9d4d-4497718fb113/jobs/4941

```
#!/bin/bash -eo pipefail
. ./venv/bin/activate
pip install -r requirements/prod.txt
pip install -r requirements/dev.txt
pip install awscli

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting boto3<2,>=1.3.0
  Downloading boto3-1.14.50-py2.py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 9.7 MB/s eta 0:00:01
Collecting click<8.0,>=7.0
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 3.6 MB/s  eta 0:00:01
Collecting colorama==0.3.9
  Downloading colorama-0.3.9-py2.py3-none-any.whl (20 kB)
Collecting Jinja2<3,>=2.8
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 40.2 MB/s eta 0:00:01
ERROR: Could not find a version that satisfies the requirement networkx==2.4 (from -r requirements/prod.txt (line 5)) (from versions: 0.34, 0.35, 0.35.1, 0.36, 0.37, 0.99, 1.0rc1, 1.0, 1.0.1, 1.1, 1.2rc1, 1.2, 1.3rc1, 1.3, 1.4rc1, 1.4, 1.5rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7, 1.8rc1, 1.8, 1.8.1, 1.9rc1, 1.9, 1.9.1, 1.10rc2, 1.10, 1.11rc1, 1.11rc2, 1.11, 2.0, 2.1, 2.2rc1, 2.2)
ERROR: No matching distribution found for networkx==2.4 (from -r requirements/prod.txt (line 5))
```

**Comment by DG-SHeather** [comment]
The [setup.py](https://github.com/networkx/networkx/blob/fd0ecd22723cb30a365511d324841a85caad589c/setup.py) file from the networkx 2.4 release gives you the answer:

```python
if sys.version_info[:2] < (3, 5):
    error = """NetworkX 2.3+ requires Python 3.5 or later (%d.%d detected).
             
For Python 2.7, please install version 2.2 using:
$ pip install 'networkx==2.2'
""" % sys.version_info[:2]
    sys.stderr.write(error + "\n")
    sys.exit(1)
```

**Comment by zaro0508** [comment]
hmm, I though we removed python 2.7 in PR #922 ?  I'm not sure how python 2.7 is still getting into the build environment.  maybe you can shed some light on this @ngfgrant ?

**Comment by ngfgrant** [comment]
Yeh not sure I think that 2.4 only supports Py > 3.4/5

**Comment by zaro0508** [comment]
> Yeh not sure I think that 2.4 only supports Py > 3.4/5

I also don't see any references to python 3.4 or python 3.5 in this repo.

Doesn't the message `DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020` indicates that the build is still setup with python 2.7 somehow?  I see that the circle ci config is referencing a [sceptre docker image](https://github.com/Sceptre/sceptre/blob/master/.circleci/config.yml#L8), could that be the problem @ngfgrant?

**Comment by craighurley** [comment]
Debian:stretch ships with 2.7 and 3.5, where I assume 2.7 is the default: https://wiki.debian.org/Python#Supported_Python_Versions

**Comment by craighurley** [comment]
Is switching to this container an option: https://hub.docker.com/r/circleci/python, e.g. `circleci/python:3.8.5`

```
$ docker run --rm -it circleci/python:3.8.5 python --version
Python 3.8.5
```

**Comment by ngfgrant** [comment]
I've reverted the commit that upgraded to networkx 2.4 until I have more time to look into this. At least in the meantime master is green.

**Comment by zaro0508** [comment]
thanks @ngfgrant
