### ISSUE TITLE
Support AWS::Include

### ISSUE THREAD

**Issue by nikolay** [Sceptre/sceptre#94]

**Comment by theseanything** [comment]
Thanks! Yup having sceptre to be able to upload the require snippets to S3, before launch the stack with the AWS:Include would be handy.

**Comment by JuanCanham** [comment]
using AWS::Include and S3 objects, will be supported once https://github.com/cloudreach/sceptre/pull/326 lands

I also had a look at this for local codeURIs, when doing some SAM hooks, and couldn't figure out the value in this, as you would take local code, push it to s3, then have AWS put that code back into the template, the code should be simple though if somebody can explain the point of uploading include blocks to s3

**Comment by zaro0508** [comment]
Nobody can provide motivation for this feature request so closing.
