### ISSUE TITLE
stack_output does not take stack_name of source stack into account

### ISSUE THREAD

**Issue by RolandOtta** [Sceptre/sceptre#943]
i have stack a configured in a.yaml with a custom stack name (configured via stack_name stack parameter) `my-stack`.

then i have a stack b that is trying to resolve an output from stack a via `!stack_output a.yaml:myExport`.
instead of using my custom stack name `my-stack` the resolver is trying to use spectre´s default stack name for retrieving the export which results in an error `Stack with id [spectre default stack name] does not exist`

**Comment by craighurley** [comment]
Hi @RolandOtta ,

Have a look at the docs for this.  When you set a stack name with `stack_name`, you need to reference outputs differently, e.g.:

```
!stack_output_external a.yaml::myExport
```

https://sceptre.cloudreach.com/2.4.0/docs/stack_config.html

**Comment by RolandOtta** [comment]
sorry. my bad. thanks for pointing this out
