### ISSUE TITLE
sceptre list resources yaml error 

### ISSUE THREAD

**Issue by mundey** [Sceptre/sceptre#950]
to the code moderators
while reading about sceptre i got interested to use it. But apart from getting block at each stage, i got no joy. Can someone please help in responding what wrong am i doing (2.4.1, python 2.7 or 3.8):
1. list resources gave out error and i had to comment if else in the code and let it work with just available type
2. can't create change-set without stack, i had to add one clause to fix that. there is an issue already reported but how come a one liner fix has not been done in the code
3. tags, i had to read the code to actually know how to specify tags and to my amazement it still didn't work and got this error. why there is not a sinlge example of how to specify tags 
AttributeError: 'list' object has no attribute 'list'
till i had to remove the for loop and assign the struct straight to tags

Either I am doing something wrong or sceptre is not actively used

**Comment by craighurley** [comment]
My colleagues and I use it every day on multiple different client projects. 

The most recent release was a couple of weeks ago. 

Could you raise tickets for each of the issues with more details?

**Comment by zaro0508** [comment]
well if you look on pypi, sceptre isn't supported on python 2.4 and 3.8.  try running with python 3.7

> list resources gave out error and i had to comment if else in the code and let it work with just available type

you are probably running into issue #881

> can't create change-set without stack, i had to add one clause to fix that...

change set support is a relatively new, i think it was just added in sceptre ver 2.4.0 so please create GH issues if you see any.

> tags, i had to read the code to actually know how to specify tags and to my amazement it still didn't...

sceptre `stack_tags` works great for me on both ver 2.3.0 and 2.4.0

**Comment by mundey** [comment]
ok so, i tried to install 3.7 but sceptre gave error:

then on a second thought, considered using docker - 
docker container run -it -v $(pwd):/project --entrypoint='' cloudreach/sceptre:2.4.0 sh

sceptre list resources test-env/example.yaml
...
  File "/usr/local/lib/python3.6/site-packages/sceptre-2.4.0-py3.6.egg/sceptre/cli/helpers.py", line 80, in write
    output = "---\n".join(var)
TypeError: sequence item 0: expected str instance, dict found

**Comment by craighurley** [comment]
Post `test-env/example.yaml`

**Comment by ngfgrant** [comment]
@mundey as @craighurley asked please share more information about your project and please avoid unhelpful issue titles.

**Comment by mundey** [comment]
apology @ngfgrant, may you please close this issue?

@craighurley kindly refer to #951 specific to the first issue. i started to open issues separately.

also, can you please guide me how can i access community chat related to sceptre? that would be great for communicating with experts without creating issues. i would like to help improving the tool.
