### ISSUE TITLE
Launching a Plan Fails when Using Sceptre as a Module

### ISSUE THREAD

**Issue by jmsuzuki** [Sceptre/sceptre#954]
When trying to execute a Sceptre plan programmatically, the expected templates are loaded, but never executed.
```
from sceptre.context import SceptreContext
from sceptre.plan.plan import SceptrePlan

context = SceptreContext("/path/to/project", "command_path")
plan = SceptrePlan(context)
plan.launch()
```

**Comment by ngfgrant** [comment]
Hi @jmsuzuki do you have a `tree`  with the command path you are trying to execute. Our CLI utilises Sceptre as a module so I am thinking it might be something else?
