### ISSUE TITLE
Builds are failing with "Could not build wheels for cryptography"

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#956]
The circleci builds have been failing for the past week.. https://app.circleci.com/pipelines/github/Sceptre/sceptre

```
 ..
  Building wheel for cryptography (PEP 517) ... - \ | / - \ | error
  ERROR: Command errored out with exit status 1:
   command: /home/circleci/project/venv/bin/python2 /home/circleci/project/venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp0MeS7z
       cwd: /tmp/pip-install-6dyOyJ/cryptography
 ..
 ..
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

**Comment by zaro0508** [comment]
This seems like it might be a python 2.7 issue.  It looks like the build failed when attempting to build "wheel for cryptography"  using python 2.7 even though python 2.7 support was removed in PR #922.   

```
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.7" in ./venv/lib/python2.7/site-packages (from s3transfer<0.4.0,>=0.3.0->boto3>=1.9.201->moto<2.0.0,>=1.3.8->-r requirements/dev.txt (line 9)) (3.3.0)
Building wheels for collected packages: coverage, troposphere, parse, functools32, cryptography, jsondiff, cfn-lint, backports.ssl-match-hostname, pyrsistent, wrapt, future, filelock, scandir
  Building wheel for coverage (setup.py) ... - \ | / - \ done
  Created wheel for coverage: filename=coverage-4.5.4-cp27-cp27mu-linux_x86_64.whl size=202656 sha256=2557cda6b5f10e4d4807b2a0e80924627dab308fedb21539f14c8a2c8084c257
  Stored in directory: /home/circleci/.cache/pip/wheels/9e/c9/80/f07586da8015bd4cab1cae36b12a73b9f90062b22f3de36dcd
  Building wheel for troposphere (setup.py) ... - \ done
  Created wheel for troposphere: filename=troposphere-2.0.2-py2-none-any.whl size=89842 sha256=8137e96e6e4509d71651c72aa8caed0c8db37b1b2de06371c32e8035a10faefd
  Stored in directory: /home/circleci/.cache/pip/wheels/08/f2/b6/679260805e8f3c9d072b35809f8defd5170c6ef6603b2c2822
  Building wheel for parse (setup.py) ... - done
  Created wheel for parse: filename=parse-1.18.0-py2-none-any.whl size=24132 sha256=4c81e705337a16a926beefeb7f8bc2bb7cf7d5bcce3f0e0771d13288592e49be
  Stored in directory: /home/circleci/.cache/pip/wheels/00/2e/12/a728447a874a727bfea693e78bcec7cc1fdf1c86badd03e7af
  Building wheel for functools32 (setup.py) ... - done
  Created wheel for functools32: filename=functools32-3.2.3.post2-py2-none-any.whl size=14556 sha256=483ec03b85a19b30dc8752eac8e6fbb6a4e0663c09b5c8afda735b3d9fd5efb5
  Stored in directory: /home/circleci/.cache/pip/wheels/c2/ea/a3/25af52265fad6418a74df0b8d9ca8b89e0b3735dbd4d0d3794
  Building wheel for cryptography (PEP 517) ... - \ | / - \ | / error
  ERROR: Command errored out with exit status 1:
   command: /home/circleci/project/venv/bin/python2 /home/circleci/project/venv/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpVrpEKk
       cwd: /tmp/pip-install-L8179v/cryptography
  Complete output (948 lines):
```

I'm wondering if this might have something to do with the docker image `cloudreach/sceptre-circleci:0.4` using in the build step, https://github.com/Sceptre/sceptre/blob/master/.circleci/config.yml#L35 ?

**Comment by zaro0508** [comment]
updating docker container in PR #959 didn't fix the built, although i think it's the correct thing to do.

I'm wondering if updating to a newer version of alpine might help since it will get a newer version of openssl ? https://github.com/Sceptre/sceptre-circleci/blob/master/Dockerfile#L1

**Comment by zaro0508** [comment]
I believe I've figure this out.  The build is failing because the sceptre build is setup to use the Sceptre/sceptre-circleci docker container with alpine ver 3.7.  I've verified that updating Alpine to ver 3.11 works just fine.  The fix is to update Alpine to ver 3.11 in Sceptre/sceptre-circleci and then use that in the Sceptre/sceptre build.   That fix is in the following PRs: https://github.com/Sceptre/sceptre-circleci/pull/1 and https://github.com/Sceptre/sceptre/pull/959

**Comment by zaro0508** [comment]
It looks like the [sceptre-circleci build](https://app.circleci.com/pipelines/github/Sceptre/sceptre-circleci) is failing due to  a permissions issue. 
```
Using SSH Config Dir /home/circleci/.ssh
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by twelvelabs** [comment]
@ngfgrant it looks like CircleCI is [failing](https://app.circleci.com/pipelines/github/Sceptre/sceptre-circleci/9/workflows/6f6ee6df-8f2c-4765-8e2a-16745b4e5f3e/jobs/20) on the initial checkout w/ an invalid SSH key. Perhaps whatever SSH key was originally setup so that CircleCI could clone https://github.com/Sceptre/sceptre-circleci has been changed?

Is there any chance you (or someone w/ admin access to the sceptre-circleci GH and Circle projects) could sort this out soon? I'd like to try working on fixing #942, but will need CI running.

**Comment by zaro0508** [comment]
build has been fixed.
