### ISSUE TITLE
How to update a provisioned product for MSK

### ISSUE THREAD

**Issue by mskuser** [Sceptre/sceptre#962]
I have a two steps process :

1. Create a MSK cluster using scepter 
2. Update the MSK cluster with some configurations 

But while updating the MSK product in step 2 its failing with the error "Stack name already exsists". 

How can we update a msk cluster after provisioning ?

**Comment by craighurley** [comment]
Can you provide same sceptre config and cfn templates?

**Comment by zaro0508** [comment]
closing due to no response from reporter
