### ISSUE TITLE
Eliminate Dependency on "head_bucket" for template upload

### ISSUE THREAD

**Issue by GridGuy4** [Sceptre/sceptre#965]
on line 269 of sceptre/template.py, it raises an exception if an error message other than "Not Found" occurs.  We have a situation where our templates must be deployed from a single bucket, and we only have permissions on particular folders in that bucket. 
 There's a prod section & non-prod section - and non-prod roles do not have "head_bucket" permissions, so we hit the situation where exceptions are raised.

I have tested this by changing line 269 from:

    raise

to:

    self.logger.warning(
          "%s - received error with head_bucket, though template bucket exists '%s'", self.name, bucket_name 
    )
    return True                  

And it works fine.  If you had a situation where you don't have write permissions to the folder, then that would fail when you try to write - so it shouldn't make any difference.

Thanks.

**Comment by craighurley** [comment]
Hi @GridGuy4 , are you able to contribute a PR for this?

**Comment by GridGuy4** [comment]
I’m working with my company’s FOSS team to get my contribution approved. 

PR should happen this week.

**Comment by zaro0508** [comment]
too old and not a widespread problem for users.
