### ISSUE TITLE
--output option doesn't change output format of change-sets

### ISSUE THREAD

**Issue by yuripallada** [Sceptre/sceptre#975]
Hi,

Whenever I want to describe a change-sets' information on my terminal (oh-my-zsh), I just get the output, formatted as JSON, all on one line. It doesn't matter which `--output` parameter I add to the `sceptre describe change-set` command, It's always JSON, which is also incorrectly formatted json, as when I put it into a linter it produces errors.

Do you have any idea why that is happening and what I can do to resolve this? I'm working in Ubuntu using the oh-my-zsh terminal.

thanks!

**Comment by craighurley** [comment]
Hi @yuripallada , can you please provide an example config and template that causes this issue for you?

**Comment by yuripallada** [comment]
Hi @craighurley,

I have this issue with basically any Cloudformation template I roll out using Sceptre. I have attached an example of one such template and config, along with the output on my terminal when I describe the change-set.
What I did find out today is that if I have `--output json` I get somewhat formatted JSON output, but there's no coloring or anything.

Thanks for helping me with this.

Yuri.
[sceptre.zip](https://github.com/Sceptre/sceptre/files/6414623/sceptre.zip)

**Comment by zaro0508** [comment]
@yuripallada could you please provide the following info? 
* version of sceptre (sceptre --version)
* version of python (python --version)
* which OS/distro

**Comment by yuripallada** [comment]
@zaro0508

- version of septre: Sceptre, version 2.4.0
- version python: Python 3.8.8
- distro: Ubuntu-20.04 inside WSL2 on Windows.

**Comment by ngfgrant** [comment]
@yuripallada from your screenshot it looks like valid json to me. Are you saying that you would like it to have spaces/indents and newlines etc? 

If the formatting is the case can I recommend the tool `jq`. 

<img width="1680" alt="Screenshot 2021-06-28 at 20 35 26" src="https://user-images.githubusercontent.com/6362273/123693821-782b0280-d850-11eb-878d-853acb834cb6.png">

**Comment by yuripallada** [comment]
Hi @ngfgrant,

Thanks for this tip about jq. I knew about the tool, but didn't know that I could use it like this to format change-set output from Sceptre! I actually thought that Sceptre would have displayed that information formatted like this automatically, but at least I have something that works now.

I'll close the issue.
Yuri.
