### ISSUE TITLE
update sceptre docker image

### ISSUE THREAD

**Issue by zaro0508** [Sceptre/sceptre#992]
The official sceptre docker image for users to run sceptre is built on `python:3.6.8-alpine3.10`,  https://github.com/Sceptre/sceptre/blob/master/Dockerfile#L1

however the docker image for testing is based on alpine 3.13 https://github.com/Sceptre/sceptre-circleci/blob/master/Dockerfile#L1

We should update docker images to match.

**Comment by craighurley** [comment]
I will do that.
